### ISSUE TITLE
Bots don't award XP with correct config inside BGs/Arenas

### ISSUE THREAD

**Issue by Twiggstar** [liyunfan1223/mod-playerbots#102]
**Describe the bug**
When the option Battleground.GiveXPForKills is enabled, the bots don't award XP. Probably because they aren't considered a player.

**Commit hash**
658cc2fd6fe241a6c7b154d1d87ea69f258f9d32

**To Reproduce**
1. Go inside a BG with the option turned on.
2. Get a kill on bot.
3. Behold, no XP from the kill.

**Expected behavior**
Bot kill should award XP with the correct option set on.

**Additional context**
With addition to no XP given as the bots are not considered real players. Their bars aren't colored to the class with the option "Class color on nameplates" turned on. There has to be some way to trick the server to think they are visually players. Also i have no clue what class they are until they start using abilities because it doesn't show either in their description. They don't appear in recount no matter what settings i use, non trivial, trivial mobs, unknown mobs. It's like they don't exist.

**Comment by Twiggstar** [comment]
> Yo could try the addon called Details for DPS meters etc. at least bots do show up with correct scores.

Thanks for the alternative. But that is not the main issue here.

**Comment by Dreathean** [comment]
Yeah that's interesting....this was a problem with NPCBots, but that was expected since it used NPC creatures and not players. I can't imagine why Playerbots would experience this issue when they're using actual player characters.

**Comment by Dreathean** [comment]
@Twiggstar what was this closed for? Was the issue on your end?

**Comment by Twiggstar** [comment]
> @Twiggstar what was this closed for? Was the issue on your end?

Sorry, i was not available for a long time. I believe it was issue on my end. I think i posted the issue in the wrong place.
