### ISSUE TITLE
Bots occasionally change Talents even with EquipmentPersistence set

### ISSUE THREAD

**Issue by nl-saw** [liyunfan1223/mod-playerbots#104]
**Describe the bug**
Setting AiPlayerbot.EquipmentPersistence = 1 does not take talents into account. This leads to bots geared for lets say DPS might occasionally switch to Resto, etc. This is extremely annoying.

**Commit hash**
N/A

**To Reproduce**
1. N/A, see description.

**Expected behavior**
If bots are set to AiPlayerbot.EquipmentPersistence = 1 they should no longer change spec themselves but retain the one they are geared for once reached configured level (in my case 80). Perhaps have a switch in config setting this behavior.

**Comment by Dreathean** [comment]
Ah I did not know they did that and definitely agree spec should remain the same unless a player tells the bot to change their spec, and yes should be it's own separate config.

**Comment by Dreathean** [comment]
Yeah I'm still not sure of what the command is to change their spec even is if you can let me know? Tried searching the documentation. I personally have been holding off on moving forward with starting for real until a lot of this has been resolved and just trying to test things here and there when I can. Thankfully Liyunfan has made a ton of progress over the past several months so I am hopeful these will be fixed in time!

**Comment by Dreathean** [comment]
Ah, for some reason I kept trying .talents. So you whisper "talents" and it'll give you a list of options or do you just whisper for example a paladin "talents holy" and it's supposed to switch?

**Comment by Dreathean** [comment]
Followup on this: Whispered priest playerbot "talents spec holy pve" (from shadow priest spec) which worked great but priest is still only trying to deal damage and not heal in combat. I'm struggling to determine the command to change their roles, is this implemented at this time?

**Comment by liyunfan1223** [comment]
> Followup on this: Whispered priest playerbot "talents spec holy pve" (from shadow priest spec) which worked great but priest is still only trying to deal damage and not heal in combat. I'm struggling to determine the command to change their roles, is this implemented at this time?

Command `reset botAI` should work.

**Comment by Dreathean** [comment]
Got it, I will try it out when I get a chance, thank you!

**Comment by Dreathean** [comment]
Guessing this should now be fixed with commit 21e9e2e?

https://github.com/liyunfan1223/mod-playerbots/commit/21e9e2e2aa3e0f3ba01de2eea2ef4518b8dfd024

**Comment by liyunfan1223** [comment]
Yeah, it should be fixed.
