### ISSUE TITLE
Bots randomly unequip gear and refuses to accept certain gear.

### ISSUE THREAD

**Issue by nl-saw** [liyunfan1223/mod-playerbots#105]
**Describe the bug**
Bots just randomly unequip gear. Its shield, while being a tank. Its offhand while being a healer. Its 2nd Axe in case of DK, etc. Seems to be even worse when inventory is full.

**Commit hash**
N/A

**To Reproduce**
1. Gear up a few bots with high end gear
2. Have their bags full (this seems to amplify the problem)
3. Every now and then (usually at a fight start) bots will simply unequip major gear.
4. After fight they might decide to re-equip.

**Expected behavior**
Not to unequip gear, specially players'  alt accounts. Even if its considered OP.

**Additional context**
I suspect this has to do with gear(score)(stats) calculation, BOTS also will not take all phase 4 BIS items (useless/auctionhouse etc). Would be nice if they just take and equip whatever a player gives them manually, and/or have the EQUIP command to work, persistently.

**Comment by Dreathean** [comment]
Can confirm both have happened for me as well.

**Comment by Dreathean** [comment]
Yeah I imagine there are many commands not implemented yet since this project was ported over from the cmangos core, so there does remain a lot of bits that haven't been adjusted to Azerothcore

**Comment by liyunfan1223** [comment]
Fixed. https://github.com/liyunfan1223/mod-playerbots/commit/e6295e626077baea5fcb7f92c2355d4eb1ebbfe9
