### ISSUE TITLE
Today (2024/01/14) I updated AtherothCore and PlayerBots - a lot of errors appeared

### ISSUE THREAD

**Issue by MRafStudio** [liyunfan1223/mod-playerbots#106]
**Excerpt from the log:**

> Config: Missing property AiPlayerbot.PremadeSpecLink.1.0.0 in config file configs/worldserver.conf, add "AiPlayerbot.PremadeSpecLink.1.0.0 = " to this file or define 'AC_AI_PLAYERBOT_PREMADE_SPEC_LINK_1__0__0' as an environment variable.
> Config: Missing property AiPlayerbot.PremadeSpecLink.1.0.1 in config file configs/worldserver.conf, add "AiPlayerbot.PremadeSpecLink.1.0.1 = " to this file or define 'AC_AI_PLAYERBOT_PREMADE_SPEC_LINK_1__0__1' as an environment variable.
> Config: Missing property AiPlayerbot.PremadeSpecLink.1.0.2 in config file configs/worldserver.conf, add "AiPlayerbot.PremadeSpecLink.1.0.2 = " to this file or define 'AC_AI_PLAYERBOT_PREMADE_SPEC_LINK_1__0__2' as an environment variable.
> Config: Missing property AiPlayerbot.PremadeSpecLink.1.0.3 in config file configs/worldserver.conf, add "AiPlayerbot.PremadeSpecLink.1.0.3 = " to this file or define 'AC_AI_PLAYERBOT_PREMADE_SPEC_LINK_1__0__3' as an environment variable.

**He also talks about unknown spells (previously it was much less):**

CastSpell: unknown spell 89501 by caster GUID Full: 0xf13000797d00000c Type: Creature Entry: 31101  Low: 12
CastSpell: unknown spell 89502 by caster GUID Full: 0xf13000797d00000c Type: Creature Entry: 31101  Low: 12
CastSpell: unknown spell 89503 by caster GUID Full: 0xf13000797d00000c Type: Creature Entry: 31101  Low: 12
CastSpell: unknown spell 89505 by caster GUID Full: 0xf13000797d00000c Type: Creature Entry: 31101  Low: 12
CastSpell: unknown spell 89506 by caster GUID Full: 0xf13000797d00000c Type: Creature Entry: 31101  Low: 12
CastSpell: unknown spell 89501 by caster GUID Full: 0xf130007718000581 Type: Creature Entry: 30488  Low: 1409
CastSpell: unknown spell 89502 by caster GUID Full: 0xf130007718000581 Type: Creature Entry: 30488  Low: 1409
CastSpell: unknown spell 89503 by caster GUID Full: 0xf130007718000581 Type: Creature Entry: 30488  Low: 1409
CastSpell: unknown spell 89505 by caster GUID Full: 0xf130007718000581 Type: Creature Entry: 30488  Low: 1409
CastSpell: unknown spell 89506 by caster GUID Full: 0xf130007718000581 Type: Creature Entry: 30488  Low: 1409
CastSpell: unknown spell 89501 by caster GUID Full: 0xf1300079b100001b Type: Creature Entry: 31153  Low: 27
CastSpell: unknown spell 89502 by caster GUID Full: 0xf1300079b100001b Type: Creature Entry: 31153  Low: 27
CastSpell: unknown spell 89503 by caster GUID Full: 0xf1300079b100001b Type: Creature Entry: 31153  Low: 27
CastSpell: unknown spell 89505 by caster GUID Full: 0xf1300079b100001b Type: Creature Entry: 31153  Low: 27

[Errors.log](https://github.com/liyunfan1223/mod-playerbots/files/13930858/Errors.log)
[Playerbots.log](https://github.com/liyunfan1223/mod-playerbots/files/13930859/Playerbots.log)
[Server.log](https://github.com/liyunfan1223/mod-playerbots/files/13930861/Server.log)

**Comment by disgrace2013** [comment]
so do I !!!

**Comment by liyunfan1223** [comment]
Thank you for your quick feedback. Fix it in two steps, 1. Pull the latest update https://github.com/liyunfan1223/mod-playerbots/commit/368432963d31f7fa187490d3c4ac44bef745efb3 2. Overwrite the original configuration file with the latest playerbot.conf.dist

**Comment by MRafStudio** [comment]
Confirm. The problem with the errors "AiPlayerbot.PremadeSpecLink..." has been resolved. Thank you so much for your quick reaction! Your constant updates keep the heart warm!
And, more. I understand that this is not entirely related to this problem, but I would like to ask - what is the reason for bots casting missing spells in huge numbers, such as: 
89501, 89502, 89503, 89505, 89506? Is it possible to fix this in the near future?

**Comment by MRafStudio** [comment]
Among other things, thanks for all the updates. Currently, the server has been running without a single crash for more than 20 days! It's super!
