### ISSUE TITLE
建议增加当召唤指定的职业机器人离队后自动下线功能和召唤指定职业机器人时可设置坦克、奶或DPS的职责

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#110]
1、建议增加当召唤指定的职业机器人离队后自动下线功能
2、召唤指定职业机器人时可设置坦克、奶或DPS的职责或者由玩家切换机器人天赋和自动装备

**Comment by zbhcn** [comment]
顺便补充一个问题：worldserver.exe运行时间越长占用内存越大，刚启动时占用3.2G，运行5小时候占用7G，能否优化一下性能啊？内存都快不够用了

**Comment by oiuv** [comment]
> 顺便补充一个问题：worldserver.exe运行时间越长占用内存越大，刚启动时占用2.2G，运行5小时后占用5.7G，能否优化一下性能啊？内存都快不够用了。（服务器只有2个真人玩家在线，还有200个机器人玩家在线）

我的占用内存和你差不多啊，但我机器人才50个：

```
server info
AzerothCore rev. 6483d45598fb 2024-01-15 19:06:09 +0800 (Oiuvbot branch) (Win64, Release, Static)
Connected players: 1. Characters in world: 55.
Connection peak: 5.
服务器运行时间: 19 hour(s) 20 minute(s) 50 second(s)
Update time diff: 1ms, average: 4ms.
```

显示占用内存5849MB
