### ISSUE TITLE
【Feature request】漫游机器人交易保护机制

### ISSUE THREAD

**Issue by CoffeeFantasy** [liyunfan1223/mod-playerbots#113]
**描述：**
      漫游机器人很有特色，他们就像玩家一样能够自己升级打怪，希望这些机器人能更好的协助玩家升级和攻略副本。
      此需求是为了多人游戏时，防止恶意将漫游机器人装备全部卖掉兑换成金币，当其他玩家同它组队时，只能看到一个光杆司令。

**解决方案：**
     添加【漫游机器人控制等级】等级配置（此项只针对漫游机器人，召唤机器人保持现在规则）
     此配置只针对漫游型机器人，对召唤机器人不生效

配置【漫游机器人控制等级=$0】
   漫游机器人控制等级=0  可操纵行为:  无（对机器人做任何操作无效）
   漫游机器人控制等级=1  可操纵行为：装备、使用  、交易（给予）
   漫游机器人控制等级=2  可操纵行为：装备、使用、卖出、摧毁、交易（索取/给予）

   交易给予：可以给予漫游机器人金币/item，不可向随机机器人索要金币/item

**bug反馈：**
   1.给机器人穿上更高装等的装备后，过段时间机器人【副手】位置会重置为当前等级默认配置装备。（测试为70级装备、范围：全部机器人）
   2.有些机器人穿上高级装备后还是会将全部装备重置为当前等级默认配置装备。（测试为70级装备、范围：个别机器人）

**Comment by CoffeeFantasy** [comment]
以上只是个人想法，大家可以讨论下

**Comment by zbhcn** [comment]
话说怎么向机器人索要金币？

**Comment by CoffeeFantasy** [comment]
> 话说怎么向机器人索要金币？

好像是
机器人交易时需要给你3金7银5铜，尝试耳语   3g 7s 5c

**Comment by zbhcn** [comment]
你必须给出等价或接近你索要价格的物品，机器人才会确认交易

**Comment by oiuv** [comment]
> 你必须给出等价或接近你索要价格的物品，机器人才会确认交易

不会，实测，我直接和机器人交易，我啥也不给他，就在聊天中输入1000g，然后机器人就乖乖交易1000g给我

**Comment by zbhcn** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/116956612/33f421a1-4dfa-4079-96c4-7996948bc6d1)

**Comment by oiuv** [comment]
> 你是自己招的机器人吧，不是野外机器人吧？

哦，是的，我刚测了，我自己招的机器人和我的小号可以，测试了公会机器人和非公会机器人不行，那没事了，安全。

**Comment by oiuv** [comment]
> 你是自己招的机器人吧，不是野外机器人吧？

但是发现新的问题，我在游戏中禁用了addclass指令，但玩家可以用`.playerbot bot login`离线的机器人，他们上线后会自动成为召唤机器人，一样可以直接交易金币。

**Comment by CoffeeFantasy** [comment]
确实召唤机器人跟野外机器人对待策略还不太一样
遇到一个有趣的事情：我给野外机器人500G 他不跟我交易，我必须跟他要一块蚌肉他才肯收我500G,很有原则！哈哈

**Comment by CoffeeFantasy** [comment]
更新了下问题
