### ISSUE TITLE
当让机器人释放技能的时候选择切换副天赋就会陷入无限切换技能状态

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#117]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/116956612/a9e71203-ce96-40c2-9735-d1b5e514d8ac)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/116956612/81caefc2-df8a-40a9-ba0c-8175f8e323a4)

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/366
