### ISSUE TITLE
组机器人无反应是哪里的问题

### ISSUE THREAD

**Issue by alexyang-sea** [liyunfan1223/mod-playerbots#119]
我想请教一下为啥我邀请机器人组队没任何反应呢？配置文件都是默认没改动过，可能的原因会是什么呢

**Comment by CoffeeFantasy** [comment]
是不是等级不够啊，野外机器人是要看你等级的，好像差5级他们就不组你了
或者是编译问题？

**Comment by alexyang-sea** [comment]
不是，不管组多少级的都不行，连自己账号下的角色都无法组进来

**Comment by oiuv** [comment]
编译的问题吧？我的测试一切正常，你可以试试我的：https://wow.gameivy.com/

**Comment by alexyang-sea** [comment]
> 编译的问题吧？我的测试一切正常，你可以试试我的：https://wow.gameivy.com/

我指的不是单纯这个模块，不知道你编译了Alvin zhu的渐进端没？我是把他的合并了两种机器人的端编译后出现的，而且是12.29号之前的可以组队，29号后的源码编译出来的就无法无天机器人和自己账号下角色啦，也不知道到底是哪里出了问题

**Comment by oiuv** [comment]
> > 编译的问题吧？我的测试一切正常，你可以试试我的：https://wow.gameivy.com/
> 
> 我指的不是单纯这个模块，不知道你编译了Alvin zhu的渐进端没？[https://github.com/AlvinZhu/azerothcore-wotlk.git。](https://github.com/AlvinZhu/azerothcore-wotlk.git%E3%80%82) 我是把他的合并了两种机器人的端编译后出现的，而且是12.29号之前的可以组队，29号后的源码编译出来的就无法无天机器人和自己账号下角色啦，也不知道到底是哪里出了问题

没有，我不用第三方端，就用官方源端编译，你用其它的端那带来的问题就自己解决吧，至少可以肯定用官方最新的端编译都没毛病。
