### ISSUE TITLE
[Request] Set Level requirements for expansion-specific enchants

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#123]
**Is your feature request related to a problem? Please describe.**
Level 55-60 Playerbots are receiving BC enchants

**Describe the solution you'd like**
Ideally they would only receive Vanilla-related enchants until leveling to 61+.

**Additional context**
![WoWScrnShot_012424_141809](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/b8abd4b0-d74c-4e90-8625-f77bae3db48c)
![WoWScrnShot_012424_141755](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/a07ae211-fb29-4eef-ab25-555af6ed2815)

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/124fa9d5e05679c67606f231a9ef8ebb7e657672 

Now we can limit enchantment expansion by setting `AiPlayerbot.LimitEnchantExpansion` to 1 (default is 1).

**Comment by Dreathean** [comment]
Excellent! Thank you for adding this
