### ISSUE TITLE
Bots not queueing Rated Arenas

### ISSUE THREAD

**Issue by Twiggstar** [liyunfan1223/mod-playerbots#125]
**Is your feature request related to a problem? Please describe.**
I queue for Rated Arenas with a bot or with an other player. But after 20 minutes of sitting in queue nobody queues into us. Skirmish work but not ranked.

**Describe the solution you'd like**
I'd like to have them queue Ranked Arenas aswell.

**Describe alternatives you've considered**
Games from skirmish to award score for your team in specific bracket and arena points as usual.

**Additional context**
Worldserver console shows correct numbers of people/bots queueing for ranked arenas (my team only).

**Comment by Macx-Lio** [comment]
Hello Everyone,

I did have the same problem.
I tried to add the Arena Teams manuelle to the "arena_team"-Table.

I made a team for each race and added the level 80 Bot-Characters to it.
Then I took the first Bot-Character of each Team as Leader.

Now my Worldserver says for each Team:
Team #ID <Name of the Team> Group is ready for match.

But the Match wont start.

Here are my Questions:
How many Teams does a Arena-Match need to be ready?
Do I need more then 12 Teams?

IMPORTANT: Each Character could only be ONCE in a arena team.

**Comment by Dreathean** [comment]
This isn't currently functional, though I know @brian8544 has been working on it

**Comment by brian8544** [comment]
It seems very difficult to implement (for me at least), i did make 2 branches.

- arena, has some gibberish code which makes arenas somewhat queue.. sometimes xD

- prototype, decent code, but only makes arenas queue with 1 real player on both sides

I'd appreciate any help, coding wise - to shove me into the right direction

**Comment by Dreathean** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/406 fixed here!
