### ISSUE TITLE
The bot has no spells

### ISSUE THREAD

**Issue by hugoshao** [liyunfan1223/mod-playerbots#126]
hello. The bot is already level 80 and has learned all the skills, why don't I have any skills when I use 'spells'? and cannot release any spells

![image](https://github.com/liyunfan1223/mod-playerbots/assets/36898061/aca29dd2-eb72-4e82-85fb-f6127902e09a)

**Describe the bug**

**Commit hash**
The hash of the current commit.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by davvvve1** [comment]
**Why won't my bot cast spells?**

- Ensure the presence of the required English DBC file (enUS).

**Comment by hugoshao** [comment]
I am using the zh-CN client. If I need to use the enUS BDC file, it will error. Is there any other way I can fix it?

**Comment by hugoshao** [comment]
thanks I merged the BDC and the issue has been resolved.
