### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#127]
**Describe the bug**

clang-16: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:194: src/server/apps/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1030: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2

**Comment by davvvve1** [comment]
My mistake ;(  Worked now

**Comment by Dreathean** [comment]
Please close this issue since you no longer are experiencing it
