### ISSUE TITLE
Bots like follower dungeon in Dragonflight

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#129]
Dragonflight has now follower dungeons . It would be great to have them like that in server . Is it possible to make bots levelup/down in my lvl when i add them ? Great work !

**Comment by Dreathean** [comment]
You can already specify the level range that they spawn at. And you can set them to cap their max level to your highest player level.
![image](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/09247985-f295-47ed-9678-2a44bf22121c)

**Comment by davvvve1** [comment]
Thanks . Im gonna do that. I know they search for bgs but the dont search for dungeons . Or is it me that have not config it right?

**Comment by Dreathean** [comment]
On their own for dungeons? I don't believe so. But you can queue up for dungeons with them in your party and that should work!

**Comment by davvvve1** [comment]
Can i make them get to the player level they are in party with ?. Cause i wanna get my friends to play . I know that this is a single player project . Sorry for my dumb questions

**Comment by evrydayjunglist** [comment]
Enter the command ".playerbots bot init=auto" in-game while targeting a bot and it will put them at your level, maybe that will work for what you want?

**Comment by davvvve1** [comment]
> .playerbots bot init=auto

Dont work

**Comment by Dreathean** [comment]
Should this be closed? Their problem is resolved using the .playerbot add class to summon a new randombot if there aren't enouh in the level range which should be set via the config.
