### ISSUE TITLE
Mod cannot be compiled with an error message

### ISSUE THREAD

**Issue by pai1233** [liyunfan1223/mod-playerbots#130]
**Describe the bug**

In file included from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Action.h:11,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/Talentspec.h:8,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAIConfig.h:11,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.h:14,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.cpp:8:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Value.h: In member function ‘T CalculatedValue<T>::Get()’:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Value.h:56:142: warning: invalid use of incomplete type ‘class AiObjectContext’
   56 |                 PerformanceMonitorOperation* pmo = sPerformanceMonitor->start(PERF_MON_VALUE, this->getName(), this->context ? &this->context->performanceStack : nullptr);
      |                                                                                                                                              ^~
In file included from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.cpp:5:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.h:12:7: note: forward declaration of ‘class AiObjectContext’
   12 | class AiObjectContext;
      |       ^~~~~~~~~~~~~~~
In file included from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Action.h:11,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/Talentspec.h:8,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAIConfig.h:11,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.h:14,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.cpp:8:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Value.h:65:146: warning: invalid use of incomplete type ‘class AiObjectContext’
   65 |                     PerformanceMonitorOperation* pmo = sPerformanceMonitor->start(PERF_MON_VALUE, this->getName(), this->context ? &this->context->performanceStack : nullptr);
      |                                                                                                                                                  ^~
In file included from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.cpp:5:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.h:12:7: note: forward declaration of ‘class AiObjectContext’
   12 | class AiObjectContext;
      |       ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/10.5.0/cmath:45,
                 from /mnt/sdb1/azerothcore-wotlk/deps/fmt/include/fmt/format.h:36,
                 from /mnt/sdb1/azerothcore-wotlk/src/common/Utilities/StringFormat.h:22,
                 from /mnt/sdb1/azerothcore-wotlk/src/common/Debugging/Errors.h:21,
                 from /mnt/sdb1/azerothcore-wotlk/src/server/game/Battlegrounds/BattlegroundScore.h:21,
                 from /mnt/sdb1/azerothcore-wotlk/src/server/game/Battlegrounds/ArenaScore.h:21,
                 from /mnt/sdb1/azerothcore-wotlk/src/server/game/Battlegrounds/Battleground.h:21,
                 from /mnt/sdb1/azerothcore-wotlk/src/server/game/Battlegrounds/BattlegroundMgr.h:21,
                 from /mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/AiFactory.cpp:6:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.h: At global scope:
/mnt/sdb1/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.h:187:5: error: expected identifier before numeric constant
  187 |     HUGE   = 250
      |     ^~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [modules/CMakeFiles/modules.dir/mod-playerbots/src/AiFactory.cpp.o] Error 1
make[1]: *** [modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Commit hash**
azerothcore-wotlk   1ef5b9a6b49bfd05ca6ba09ca6e34de294a528bd
mod-playerbots     1a11ec0717e7448fc0204a72eb404e570e11129a

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/f2053a70-dc20-4333-a367-ee1fe5a9dec2)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/84bb4f6b-55b0-44f7-ad53-b9e25cec1ff2)

![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/9dc942c2-74fb-4ea8-b4ca-7b658f29a0a0)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/e549e554-9000-4213-880c-fb037c19bb21)
![1](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/aba297fc-816e-484a-813e-0e1f755f1733)

**Desktop (please complete the following information):**
 - OS: centos7.9

**Comment by pai1233** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/5ba9b556-2d00-4a11-ab0c-d494fddd6117)

**Comment by pai1233** [comment]
移除mod文件夹后可以编译成功

**Comment by davvvve1** [comment]
git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot
cd azerothcore-wotlk
cd module
git clone https://github.com/liyunfan1223/mod-playerbots.git --branch=master

**Comment by davvvve1** [comment]
Sorry . I dont understand your language

**Comment by pai1233** [comment]
> Sorry . I dont understand your language

Mod cannot be compiled with an error message
but after removing the mod, it can be compiled normally

**Comment by pai1233** [comment]
up cmake to cmake-3.28 this error is disappear

**Comment by davvvve1** [comment]
Compiled it today without any problems on arch . I had to reboot my computer just before i compiled it .

**Comment by pai1233** [comment]
> Compiled it today without any problems on arch . I had to reboot my computer just before i compiled it .

remove the error code HUGE ->250 and remove the HUGE code from the cpp file. After replacing it with large, the compilation can be completed

**Comment by pai1233** [comment]
remove the error code HUGE ->250 and remove the HUGE code from the cpp file. After replacing it with large, the compilation can be completed

**Comment by pai1233** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/ee4e4f87-7857-4154-9d96-f074c7188029)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/17326764/9a3e7d47-cdb4-4547-9dee-63eb27c67b35)
修改后可以完成编译，不清楚会有什么影响。
