### ISSUE TITLE
Can't compile with error:  => ERROR [ac-db-import internal] load metadata for docker.io/library/base:latest

### ISSUE THREAD

**Issue by weiyicheng** [liyunfan1223/mod-playerbots#131]
**Describe the bug**
Can't compile with error:  
=> ERROR [ac-db-import internal] load metadata for docker.io/library/base:latest
=> CANCELED [ac-client-data-init internal] load build context
=> CANCELED [ac-client-data-init skeleton  3/29] RUN apt-get update && apt-get install -y gdb gdbserver git dos2unix lsb-core sudo curl unzip   make c  1.5s
> [ac-db-import internal] load metadata for docker.io/library/base:latest:
failed to solve: base: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
**Commit hash**
Master

**To Reproduce**
git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot
cd azerothcore-wotlk
**mkdir module** (because there is no subdir module but **modules**)
cd module (Error is the same if I used **modules**)
git clone https://github.com/liyunfan1223/mod-playerbots.git --branch=master

**Expected behavior**
Server runs

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/16759800/52ba40eb-262e-4210-859d-3c707fdc6165)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Docker 25.0.3, build 4debf41
 - Docker Compose version v2.24.5

**Comment by alexyang-sea** [comment]
最新版我在windows下编译通过了，其它系统下就不知道啦

**Comment by weiyicheng** [comment]
After a hug change of the dockerfile I can finally compile. But it makes no sense because this docker can't load the bot modulle. I can't find what's wrong.

**Comment by liyunfan1223** [comment]
> You can use the Dockerfile from the main branch. A merge has not taken the revision of the Dockerfile into account.
> 
> In addition, the database "playerbots" must be added to the ac-worldserver service in docker-compose.yml.
> 
> AC_PLAYERBOTS_DATABASE_INFO: "ac-database;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_playerbots"
> 
> In addition, the automatic database update must be deactivated in the Playerbots conf file. So that the server starts without errors.
> 
> I am not familiar with the code of playerbots or the core but with my knowledge of Docker I was able to compile it successfully and my server is running. I can therefore not judge whether everything is taken into account.
> 
> Hope the short description helps.
> 
> Edit: [MrSlntGhost/azerothcore-wotlk-playerbots@8a1635b](https://github.com/MrSlntGhost/azerothcore-wotlk-playerbots/commit/8a1635bc6e5cd1af15c100970749bb69459d76ee)

Nice work! Could you please make a PR for your modification to https://github.com/liyunfan1223/azerothcore-wotlk. We can also make doc in readme or link to your solution for docker deployment.

**Comment by Dreathean** [comment]
Closing as it was fixed per the above merged PR
