### ISSUE TITLE
Auction

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#132]
Want them to buy and sell stuff on auction -

**Comment by Dreathean** [comment]
This would be a cool future addition but for the time being there is the AHbot or Auctionator module already for buying and selling items on AH.

**Comment by davvvve1** [comment]
Thanks . Gonna compile the module and try. Thanks !!!!

Den mån 12 feb. 2024 13:18Dreathean ***@***.***> skrev:

**Comment by scarecr0w12** [comment]
Sorry to reopen on this, But this will be handled in #2247
