### ISSUE TITLE
Init Command for everyone

### ISSUE THREAD

**Issue by Caxxo1** [liyunfan1223/mod-playerbots#135]
Allow GMs to use the init command on everyone, including owned playerbots and players

**Comment by MGPelaar** [comment]
@Caxxo1 
You can use init for every bot by disabling the random bot check in `modules\mod-playerbots\src\PlayerbotMgr.cpp` in line 554-556:

`if (!isRandomAccount || isRandomBot) {
    return "ERROR: You can not use this command on non-summoned random bot.";
}`

Just place `/*` at the beginning of line 554 and `*/` at line 556 (or delete the whole if statement). Then rebuild the server.
I also disabled this restriction and I could use `.playerbots bot init=*rarity* *botname*`.

Hope it helps.

**Comment by Dreathean** [comment]
@Caxxo1 if their answer suffices can you close this out?
