### ISSUE TITLE
The CPU usage is really hard to describe.

### ISSUE THREAD

**Issue by zhangbo8418** [liyunfan1223/mod-playerbots#137]
![QQ截图20240219170733](https://github.com/liyunfan1223/mod-playerbots/assets/46797568/292f5baa-cab3-4552-9e6b-bd9e2586629c)

**Comment by zhangbo8418** [comment]
> The fewer bots on your server, the less resource consumption.

The problem is that no matter what kind of CPU, no matter whether the CPU is strong or weak, I use ARM64 and x86_64 CPUs and there is always one CPU core that is 100%, which is outrageous.

**Comment by wowironforges** [comment]
development for now is just one person and only a few months old, the code optimization part is not yet the central focus I believe, but this base is perfectly good after @liyunfan1223  started working on it!

**Comment by liyunfan1223** [comment]
Do you have any real trouble? I don't think high CPU utilization is abnormal. It means your hardware is working, that's all.

**Comment by zhangbo8418** [comment]
> Do you have any real trouble? I don't think high CPU utilization is abnormal. It means your hardware is working, that's all.

High CPU usage is really not a problem. The problem is that no matter what kind of CPU it is, there is always one CPU core that is used at 100%.The htop command checks that there is always a CPU core usage of 100%.

Xeon® E-2174G
![Intel® Xeon® E-2174G](https://github.com/liyunfan1223/mod-playerbots/assets/46797568/9c9ffa9c-9b45-44c1-b705-ccabf95297c8)

J4125
![Intel® J4125](https://github.com/liyunfan1223/mod-playerbots/assets/46797568/bb6dc2f7-971a-4103-837a-6bc958024191)

Realtek RTD1296 SoC
![Realtek RTD1296 SoC](https://github.com/liyunfan1223/mod-playerbots/assets/46797568/60e013c2-7a59-4e54-9cfd-8ca42b2e51e8)

**Comment by noisiver** [comment]
I'm running 2 realms on a single system, one does not have playerbots but has preloaded grids and creatures set as active, and I don't run into this issue. I'm basically putting as much load as I can on the system, which is aarch64 hosted by Oracle, and it's still not maxing out.

![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/5e20c8a0-91d1-4d97-bdb4-14c79e37e52e)
