### ISSUE TITLE
Working great but

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#139]
**Describe the bug**
Sometimes the bots dont arrive to dungeons  in party . Need to type summon. Other than that the server is stable . Been up all week without a crash .  

**Commit hash**
latest commit
**To Reproduce**
1 . Que in dungeons

**Expected behavior**
Bots join when player join

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch Linux 
 - Browser [firefox]

**Additional context**
What are the dev planning on this = ? Are they like follower so meee like . Greetings from Sweden

**Comment by Dreathean** [comment]
@davvvve1 Can you elaborate more on what isn't working for you? When I queue with bots they teleport to the dungeon when I do.

**Comment by davvvve1** [comment]
But sometimes you need to use summon in partychat . I just press o and inviter bots.  Im not using the botaddon

**Comment by hermensbas** [comment]
duplicate
