### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#14]
There is just a typo in the new confs, they are loading with errors.

https://github.com/liyunfan1223/mod-playerbots/blob/b35b8ad99763674b4120af27974fdbf0d8c976b1/conf/playerbots.conf.dist#L552
https://github.com/liyunfan1223/mod-playerbots/blob/b35b8ad99763674b4120af27974fdbf0d8c976b1/conf/playerbots.conf.dist#L553

`> Config::LoadFile: Found incorrect option`

**Comment by liyunfan1223** [comment]
Fixed in https://github.com/liyunfan1223/mod-playerbots/commit/1d423e48205910e2d91373f2cd2fa85632d0cf18
