### ISSUE TITLE
Compiling VS17/WIN: Throwing warnings

### ISSUE THREAD

**Issue by nl-saw** [liyunfan1223/mod-playerbots#144]
**Describe the bug**
VS17/WIN:

15>D:\AzerothCore\RepoBots\modules\mod-playerbots\src\PlayerbotFactory.cpp(642,48): warning C4834: discarding return value of function with 'nodiscard' attribute
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(119,26): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(114,10): message : while compiling class template member function 'void Socket<AuthSession>::QueuePacket(MessageBuffer &&)' (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp(280,20): message : see the first reference to 'Socket<AuthSession>::QueuePacket' in 'AuthSession::SendPacket'
17>D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.h(64,28): message : see reference to class template instantiation 'Socket<AuthSession>' being compiled (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(202,34): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(191,10): message : while compiling class template member function 'void Socket<AuthSession>::WriteHandler(boost::system::error_code,size_t)' (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(158,33): message : see the first reference to 'Socket<AuthSession>::WriteHandler' in 'Socket<AuthSession>::AsyncProcessQueue' (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\shared\Network\Socket.h(119,26): message : see the first reference to 'Socket<AuthSession>::AsyncProcessQueue' in 'Socket<AuthSession>::QueuePacket' (compiling source file D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp)
17>D:\AzerothCore\RepoBots\src\server\apps\authserver\Server\AuthSession.cpp(280,20): message : see the first reference to 'Socket<AuthSession>::QueuePacket' in 'AuthSession::SendPacket'

**Commit hash**
https://github.com/liyunfan1223/mod-playerbots/commit/879f9113dae2b4d751963c7d5623c292cd89ee3a
&
https://github.com/liyunfan1223/azerothcore-wotlk/commit/0b0eeb05c91ac2bebbc4233cf900aaf69fd87c74

**Comment by hermensbas** [comment]
we are aware thanks though
