### ISSUE TITLE
请问大佬，机器人是不是不会排竞技场？

### ISSUE THREAD

**Issue by 13656694410** [liyunfan1223/mod-playerbots#145]
我看playerbot配置文件里有自动加入竞技场22的功能，但是我组了机器人签名成立战队，然后排2v2也找不到队伍，然后去数据库里创建了一些机器人的2V2队伍，也还是排不到，请问机器人是不是本身就没有打竞技场的功能？

**Comment by liyunfan1223** [comment]
Not supported so far. Honestly, I pay less attention to pvp and I am not that familiar with it. Looking forward to a fix.

**Comment by 13656694410** [comment]
好的，谢谢回答，期待修复

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/issues/125 Duplicated.
