### ISSUE TITLE
No need for unbot addon 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#147]
Is it a way that makes playerbots the same level as player invites them for group `? Or like when you use dungeon finder they automatic queded up?  Can someone guide me to a site that i can read more about playerbots or must i learn to code = ? Hope you understand my bad English

**Comment by Caxxo1** [comment]
For now that's impossible, but you can simply create a macro with ".playerbot bot init=auto" and spam it on the invited bots

**Comment by liyunfan1223** [comment]
Try using addclass and init commands.

For example:
1. `.playerbot bot addclass hunter`
2. Select the bot as target
3. `.playerbot bot init=auto`
