### ISSUE TITLE
The server crashes intermittently, and the following crash logs appear.

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#150]
Revision: AzerothCore rev. 0f6ab604a361+ 2024-03-08 15:27:47 +0800 (master branch) (Win64, Release, Static)
Date 12:3:2024. Time 10:48 
//=====================================================
*** Hardware ***
Processor: Intel Xeon Processor (Cascadelake)
Number Of Processors: 4
Physical Memory: 16776656 KB (Available: 7929204 KB)
Commit Charge Limit: 20970960 KB

*** Operation System ***
Windows Server 2016 Datacenter (Version 10.0, Build 14393)

//=====================================================
Exception code: C0000420 出现声明故障。

Assertion message: #----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location 'F:\azerothcore-wotlk-Playerbot\src\server\game\Entities\Object\Object.h:339'
# Function 'GridObject<class Player>::RemoveFromGrid'
# Condition 'IsInGrid()'
 
#----------------------------------------------------------------------#

Fault address:  00007FF602EE40C7 01:0000000000CB30C7 D:\Release\worldserver.exe

Registers:
RAX:002D002D002D002D
RBX:0000000000046796
RCX:002D002D002D002D
RDX:002D002D002D002D
RSI:000000000000001D
RDI:0000020E4E69A0B0
R8: 0054005200450053
R9: 0020004E004F0049
R10:004C004900410046
R11:0000000000000019
R12:0000020E50FD2690
R13:0000000000000016
R14:0000000000000011
R15:0000000000000001
CS:RIP:0033:00007FFAA1D26EA8
SS:RSP:002B:00000000B138DD50  RBP:B138DEC9
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000202

Call stack:
Address   Frame     Function      SourceFile
00007FFAA1D26EA8  00000072B138DE20  RaiseException+68
00007FF603638DAD  00000072B138DF10  ?Assert@Acore@@YAXV?$basic_string_view@DU?$char_traits@D@std@@@std@@I0000@Z+15D
00007FF602EE40C7  00000072B138E020  ?RemoveFromGrid@?$GridObject@VPlayer@@@@QEAAXXZ+117
00007FF602EE27E0  00000072B138E080  ?PlayerRelocation@Map@@QEAAXPEAVPlayer@@MMMM@Z+160
00007FF602E709FD  00000072B138E110  ?UpdatePosition@Unit@@UEAA_NMMMM_N@Z+1AD
00007FF603268C23  00000072B138E160  ?UpdatePosition@Player@@UEAA_NMMMM_N@Z+23
00007FF6030CE326  00000072B138E310  ?HandleMoveTeleportAck@WorldSession@@QEAAXAEAVWorldPacket@@@Z+B26
00007FF6023AB47B  00000072B138E3B0  ?HandleTeleportAck@PlayerbotAI@@QEAAXXZ+17B
00007FF6023BFC79  00000072B138E410  ?UpdateSessions@PlayerbotHolder@@QEAAXXZ+199
00007FF6034AEC41  00000072B138E440  ??$ExecuteScript@VPlayerbotScript@@@@YAXV?$function@$$A6AXPEAVPlayerbotScript@@@Z@std@@@Z+61
00007FF6034AF062  00000072B138E4B0  ?OnPlayerbotUpdate@ScriptMgr@@QEAAXI@Z+32
00007FF602CC70DC  00000072B138E900  ?Update@World@@UEAAXI@Z+65C
00007FF60227CA02  00000072B138EBA0  ?WorldUpdateLoop@@YAXXZ+662
00007FF60228CC6B  00000072B138F910  main+2DDB
00007FF60375CAB0  00000072B138F950  __scrt_common_main_seh+10C  D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FFAA29484D4  00000072B138F980  BaseThreadInitThunk+14
00007FFAA5331791  00000072B138F9D0  RtlUserThreadStart+21

**Comment by zbhcn** [comment]
By the way, this file（Object.h） is an official file and has not been customized.

**Comment by zbhcn** [comment]
> 我用最新版编译后，服务器变的非常卡，玩家都没法正常游戏了。

你把这个函数改一下就好了，函数在PlayerbotFactory.cpp里的：
void PlayerbotFactory::Init()
{
    // 预处理数据，减少循环次数
    std::vector<uint32> validQuestIds;
    for (auto& entry : sObjectMgr->GetQuestTemplates())
    {
        uint32 questId = entry.first;
        Quest const* quest = entry.second;

        if (quest->GetRequiredClasses() && !quest->IsRepeatable() && quest->GetMinLevel() >= 10)
        {
            validQuestIds.push_back(questId);
        }
    }

    // 处理有效任务
    for (uint32 questId : validQuestIds)
    {
        AddPrevQuests(questId, classQuestIds);
        classQuestIds.remove(questId);
        classQuestIds.push_back(questId);
    }

    // 处理特殊任务
    for (uint32 questId : sPlayerbotAIConfig->randomBotQuestIds)
    {
        AddPrevQuests(questId, specialQuestIds);
        specialQuestIds.remove(questId);
        specialQuestIds.push_back(questId);
    }

    // 处理附魔法术
    for (uint32 id = 1; id < sSpellMgr->GetSpellInfoStoreSize(); ++id)
    {
        SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(id);
        if (!spellInfo)
            continue;

        for (uint8 j = 0; j < MAX_SPELL_EFFECTS; ++j)
        {
            if (spellInfo->Effects[j].Effect != SPELL_EFFECT_ENCHANT_ITEM)
                continue;

            uint32 enchant_id = spellInfo->Effects[j].MiscValue;
            if (!enchant_id)
                continue;

            SpellItemEnchantmentEntry const* enchant = sSpellItemEnchantmentStore.LookupEntry(enchant_id);
            if (!enchant || enchant->slot != PERM_ENCHANTMENT_SLOT)
                continue;

            enchantSpellIdCache.push_back(id);
        }
    }

    LOG_INFO("playerbots", "Loading {} enchantment spells", enchantSpellIdCache.size());

    // 处理附魔宝石
    for (auto& entry : sSpellItemEnchantmentStore)
    {
        uint32 gemId = entry.GemID;
        if (gemId == 0) {
            continue;
        }
        ItemTemplate const* proto = sObjectMgr->GetItemTemplate(gemId);
        if (!proto || !sGemPropertiesStore.LookupEntry(proto->GemProperties)) {
            continue;
        }
        enchantGemIdCache.push_back(gemId);
    }

    LOG_INFO("playerbots", "Loading {} enchantment gems", enchantGemIdCache.size());
}

**Comment by LitchLight** [comment]
Similar random crashes while idle.

GDB output below 

: )

[idle.crash.txt](https://github.com/user-attachments/files/15744010/idle.crash.txt)

**Comment by liyunfan1223** [comment]
Fixed. https://github.com/liyunfan1223/mod-playerbots/pull/355
