### ISSUE TITLE
Improve bots ability to navigate tricky dungeons

### ISSUE THREAD

**Issue by Mr-Deadbeat** [liyunfan1223/mod-playerbots#152]
**Is your feature request related to a problem? Please describe.**
when doing Shattered Halls in Outlands the bots run through the locked door into Netherkurse's chamber and pull every mob on the way with them resulting in a wipe

**Describe the solution you'd like**
would be nice if the bots would know how to jump down into the hole where the oozes are since that is the normal way of doing it unless you have a rogue who can pick the lock into the chamber

**Describe alternatives you've considered**

**Additional context**
![WoWScrnShot_031224_182254](https://github.com/liyunfan1223/mod-playerbots/assets/58752069/0ce8ede3-8566-4d23-890c-dccb9e1ee851)
![WoWScrnShot_031224_182245](https://github.com/liyunfan1223/mod-playerbots/assets/58752069/d8c140fb-6b9a-4a85-a23f-d22d9c013b8e)

**Comment by Dreathean** [comment]
Liyunfan is working on improving bot capabilities in raids and possibly eventually certain dungeons such as this, but I imagine that will be a long time. In the meantime I imagine you should be able to work around this issue by jumping then immediately using the summon command, assuming you aren't in combat
