### ISSUE TITLE
Converting attack targets and concentrating attack commands are invalid for bots

### ISSUE THREAD

**Issue by wowlove1133** [liyunfan1223/mod-playerbots#154]
Converting attack targets and concentrating attack commands are invalid for bots

**Comment by Dreathean** [comment]
I wonder, along this topic, if it would be possible to add a command to whisper bots target based on icon/marker, ie you set Skull on target A and Square on target B and you can whisper certain bots "target skull" and "target square" for more control in boss fights where you need to split attackers/have an off-tank tank a separate target, etc. I did look through the IKE documentation and that does not appear to be something they implemented in their MANGOS version so not sure if it is possible.

**Comment by cj-br** [comment]
The command “ attack my target” is still invalid. The robot will not follow the command to attack, but will only attack what it wants to attack. How should this be set？

**Comment by Dreathean** [comment]
Closing as this has been fixed!
