### ISSUE TITLE
There are a large number of memory leaks in the code

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#158]
There are a large number of memory leaks in the code, causing the system memory to constantly increase without decreasing, eventually leading to a crash. Of course, with 16GB of memory, the system can last for more than 24 hours, but if you have less than 16GB of memory, it will crash after running out of memory.

**Comment by liyunfan1223** [comment]
This is normal, the memory usage continues to grow until all maps grids are loaded. You can set PreloadAllNonInstancedMapGrids to load all maps when starting the server. There have been many related discussions in the azerothcore community https://github.com/azerothcore/azerothcore-wotlk/issues/2280

Of course, It cannot be ruled out that there has some memory leaks, but I think the phenomenon you observed is not related to memory leaks.

**Comment by zbhcn** [comment]
Maybe you are right, but if there is no playerbots module with the same parameters, the memory usage of AzerothCore will increase and then decrease after a while.However, if there is a Playerbots module, the system memory usage will always continue to increase and never decrease.

**Comment by zbhcn** [comment]
> Maybe you are right, but if there is no playerbots module with the same parameters, the memory usage of AzerothCore will increase and then decrease after a while.However, if there is a Playerbots module, the system memory usage will always continue to increase and never decrease.

**Comment by Dreathean** [comment]
So just to confirm, you have indeed had crashes due to memory capping 16 GB? I wonder if anyone has tested with >16GB? It could be that with Playerbots it steadily increases up to a certain point just beyond 16 GB since it is much more involved than the regular core.

**Comment by zbhcn** [comment]
> So just to confirm, you have indeed had crashes due to memory capping 16 GB? I wonder if anyone has tested with >16GB? It could be that with Playerbots it steadily increases up to a certain point just beyond 16 GB since it is much more involved than the regular core.

There is no crash, but this mod almost occupies all the memory of the server.When I optimize the code, it occupies approximately 3.0GB to 4.0GB of memory now.

**Comment by Dreathean** [comment]
Nice, so you have found and resolved the issues causing the heightened memory levels? Will you be submitting a pull request to share?
