### ISSUE TITLE
add support for bots to avoid AOE damage

### ISSUE THREAD

**Issue by Mr-Deadbeat** [liyunfan1223/mod-playerbots#160]
**Is your feature request related to a problem? Please describe.**

problem is when you do instances or other events in the world and there is AOE damage involved fire on the ground or other similar
hazards the bots just stand in it until dead unless you force them to move out of it with follow does not work every time so bots just end up dead

good example of this is Shattered Halls in Outlands the gauntlet run where the archers shoot fire arrows i lost my whole team in there on the first try also due to bots seeing corpses to loot with no regard to the raging fires around them i did figure out later today that you can disable looting for the bots while being master looter myself so that should take care of the looting issue for the time being

this is also a problem in The Steamvault first boss uses a lot of AOE and tank needs to kite the boss around the room while ranged kill her off

**Describe the solution you'd like**

figure out a way for the bots to avoid AOE damage

**Comment by Mr-Deadbeat** [comment]
> This is a particularly tough one that NPCbots doesn't have resolved either. Curious what Liyunfan's thoughts are on this.
> 
> Also godspeed on using these without having a player handle the tank role

actually trickerer has made good progress on some of the AOE issues but i prefer these bots having 10+ macros to control trickerers bots is a pain in the you know what also lately some spells can't be cast on NPCs anymore so cause huge issues with casting Resurrection, Revive, among others so need special macros to be able to use them which makes it even more of a hassle due to game client having a limited set of macros you can create

when it comes to controlling these bots and having lets say a warrior as Tank works pretty well just need to know about their limitations and that they do rush off if they see something in the distance causing threat to the group so best strategy i have found is going around corners and doing the pull yourself let the mobs chase you around the corner and the bots take it from there :)

also use this macro to help with some of the issues

/p Changed 5 Man Strategy
/w Tank co +tank, +aoe
/w Priest co +heal, +cure
/w Paladin co +dps, +dps assist, +heal, +cure
/w Ranged co +dps, +aoe
/p nc +bmana, bdps, -loot

last line -loot need to be master looter but it prevents the bots from looting mid combat it does mean that it will be a chore to pick all those shinies ;) also a nice side effect from -loot is the bots do not have additional gear in their bags to switch to at times they switch their gear at random highly annoying last night my rogue had switched his offhand dagger for a offhand spell casting item like wth !!

**Comment by liyunfan1223** [comment]
This is possible, but is a bit complicated. Simply put, the bot can identify AOE spells (such as rain of fire) and avoid them based on simple rules, such as staying away from the center of the spell, or moving to the left or right. But such avoidance is likely to have negative effects, especially on complex or narrow terrain, making them look less smart.

Maybe I will add an experimental avoid AOE feature later and discuss it further.

**Comment by Dreathean** [comment]
Yeah there is definitely a ton of situational nuance that makes it seem extremely challenging if not impossible for a one-size-fits-all answer. 

Still, if you are able to implement an experimental avoid AOE feature, even if simple in nature to begin with, that would enable us to determine those situational shortcomings in practice and see what needs to be adjusted to improve it. That could be a tremendous addition to the playerbots one day!

**Comment by Mr-Deadbeat** [comment]
i can imagine it being tricky to solve i'll be happy to test it out on my server if such a feature is implemented
you could check trickerers solutions to some of the issues and how he might have solved them as well

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/183 

Now an experimental avoid aoe feature has been implemented. To test this feature, please update the module to the latest version and set the configuration `AiPlayerbot.AutoAvoidAoe` to 1 (default is 0), or use the command `co +avoid aoe`.

It seems to work well with some general spells, such as "Rain of Fire" for Naxxramas Faerlina or "Cave In" for Gruul. However, there are also many spells for which it doesn't work. Technically, these spells operate on different principles, making it difficult to cover all situations. Testing and providing specific examples would be helpful for further improvement. Thank you for any help or suggestions!

**Comment by Dreathean** [comment]
Awesome! Will definitely let you know of any specific instances I encounter issues with. Thank you for all your additions and improvements as always

**Comment by Mr-Deadbeat** [comment]
here are some of my findings from last night i tested shattered halls since it gave me issues in the past
bots do avoid aoe when archers or spell casters cast either rain of fire or volley also they seem to avoid the fire hazards in the fire gauntlet what they do not do is avoid Netherkurze's Consumption spell they just stand in it until dead other than the boss fight avoid aoe feature is working very well did not see any strange behaviour
they just stepped out of the danger and that kept me going :) great job thus far

also ended up with a crash inside shattered halls during the first part of the instance when you get ambushed the first group of mobs has triggered crashes on 3 different occasions for me but after server restart it has not happened again so it's random tried to debug it last night with gdb but the crash never triggered so my findings did come up empty at the time of the crash the server had been online for almost 2 days so wondering if something goes wrong somewhere along the way and when all pieces fall into place it triggers the crash

at the moment i'm waiting for more ram to arrive for the server so i can setup a test server where i can test freely cases like the above one my buddy gave me a hard time since he could not jump in and play when i was debugging so going to setup a test realm once the ram gets here :) did spot other problems with the bots but will create other issues for them to keep them separate

**Comment by Dreathean** [comment]
That is awesome to hear! Sounds very promising

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/198 I updated to cover more spells, like consumption for Netherkurze, and fixed a crash issue here.

**Comment by Mr-Deadbeat** [comment]
> #198 I updated to cover more spells, like consumption for Netherkurze, and fixed a crash issue here.

ok sounds great i will test it shortly

**Comment by Mr-Deadbeat** [comment]
just finished a test run in Shattered halls and this was the smoothest run thus far not a single issue also bots stepped out of Netherkurzes Consumption so it is working very well :) great job although have not tried the dreaded pit to get to the boss have used my Rogue every time since he can unlock the door :)

i did however notice the diff times spiking up to 16k+ shortly after server start that got me a bit worried although it settled down after a while figured the bot code is doing something in the background to prep the random bots
currently the diff times are showing 91, 106, 129 this is on the client side

**Comment by Mr-Deadbeat** [comment]
yeah the issue can be closed so far the bots have worked very well with avoiding AOE might be there needs to be some polishing here and there but they work well enough as far as i can tell :)
