### ISSUE TITLE
(Naxxramas 40) More raid scripts for raiding with bots

### ISSUE THREAD

**Issue by Fer0Fer0** [liyunfan1223/mod-playerbots#167]
**Is your feature request related to a problem? Please describe.**
It's pretty tough to raid with playerbots, i usually find myself having to micromanage and revive dead bots during raid encounters, specifically "Naxxramas classic 40man", which is being integrated to both mod-progression and individual-progression-mod.

**Describe the solution you'd like**
more raid scripts for each boss encounter in raids, so that the bots don't just charge in and die.

**Describe alternatives you've considered**
Scripts for only difficult bosses, like Ragnaros, Garr, C'thun ect.

**Additional context**
I do not have any video or screenshots unfortunately

**Comment by Dreathean** [comment]
As Liyunfan said in https://github.com/liyunfan1223/mod-playerbots/issues/162, it is a long term goal overall for raiding scripting,  and I can't speak for them of course, but I don't foresee scripting being implemented for a raid only available via a separate module like Naxx40 from the individual progression module.

**Comment by Dreathean** [comment]
@Fer0Fer0 Can you please close this out as this is already a part of the long term development goal?
