### ISSUE TITLE
Playerbot fails to compile with liyunfan123/azerothcore-wotlk of last week (latest)

### ISSUE THREAD

**Issue by doowahree** [liyunfan1223/mod-playerbots#168]
**Describe the bug**
For https://github.com/liyunfan1223/azerothcore-wotlk/commits/Playerbot commit 97604fab77ba00c0fe8150d46508e9682d4e7188, compile fails due to https://github.com/liyunfan1223/azerothcore-wotlk/commit/b1ee6cfe06865674be3419f56499720496ea881b#comments. The spawnId is gone now but is referenced by https://github.com/liyunfan1223/mod-playerbots/blob/e6295e626077baea5fcb7f92c2355d4eb1ebbfe9/src/PlayerbotAI.cpp#L1817 and another place.

**Commit hash**
e6295e626077baea5fcb7f92c2355d4eb1ebbfe9

**To Reproduce**
Pull latest of liyunfan1223/azerothcore-wotlk, install this module, compile fails.

**Expected behavior**
Compile succeeds.

**Desktop (please complete the following information):**
 - Windows

**Comment by Dreathean** [comment]
Just updated both to latest with no issues, that's strange

**Comment by papwuj** [comment]
I have the same problem.

**Comment by liyunfan1223** [comment]
Have you pulled the latest module?

**Comment by Mr-Deadbeat** [comment]
tried make clean before building ? sometimes i have forgotten that and end up with all kinds of strange behaviour when compiling

i'm running the same version and just now compiled the new upstream fixes that @liyunfan1223 just merged and have not had a single issue although i run on ubuntu system over here saw now that you use windows

**Comment by davvvve1** [comment]
The easiest way to fix it is by dropping your database and importing it again. That helped me . I just opened up dbbeaver or heidisql and removed  all acoredatabases and imported them again with https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/create/create_mysql.sql

**Comment by doowahree** [comment]
With new pull this doesn't seem to be a problem. I will close this issue!
