### ISSUE TITLE
PARTY BUG

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#17]
This bug is pretty easy to reproduce.

All you have to do is enter a party with 2 or more bots and being the leader of the party, if he leaves the party goes to the other bots who do not log out and do not play until the server is restarted.

**I would like to emphasize my gratitude for this mod, the bots are very, very good, the progress is incredible.**

**Comment by liyunfan1223** [comment]
I misunderstood the problem earlier and I will check again.

**Comment by garfieldz90** [comment]
> > Fixed in [1c47108](https://github.com/liyunfan1223/mod-playerbots/commit/1c47108c2399fff5c240100726251297448c9656) Now if the leader is far away from the bot, it will leave the group and continue the right behaviors.
> > Thanks also for your contribution and efforts!
> 
> This problem still exists, I was leader of 4 bots, I waited for my character to disconnect from the game and the account, when I came back the 4 bots were still in the party and I can't invite them anymore.

some time they cant join you again case they still in a party, u need whisper any of bot say "who" to get who is the leader of party, and whisper him "invite" to invite you to they party,  say "/p give leader" in party chat after you join the party then you will the party leader again! hope this will help, this not  bug, i think.

**Comment by liyunfan1223** [comment]
Bots now automatically leave the group.

https://github.com/liyunfan1223/mod-playerbots/commit/966c33f9446b11960c0145ce5ea67c0c9eb03b32
