### ISSUE TITLE
Zelemar the Wrathful 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#174]
**Describe the bug**
Zelemar The Wrathful spaws 2 times in dungeon Ragefire Chasm

**Commit hash**
Latest 

**To Reproduce**
1. Go to 'the boss urne '
2. stand on urne
3. Scroll down to Watch  2 of Zelemar spawn - 

**Expected behavior**
One Zelemar

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dreathean** [comment]
I can't imagine this is related to the Playerbots module, this has got to be a core issue and this should be posted on the core github

**Comment by Dreathean** [comment]
@davvvve1 please close this out as this has nothing to do with Playerbots module

**Comment by Dreathean** [comment]
Closing as this is unrelated to Playerbots.
