### ISSUE TITLE
Maybe it's a bug，Using “init ” commands in combat，Robots will come back to life

### ISSUE THREAD

**Issue by cj-br** [liyunfan1223/mod-playerbots#179]
In the battle of ICC's fourth boss，I found that using initialization commands can eliminate robot imprints。
And the dead robot will be directly resurrected after being initialized。
I think this is a bug。
The initialization command should not be available during combat。

**Comment by Dreathean** [comment]
There is a .conf option that makes it so the init command is only available to GMs, is that not a solution for you?

**Comment by Dreathean** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/334/commits Resolved
