### ISSUE TITLE
[Question] Playerbots and AuctionHouse

### ISSUE THREAD

**Issue by Wantedslv** [liyunfan1223/mod-playerbots#184]
Is it real to make bots use AH?

**Comment by oiuv** [comment]
这个机器人好像不支持AH，希望增加支持。

**Comment by Wantedslv** [comment]
Thanks, oiuv. I hope it will work in the future.

**Comment by liyunfan1223** [comment]
Maybe use mod-ahbot instead. https://github.com/azerothcore/mod-ah-bot

**Comment by oiuv** [comment]
> Maybe use mod-ahbot instead. https://github.com/azerothcore/mod-ah-bot

我现在用的就是这个，这个美中不足的是只能指定一个固定的角色挂拍卖行。

**Comment by Dreathean** [comment]
This has come up a few times. I agree there are drawbacks to AHBot and Auctionator, but for now I feel they are reasonable options for people who wish to use the AH. I imagine it would take a lot of development time to combine Playerbots with either of them, and right now there are more critical areas of improvement for Playerbots. It is of course entirely up to Liyunfan what they wish to do, just my thoughts on this.

**Comment by PrymetymeGaming** [comment]
I do see when they loot some greens and blues they say AuctionHouse. Can bots post on the AH? If they can't can Ah-bot mode compile fine with Playerbots?

**Comment by Dreathean** [comment]
That is not implemented at this time, no. You can definitely compile either AH-bot or Auctionator just fine with Playerbots. I've done both with no issues.

**Comment by PrymetymeGaming** [comment]
What one did u like of the two?

**Comment by Dreathean** [comment]
To be honest I previously used AHbot a lot and only recently and trying out auctionator. AHbot is missing a lot of trade goods, food, etc but works well enough for equipment. Auctionator is fairly newer and more actively developed so I think it is more promising, but haven't been able to try it too much yet.

**Comment by Dreathean** [comment]
@Wantedslv can you please close this as I do not anticipate there being any near term development on playerbots + AH and there are existing options with AHBot and Auctionator
