### ISSUE TITLE
What version of MySQL is supported?

### ISSUE THREAD

**Issue by youngsing** [liyunfan1223/mod-playerbots#19]
Sorry, I'm not familiar with MySQL, but it seems that this sql statement below is not supported in 5.7? Is it only supported on 8.0 and above?
https://github.com/liyunfan1223/mod-playerbots/blob/b0ef775510dbe6480c20f0619262128e13c9725d/src/RandomPlayerbotMgr.cpp#L1112-L1145

After compiling with the latest version of the code and MySQL 5.7.43, running `worldserver` gives the following error
```
[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GroupedData AS ( SELECT MIN( c.guid ) guid, (AVG( t.maxlevel ) + AVG( t.minlevel' at line 1
Error while parsing SQL. Core fix required.

```

**Comment by liyunfan1223** [comment]
Confirmed that it's only support on mysql 8.0 and above, but it seems unnecessary to write in this way.

I'll rewrite it and make it compatible with mysql 5.7.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/55fe060e2cabca31827d30a914c9d446e4c61fcf

**Comment by youngsing** [comment]
Thank you! 
I test the latest code with MySQL 5.7.43, it works fine now.
