### ISSUE TITLE
Bots fall behind they seem to have different movement speed to player

### ISSUE THREAD

**Issue by Mr-Deadbeat** [liyunfan1223/mod-playerbots#196]
**Describe the bug**

when running around with your bots either walking / riding / flying
bots always fall behind and you have to stop and wait for them

they seem to have different move speed compared to a human player

also when playing with my hunter aspect of the pack does nothing it seems or the aura affects them but due to the above mentioned speed difference they still fall behind

**Commit hash**
Core: 10bd872f2d1013393946840a0179e2e08ba6740e
Bots:  e003ce99f0eed19d6166384d669e6d5ad0da7ba7

**To Reproduce**
1. login with your character
2. summon your team of bots
3. walk around / ride / fly

**Expected behavior**

bots should be able to keep up with master match his movement speed unless master has speed altering buffs
for example enchants or trinkets that buffs his movement speed

**Screenshots**

**Desktop (please complete the following information):**
 - Server ubuntu 22.04.3

**Additional context**

**Comment by Dreathean** [comment]
@Mr-Deadbeat Can you see if you are still experiencing this issue? I have not noticed this on my end - have you done anything to modify your speed?

**Comment by Mr-Deadbeat** [comment]
yeah i've had this issue since the day i reported it i have updated the code when there has been updates but the issue has remained i do not have any custom changes made to the code or anything only run with 4 mods ahbot, ip tracker, playerbots, and weekend xp

**Comment by Mr-Deadbeat** [comment]
@Dreathean have you made any changes to your playerbots.conf file ?? i tried disabling all addons and they still fall behind no matter what changes i make i even tried changing these 2 settings just to see if it made any difference but none thus far
´´´# Set randombots movement speed to walking anywhere
AiPlayerbot.RandombotsWalkingRPG = 1

# Set randombots movement speed to walking only inside buildings
AiPlayerbot.RandombotsWalkingRPG.InDoors = 1´´´

so after testing these changes i'm still no closer to the reason why the damn bots fall behind it's like they wait for me to reach an endpoint and then start following ? it's driving me insane

**Comment by Mr-Deadbeat** [comment]
as a test i extracted new data from chromiecraft client i have used my original dvds up to this point enGB version
thought that maybe it's the client versions differing and causing the problem but nope still the same behaviour
with chromiecraft client so at the moment i'm stumped to what might be causing it also i only have 200 bots active and i have no latency issues while playing so thats not causing the problem either on trickers npcbots i had over 300 bots active so i don't think that is causing the issue maybe an addon ?? thats the only thing i have not tested for yet

i use Altoholic, Atlas. Atlasloot enhanced, Carbonite, ct_core, Details, Feral by night, fizzwidget disenchant predictor, gearscore lite, healbot, moveanything, Tellmewhen, Titan Panel, Unbot, Yssbossloot, Zonelevelinfo, Deadly boss mods and thats about it oh have ct_barmod, ct_bottombar and ct_buffmod disabled the rest are in use while i play

**Comment by Dreathean** [comment]
Out of those I use Atlasloot, Unbot, and DBM. I would recommend trying to turn all of the rest off and see if the issue persists, and if it's gone then might unfortunately have to add them back one by one to see which one is causing the issue. 

I do not have any idea what that channel is for, haha.

**Comment by Mr-Deadbeat** [comment]
well i tested the addons as well i disabled all of them and it made no difference they are still falling behind if you have not noticed it test it on your server when you are on a flying mount it's most noticeable when using a flying mount starting to wonder if some of the warnings you get during compilation have other adverse side effects like the issue i have encountered
noticed there are some comparisons between integers for one that could possibly cause spill over and unpredictable behaviour

**Comment by davvvve1** [comment]
Is there anyway we can make bots faster ?  I  notice this too .  I have chache speedrate in worldserver.conf to 1.4
