### ISSUE TITLE
When playing multiplayer games, there are some bugs that lead to crashes, and the crash logs do not record code navigation information

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#197]
When approximately 150 human players and 260 AI players are simultaneously online, crashes occur intermittently, particularly when a significant number of players are queuing for 5-player random dungeons with AI teammates. The crashes typically happen at intervals of around 2-4 hours. Sometimes, after the worldserver.exe restarts, it crashes again within 10 minutes. Here are some excerpts from the crash logs：

Physical Memory: 33544996 KB (Available: 24640064 KB)
Commit Charge Limit: 38787876 KB

*** Operation System ***
Windows Server 2016 Standard (Version 10.0, Build 17763)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF7102FAD62 01:00000000003D9D62 D:\Server\worldserver.exe

Registers:
RAX:0000024BEF295F00
RBX:0000024BEF295F00
RCX:00000000000003E8
RDX:000000000000020B
RSI:0000000000000001
RDI:0000024BD3DB8180
R8: 0000000000000000
R9: 00000000546C6148
R10:FFFFFFFFC309F73D
R11:0000000000000000
R12:0000024B4D654550
R13:000000FCD92FECF0
R14:0000024B4D654550
R15:000000FCD92FE230
CS:RIP:0033:00007FF7102FAD62
SS:RSP:002B:00000000D92FE7F0  RBP:D92FE8F0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
00007FF7102FAD62  000000FCD92FEA30  0001:00000000003D9D62 D:\Server\worldserver.exe
00007FF7102FB819  000000FCD92FEA70  0001:00000000003DA819 D:\Server\worldserver.exe

**Comment by zbhcn** [comment]
and this:
//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF710D457D0 01:0000000000E247D0 D:\Server\worldserver.exe

Registers:
RAX:000002133B47E540
RBX:00000213578485D0
RCX:0000000000000000
RDX:00007FF711893468
RSI:0000000000000000
RDI:00000213BC800410
R8: 0000000000008000
R9: 00007FF70FF20000
R10:000000EB982FECA0
R11:000000000000110B
R12:00007FF711858740
R13:00000213C39A6280
R14:000000EB982FEE50
R15:000000EB982FE6F0
CS:RIP:0033:00007FF710D457D0
SS:RSP:002B:00000000982FECA8  RBP:982FEDB0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Call stack:
Address   Frame     Function      SourceFile
00007FF710D457D0  000000EB982FECA0  0001:0000000000E247D0 D:\Server\worldserver.exe
00007FF7103A49A0  000000EB982FEE10  0001:00000000004839A0 D:\Server\worldserver.exe

**Comment by liyunfan1223** [comment]
Logs are missing information.
