### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#2]
Hello!!

![image](https://github.com/liyunfan1223/mod-playerbots/assets/58153179/c4824202-a84c-4275-a2d9-2c6e7004b4ae)

**Comment by liyunfan1223** [comment]
Fixed https://github.com/liyunfan1223/mod-playerbots/commit/b11fad1a467e6e0cf85e959d2b3e2d4fc13e829e and https://github.com/liyunfan1223/azerothcore-wotlk/commit/23306a3d10f39ad0e73ebdbe282fc8109b661806.

Thanks for your contribution :).
