### ISSUE TITLE
Death Knights stuck in starting zone, also fighting each other 

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#20]
Death knights seem to have difficulty (or impossible?) to make it out of their starting zone. Is it possible to have them simply skip this entire stage and teleport out of this zone?

The two factions do also fight each other when I think they aren't technically supposed to be until they "complete" this zone

![WoWScrnShot_080523_083701](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/fb658555-7cc2-4ea5-906c-0207ed7afadd)

**Comment by Dreathean** [comment]
Oh I absolutely agree, Liyun is doing a phenomenal job and I greatly appreciate all of their effort! Just trying to do my part to bring any issues I find to light! If I knew how to code this to help I would haha

**Comment by liyunfan1223** [comment]
Try typing following commands in console:
```
.playerbot rndbot init
.playerbot rndbot teleport
```

Dk bot will learn spell [Death Gate](http://db.nfuwow.com/80/?spell=50977) during initialization, which make them be able to leave the starting zone. Then they'll teleport to elsewhere by `teleport` command.

It is expected that the server will automatically execute these commands periodically. I'm not sure if there are some problems with this periodic execution.
