### ISSUE TITLE
Priest stops casting heals if wand is equiped

### ISSUE THREAD

**Issue by PrymetymeGaming** [liyunfan1223/mod-playerbots#200]
**Describe the bug**
If a wand is equipped on my priest they will use it 95% of time instead of healing. My group has died many times due to the priest just wanding.

**Commit hash**
The hash of the current commit.

**To Reproduce**
1. Equip wand on priest
2. Do a dungeon
3. 95% of the time they will wand instead of heal

**Expected behavior**
Heal when party is low hp

Maybe this was just my priest but for now I don't let them equip a wand. I will test further today.

**Comment by Dreathean** [comment]
Interesting, just to confirm - priest heals majority of the time if no wand is equipped? I assume holy/disc spec with the +heal command explicitly requested? Will test on my end

**Comment by Mr-Deadbeat** [comment]
yeah i think @Dreathean has a point if you don't tell the healer that he has healing duties i think he skips that and goes dps so need to add co +heal, +cure to the line and he will do what he is supposed to my priest has had a wand the whole time and when he doesn't need to keep the tank up he uses the wand so working as intended over here

**Comment by PrymetymeGaming** [comment]
The priest is holy and I had no idea I needed to tell the healer that. I just started using this a few days ago figuring things out. I have been piecing the commands together through google searches.

**Comment by liyunfan1223** [comment]
Fixed https://github.com/liyunfan1223/mod-playerbots/pull/219/commits/26faac914ebc7ec2e7deeba20e3b546d92d1f215.

Healing Priest may incorrectly stop casting healing spells due to threats. Now, they will keep casting healing spells no matter how the threat is.
