### ISSUE TITLE
What is the robot doing?

### ISSUE THREAD

**Issue by zhangbo8418** [liyunfan1223/mod-playerbots#201]
**Describe the bug**
The robot behaves strangely while riding. If you command the robot to attack from a distance, the robot will get stuck. Please watch the video for details.

**Commit hash**
The hash of the current commit.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

https://github.com/liyunfan1223/mod-playerbots/assets/46797568/5c765df2-ccb5-4d86-9742-3d176941292b

**Comment by zhangbo8418** [comment]
H264

https://github.com/liyunfan1223/mod-playerbots/assets/46797568/55c2a864-f62c-4a7d-96ee-f19220fee9c7

**Comment by zhangbo8418** [comment]
There are still problems. . .
https://github.com/liyunfan1223/mod-playerbots/assets/46797568/1a2c67c6-454c-4bc6-9373-4e9398e213fc

**Comment by zhangbo8418** [comment]
Many commands in the new version are invalid, and the command to reset the robot is also invalid.

**Comment by Dreathean** [comment]
@zhangbo8418 Can you confirm is reset BotAI is still not working for you? It seems to work for me now whereas it did not before. Are you still experiencing the riding/attacking issues?

**Comment by zhangbo8418** [comment]
> @zhangbo8418 Can you confirm is reset BotAI is still not working for you? It seems to work for me now whereas it did not before. Are you still experiencing the riding/attacking issues?

https://github.com/liyunfan1223/mod-playerbots/assets/46797568/1a2c67c6-454c-4bc6-9373-4e9398e213fc

**Comment by Dreathean** [comment]
Try the standard "attack" command, I know Liyunfan recently fixed that which should cover most use-cases.

**Comment by zhangbo8418** [comment]
> Try the standard "attack" command, I know Liyunfan recently fixed that which should cover most use-cases. Also that is the same video you posted from April?


Do you have any misunderstanding? The long-range attacks in the team are invalid.

**Comment by Dreathean** [comment]
I understand that the ranged attack command is currently not functional. I'm saying that the normal "attack" command will work for every bot regardless of melee/ranged though.

**Comment by Dreathean** [comment]
Closing as the "attack" command works for both melee and ranged.
