### ISSUE TITLE
Server log getting spammed by failed spell cast ?

### ISSUE THREAD

**Issue by Mr-Deadbeat** [liyunfan1223/mod-playerbots#204]
**Describe the bug**

server log is getting filled up with this over and over again

Player::CastItemCombatSpell(GUID Full: 0x000000000000074a Type: Player Low: 1866, name: Launus, enchant: 1866): unknown spell 19270 is casted, ignoring...

**Commit hash**
Core: 10bd872f2d1013393946840a0179e2e08ba6740e
Bots:  295214c30cba73636dc2cfdefe4c7075c5a6e6cf

**To Reproduce**

compile above versions of core and bots
and keep an eye on your server log

**Expected behavior**
no spam in log :)

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu Server 22.04.4 
 
**Additional context**

did not notice that spam earlier so must be something recent typo somewhere ?

**Comment by hiimawalrus** [comment]
Same, I did a fresh build a few times. Can't seem to figure it out
