### ISSUE TITLE
Unable to automatically apply mod's database

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#209]
**Describe the bug**
I used the original repository to compile and run without any issues. However, when using the playerbot's provided wlk branch with the additional mods, there are problems, and the mod database cannot be applied. The compilation is complete, but there are issues when running

authserver
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/ce41d3ab-ad6c-4849-8afb-a885dad148a5)
worldserver
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/6faf4709-1197-4a51-befc-d93d66654640)

I found that the databases provided by the mod don't seem to auto-load. Why is this happening? Initially, when I ran the program using the original repository, there were no errors. It’s too troublesome to import them one by one

**Commit hash**
last commit
[c010742](https://github.com/liyunfan1223/azerothcore-wotlk/commit/c010742289f38a2e842684003f7f8073237aef02)
[85bab82](https://github.com/liyunfan1223/mod-playerbots/commit/85bab825a17afb20f87f244f8270d9c97b642b9b)
**To Reproduce**

**Expected behavior**

**Screenshots**
MOD LIST
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/c67070de-4d68-4d1a-a700-20199b07ee7d)

**Desktop (please complete the following information):**
 - OS: ubuntu22.04.4 x64

**Additional context**

**Comment by xengine-qyt** [comment]
我自己看了下 playerbot 的数据库除了自己的库playerbots 其他两个库的数据也没应用成功
我使用的其他数据库用户名密码,不是默认的,不会是这个原因吧?

**Comment by xengine-qyt** [comment]
> Having this same issue. I can not even find this particular sql in the files

I can tell you a solution. Compile and run using the official repositories and all MODs of AZ once, then you can import the database correctly. Before that, do not include the PLAYERBOT MOD. Then compile and run PLAYERBOT branch and all MODs (including PLAYERBOT's MOD) together.

**Comment by cutdachez** [comment]
That is exactly what I did. Will try again though. Server runs. It just consistently gives that error.

**Comment by xengine-qyt** [comment]
> I found the issue. And fixed it, For me anyway

fixed? how? pr please?

**Comment by cutdachez** [comment]
Well for me. It wasn't actually a playerbot issue. It was transmog_mod that did not update sql files. I ran the transmog sql manually and it worked fine after that.
