### ISSUE TITLE
Battlegrounds not currently working

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#21]
Bots stay at starting position and do not move for the entire duration of the battleground 

Tested on WSG

As always, thank you for all you do!
![WoWScrnShot_080523_192847](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/a36b7ce4-aab7-49fe-bc25-3724710de201)

**Comment by Dreathean** [comment]
I honestly didn't think it was going to trigger at all, it took about 1-2 full minutes before to my surprise it popped up and it populated. But they wouldn't move after joining unfortunately

**Comment by liyunfan1223** [comment]
Currently the battleground functionality is only ported and not checked, so I can't make any guarantees at the moment :(. But it will be improved as development progresses.

**Comment by rogerc66** [comment]
Would be super fun if it work like live player in bg

**Comment by Dreathean** [comment]
> Currently the battleground functionality is only ported and not checked, so I can't make any guarantees at the moment :(. But it will be improved as development progresses.

Ah gotcha, that makes sense! Thank you for all of your effort on this project as always.

**Comment by rogerc66** [comment]
https://youtu.be/MmN1gZ4xurI

I got mine works a little

**Comment by Dreathean** [comment]
Nice! Did you get it working on WSG too or just AB at the moment? Should put in a pull request for your changes!

**Comment by zbhcn** [comment]
I am looking forward to repairing the issue of the battlefield robot not moving

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/29b748803ec0d040fcd6d1dcef7f31d89e367f3f Battlegrounds is available now, but is lacking testing and may have various problems. You are welcome to try it and give more feedback!

**Comment by rogerc66** [comment]
> [29b7488](https://github.com/liyunfan1223/mod-playerbots/commit/29b748803ec0d040fcd6d1dcef7f31d89e367f3f) Battlegrounds is available now, but is lacking testing and may have various problems. You are welcome to try it and give more feedback!

Awesome, finally it works, but the moment need to be improved, bots either flying or submerged underground sometimes

**Comment by Dreathean** [comment]
Very exciting! Can't wait to try it out, thank you!
