### ISSUE TITLE
Out-of-Bounds Teleport Points

### ISSUE THREAD

**Issue by Revisits** [liyunfan1223/mod-playerbots#214]
**Describe the bug**
Certain Playerbots are found roaming under playable areas (e.g. Orgrimmar).

**Commit hash**
85bab82

**To Reproduce**
1. Use chat command _/who_ in Orgrimmar
2. Use GM Command _.appear_ to one of the bots
3. Most of them are found RPG'ing under the Orgrimmar Map, hence erroneous

**Expected behavior**
Playerbots shouldn't be found in unreachable parts of the game world.

**Screenshots**
**Orgrimmar**
![UnderMap1](https://github.com/liyunfan1223/mod-playerbots/assets/167161581/d87ecfa3-ae65-498a-ba69-43437011f53c)
![UnderMap2](https://github.com/liyunfan1223/mod-playerbots/assets/167161581/900f8698-5396-4711-80b4-f3b3e39b53a6)
**Random Teleporting**
![RandomTP1](https://github.com/liyunfan1223/mod-playerbots/assets/167161581/00802687-c699-48cc-90b4-0329459ab19c)
_Z-coordinate (-2.7) is way below Orgrimmar, I've tested using .go xyz_

**System Information**
 - OS: Windows 11
 - ACore Fork: 10bd872f2

**Additional context**
Bots are intentionally being teleported into the invalid spots during 'Random Teleporting'.

**Comment by liyunfan1223** [comment]
Fixed. https://github.com/liyunfan1223/mod-playerbots/pull/281/commits/036638e110b3081fa2d16f3e226f259e8c9e1202
