### ISSUE TITLE
Crash on restart/shutdown

### ISSUE THREAD

**Issue by noisiver** [liyunfan1223/mod-playerbots#217]
**Describe the bug**
The server crashes when shutting down. I'm including the log from GDB below.

**Commit hash**
[0a1570e](https://github.com/liyunfan1223/azerothcore-wotlk/commit/0a1570ec52a6380e4114c3f78354ff95125574f1)
85bab825a17afb20f87f244f8270d9c97b642b9b

**To Reproduce**
1. Use `.server shutdown` or `.server restart`

**Expected behavior**
It shouldn't crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Not applicable

**Additional context**
Log from GDB: [gdb.txt](https://github.com/liyunfan1223/mod-playerbots/files/15200477/gdb.txt)

**Comment by liyunfan1223** [comment]
Comfirmed. I found that when I disabled the playerbot mod (set AiPlayerbot.Enabled to 0) the crash still persisted, this might be a core related issue.

**Comment by noisiver** [comment]
It could be. I haven't tried it without the module, just your changes to the core. The issue isn't there when using a copy of AC that doesn't include your fork though so it has to be something you've changed that causes it.

**Comment by liyunfan1223** [comment]
Yeah that makes sense, thank you for testing.

**Comment by liyunfan1223** [comment]
Resolved by reverting this commit https://github.com/azerothcore/azerothcore-wotlk/pull/18719. But still looking for the reason.

**Comment by azcguy** [comment]
Also crashes the client, after which all client settings are lost and logging in without restarting the whole auth/world is impossible

**Comment by liyunfan1223** [comment]
Fixed https://github.com/liyunfan1223/mod-playerbots/pull/221/commits/9dda8fa88fb6201d7c9901f43bbd54cc84dbc374.
