### ISSUE TITLE
[1146] Table 'acore_characters.custom_unlocked_appearances' doesn't exist

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#228]
[1146] Table 'acore_characters.custom_unlocked_appearances' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders

build complete and running worldserver is failed.
the server is first running.

**Comment by Dreathean** [comment]
Not sure why you think this is Playerbots related, appears to be a different custom module, a transmog one it seems.

**Comment by xengine-qyt** [comment]
> Not sure why you think this is Playerbots related, appears to be a different custom module, a transmog one it seems.

This does seem like an issue with the mod, but I followed the same compilation steps using the official repository, and the mod works fine with the official version. However, it doesn't work with the PLAYERBOT branch. The workaround is to compile and run the official repository once, and then compile and run this branch.

**Comment by Dreathean** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/eb04e71c-b5ac-466a-9c6d-97a00c21a584)

It's possible that there is another issue you're facing causing your worldserver to fail, but this table is custom for the Transmog module and needs to be run manually from what I can see.

**Comment by xengine-qyt** [comment]
> ![image](https://private-user-images.githubusercontent.com/132776330/332110522-eb04e71c-b5ac-466a-9c6d-97a00c21a584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzk2MDgsIm5iZiI6MTcxNjI3OTMwOCwicGF0aCI6Ii8xMzI3NzYzMzAvMzMyMTEwNTIyLWViMDRlNzFjLWI1YWMtNDY2YS05YzZkLTk3YTAwYzIxYTU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwODE1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGVkYWJkOWZmYTk0MjE1YzBlZjRjYTA5ZmEzMzcxNTVhZjhjZTNhNWViODY3ZmRhNDU2MDdhOWU0ZWI2NGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hEO33-VzmwRAgmfam-G2eYEUYh6rPsMl8gVyvP2jMQA)
> 
> It's possible that there is another issue you're facing causing your worldserver to fail, but this table is custom for the Transmog module and needs to be run manually from what I can see.

As I mentioned, all I need to do is to run the official worldserver once, and it will automatically import the MOD's database. However, there's an issue with PLAYERBOT's server. So, I'll start by running the official worldserver to automatically import all databases, and then I can proceed to run the PLAYERBOT's server
