### ISSUE TITLE
[BUG] Shadow Priest Talent Spec not complete

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#229]
**Describe the bug**
When a randombot or playerbot chooses Shadow spec for Priest, either on its own or when told "talents spec shadow pve", it will only select 12 talents in that tree, leaving 47 available.

**Commit hash**
The hash of the current commit.
[f475b94](https://github.com/liyunfan1223/mod-playerbots/commit/f475b94ae08226e409dd8e87fd38efa33569947d)

**To Reproduce**
1. Tell Priest "talents spec shadow pve"
2. See that only 12 talents are chosen

**Screenshots**
![WoWScrnShot_051924_100103](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/0efdd67d-1537-447a-851e-68dc95e565ce)

**Comment by liyunfan1223** [comment]
This may be caused by the premade talent in the configuration not being updated. Check it
```
AiPlayerbot.PremadeSpecLink.5.2.60 = --325003041203010323150301351
AiPlayerbot.PremadeSpecLink.5.2.80 = 0503203--325023051223010323152301351
```

**Comment by Dreathean** [comment]
Ah you are definitely right! I forgot to copy this fix over from the .dist to my .conf, thanks!
