### ISSUE TITLE
many bot server delay

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#233]
**Describe the bug**
I created 4000 robots, and the server became very slow... Why is the server CPU only utilizing one? Is it incapable of multi-threading?

**Commit hash**
last version

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/1b58dade-e3fb-4a48-9cb5-ecb675094927)

**Desktop (please complete the following information):**
ubuntu 22.04.4

**Comment by Dreathean** [comment]
Pretty sure that is simply a core Azerothcore/WoW thing, I don't believe that is something fixable on the Playerbot end.

**Comment by liyunfan1223** [comment]
Increase `MapUpdate.Threads` in worldserver.conf.

**Comment by xengine-qyt** [comment]
> Increase `MapUpdate.Threads` in worldserver.conf.

It's still the same. There's a noticeable delay. Below is my WORLDSERVER configuration.
Network.Threads = 4
ThreadPool = 4
UseProcessors = 4
MapUpdate.Threads = 8

![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/1b2b5700-2062-4c76-96d0-a10c9fbbba9b)

and sometime is world server report error:
Possible hacking attempt: Player Alissende [GUID Full: 0x000000000000035d Type: Player Low: 861] tried to loot a gameobject [GUID Full: 0xf110000e8700022d Type: Gameobject Entry: 3719  Low: 557] which is on respawn time without being in GM mode!
SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (336, 33391, 255)
 [ERROR]: [1062] Duplicate entry '336-33391' for key 'character_spell.PRIMARY'
SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (406, 33391, 255)
 [ERROR]: [1062] Duplicate entry '406-33391' for key 'character_spell.PRIMARY'
SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (1296, 33391, 255)
 [ERROR]: [1062] Duplicate entry '1296-33391' for key 'character_spell.PRIMARY'

**Comment by xengine-qyt** [comment]
> Pretty sure that is simply a core Azerothcore/WoW thing, I don't believe that is something fixable on the Playerbot end.
> 
> EDIT: see below, guess I am wrong!

All actions of playerbot are controlled by the mod rather than azcore. I believe the high CPU usage is due to the NPC behavior calculations of playerbot

**Comment by xengine-qyt** [comment]
> Pretty sure that is simply a core Azerothcore/WoW thing, I don't believe that is something fixable on the Playerbot end.
> 
> EDIT: see below, guess I am wrong!

All actions of playerbot are controlled by the mod rather than azcore. I believe the high CPU usage is due to the NPC behavior calculations of playerbot

**Comment by brian8544** [comment]
If you want a higher amount of bots, this must be implemented akin to mangosbots https://github.com/liyunfan1223/mod-playerbots/discussions/191

**Comment by brian8544** [comment]
If you want a higher amount of bots, this implementation akin to mangosbots https://github.com/liyunfan1223/mod-playerbots/discussions/191 has to be implemented. However try changing `AiPlayerbot.BotActiveAlone` to a lower percentile, for now.

**Comment by xengine-qyt** [comment]
> If you want a higher amount of bots, this implementation akin to mangosbots #191 has to be implemented. However try changing `AiPlayerbot.BotActiveAlone` to a lower percentile, for now.

no,that's useless modify.i solved it.follow me to modify configure with worldserver

UseProcessors = 0
ThreadPool = 8

**Comment by dd667** [comment]
AzerothCore rev. c304ccee571b - same issue still persists, atleast for me. Whether it is 2000 or 10000 bots it slows down the server massively. The machine itself is utilizing less than 50% of memory and around 30% of CPU. However, time diffs are shocking:

Update time diff: 12849ms with 0 players online
Last 500 diffs summary:
|- Mean: 369ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4303ms, 6109ms, 12849ms

I have followed your advice of changing the threadpool and processors but that did not help at all unfortunately. It's either keep bots below 1000 or have a nostalgic 2005 gameplay lags. No point opening new issue i guess.

**Comment by xengine-qyt** [comment]
> AzerothCore rev. c304ccee571b - same issue still persists, atleast for me. Whether it is 2000 or 10000 bots it slows down the server massively. The machine itself is utilizing less than 50% of memory and around 30% of CPU. However, time diffs are shocking:
> 
> Update time diff: 12849ms with 0 players online Last 500 diffs summary: |- Mean: 369ms |- Median: 2ms |- Percentiles (95, 99, max): 4303ms, 6109ms, 12849ms
> 
> I have followed your advice of changing the threadpool and processors but that did not help at all unfortunately. It's either keep bots below 1000 or have a nostalgic 2005 gameplay lags. No point opening new issue i guess.

Use the release compilation option to solve this problem
