### ISSUE TITLE
Still crashing on restart/shutdown

### ISSUE THREAD

**Issue by noisiver** [liyunfan1223/mod-playerbots#235]
**Describe the bug**
I know the previous bug report was closed as it was fixed, but it's still happening.

**Commit hash**
6ebd054fe1af8fb9334b1c5777da35635848df06
[9bbe90d](https://github.com/liyunfan1223/azerothcore-wotlk/commit/9bbe90d388389d7875895b21ba030f16934c823c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
[gdb.txt](https://github.com/liyunfan1223/mod-playerbots/files/15444075/gdb.txt)

**Comment by liyunfan1223** [comment]
This crash no longer occurs on my server, could another mod be causing it?

**Comment by noisiver** [comment]
If you mean another module I use could be causing it then it can't be because the issue isn't there unless I'm using playerbots. I also don't see how it could be a conflict between playerbots and one of my modules (I basically only use my own modules). I'll try with only playerbots soon to see if the issue is still there. I'll update the source at the same time obviously.

**Comment by noisiver** [comment]
Okay, so updating the core and playerbots module (~1 hour ago) fixed it again. This is what happened last time, it was fixed for a while and then broke again. I'm closing this for now but should I have the same thing happen again and my testing with straight up your fork of AC and no module other than playerbots has the same issue I'll reopen it, but here's hoping it won't!

I appreciate you taking the time to respond to these reports.
