### ISSUE TITLE
Acore string entry 50000 not found in DB.

### ISSUE THREAD

**Issue by ole100** [liyunfan1223/mod-playerbots#240]
Hello everyone,
 I found a error report when server start after latest compilation, no idear for that.
![image](https://github.com/liyunfan1223/mod-playerbots/assets/82332261/72ff3ef6-8105-445b-98cd-62ec0163ff6c)

**Comment by christan-duplicate** [comment]
INSERT INTO `acore_world`.`acore_string` (`entry`, `content_default`, `locale_koKR`, `locale_frFR`, `locale_deDE`, `locale_zhCN`, `locale_zhTW`, `locale_esES`, `locale_esMX`, `locale_ruRU`) VALUES (50000, 'This server is running the |cff4CFF00Loot aoe|r module.', '', '', '', '这个服务器正在运行 |cff4CFF00拾取范围扩展|r 模块。', '', 'Este servidor está ejecutando el módulo |cff4CFF00Loot aoe|r.', 'Este servidor está ejecutando el módulo |cff4CFF00Loot aoe|r.', '');

**Comment by liyunfan1223** [comment]
It has something to do with other mods not importing sqls correctly.
