### ISSUE TITLE
Config Issues

### ISSUE THREAD

**Issue by leewheel** [liyunfan1223/mod-playerbots#241]
<img width="879" alt="image" src="https://github.com/liyunfan1223/mod-playerbots/assets/30166672/3406d098-6e6d-424d-8cb5-8e8edd68197e">
There is already AiPlayerbot.AutoGearQualityLimit = 3 in playerbots.conf, why is it still reporting an error? It requires adding it in Worldserver.conf, and I have tested it, it can only be =3, and the other numbers are all wrong.

**Comment by Shiradan** [comment]
Yes, I found the same line of error in the log, not sure whether it is  still necessary to add that config to worldserver conf?

**Comment by liyunfan1223** [comment]
Fixed. https://github.com/liyunfan1223/mod-playerbots/pull/242
