### ISSUE TITLE
Zone-Appropriate Levels

### ISSUE THREAD

**Issue by F-Lambda** [liyunfan1223/mod-playerbots#246]
It would be nice if there was a way to make sure bots spawned were appropriate levels to the current zone. For example, creating a fresh orc or troll character and loading into the Valley of Trials, there's currently a decent chance there's a bunch of level 80s running around. It would be good if there was a way to weight the levels so that instead there's bots around the level 1-20 range in starting zones, and so on.

**Comment by Dreathean** [comment]
Is this purely based on a fresh spawn of randombots? Bc afaik from what I've seen they do teleport to level-appropriate zones, but obviously that can take a bit from a fresh spawn based on their teleport timer.

**Comment by Dreathean** [comment]
@F-Lambda can you confirm if this issue persists after letting the server run for some time? I haven't experienced this issue. If not can you please close this issue?

**Comment by Dreathean** [comment]
Closing this as this issue does not seem to be present at this time.
