### ISSUE TITLE
The robot generated incorrectly, and some robots stopped functioning.

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#254]
**Describe the bug**
The robots stopped functioning, and I only saw them in the wild. They cast buff spells on themselves but then just get stuck there without moving. I don't know why.
Another issue is that I generated robots supposed to be between levels 5 and 70, but 3,000 level 1 robots were generated instead. Why is this happening?

**Commit hash**
12ea82a57

**To Reproduce**
```
# Random bot count
AiPlayerbot.MinRandomBots = 6000
AiPlayerbot.MaxRandomBots = 6000
AiPlayerbot.RandomBotMinLevel = 5
AiPlayerbot.RandomBotMaxLevel = 70

# Enable/Disable rotation of bots (randomly select a bot from the bots pool to go online and rotate them periodically)
# Need reset rndbot after changing the setting
# default: 0 (disable, the online bots are fixed)
AiPlayerbot.EnableRotation = 0

# Bots pool size for rotation (should be less than RandomBotAccountCount * 10)
AiPlayerbot.RotationPoolSize = 1000

# Accounts to create for random bots
AiPlayerbot.RandomBotAccountPrefix = "rndbot"
AiPlayerbot.RandomBotAccountCount = 10000
```

**Screenshots**
Screenshot of robot stopping activity
![1](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/87642822-81dc-45e6-b4be-883237842b6e)
![2](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/60ef8c16-9049-4699-a480-1107c8f52996)
![3](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/9dcc3fd1-417c-421a-908a-cde69ecedec3)

**Desktop (please complete the following information):**
ubuntu22.04.4

**Comment by christan-duplicate** [comment]
内存满了吗？
预留的机器人姓名池有没有12000条数据？

**Comment by xengine-qyt** [comment]
> 内存满了吗？ 预留的机器人姓名池有没有12000条数据？

没满,生成机器人只是插入数据库 不占用内存啊. 16G内存 8核
超过12000? 什么意思?

**Comment by Dreathean** [comment]
Is your computer not lagging insanely hard at those numbers? Those are super high, most people don't go over 1000 or 2000 unless they have a super nice setup that I'm aware of.

Also when you're first setting the level ranges, the bots first level in at level 1 and then periodically get updated into the defined range just fyi.

**Comment by xengine-qyt** [comment]
> Is your computer not lagging insanely hard at those numbers? Those are super high, most people don't go over 1000 or 2000 unless they have a super nice setup that I'm aware of.
> 
> Also when you're first setting the level ranges, the bots first level in at level 1 and then periodically get updated into the defined range just fyi.

There will be lag, but the server's CPU and memory are normal; it just lags. It should be an issue with the internal logic processing

**Comment by Dreathean** [comment]
I would recommend seeing if you're experiencing these issues if you have say 1000 playerbots. And change the accounts to 150 or so, 10000 is overkill even for 6000 bots. Even if it shouldn't cause lag, maybe it is causing issues with something.

**Comment by xengine-qyt** [comment]
> I would recommend seeing if you're experiencing these issues if you have say 1000 playerbots. And change the accounts to 150 or so, 10000 is overkill even for 6000 bots. Even if it shouldn't cause lag, maybe it is causing issues with something.

I haven't tried it, but I believe the creation and setup of the bots are done according to the basic code, so there shouldn't be any problems. However, there are indeed some inexplicable issues during gameplay.
