### ISSUE TITLE
Since Yday i'm getting this error due to playerbots moduler

### ISSUE THREAD

**Issue by Foxyybg** [liyunfan1223/mod-playerbots#257]
[1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND c.id1 != 32820 AND c.spawntimesecs < 1000 AND t.faction != 188 GROUP BY...' at line 1
Error while parsing SQL. Core fix required.

I just made a recompile of the files i didn't changed anything and i got this error before that i was running for 3-4 days without problem currently i'm using mariadb 10.5.23 version , i'm not sure if it have been updated

**Desktop (please complete the following information):**
 - OS: Debian 11

**Comment by Dreathean** [comment]
@Foxyybg Are you still experiencing this issue with latest commit? Haven't seen anyone else report this error

**Comment by Jgoodwin64** [comment]
Can we close it? It's been a month with no other reports.

**Comment by Dreathean** [comment]
Agreed. Closing due to no update and no other reports from other users.
