### ISSUE TITLE
Shaman not using totems

### ISSUE THREAD

**Issue by Silius01** [liyunfan1223/mod-playerbots#261]
Describe the bug
Shaman bot does not seem to be using totems

Commit hash
Latest commit

To Reproduce
Create a shaman bot
Get it high enough to get the first totem
Play with Bot

Expected behavior
Shaman to use totems

Screenshots

Desktop (please complete the following information):

OS: Windows 11
Browser Chrome
Version 125.0.6422.141
Additional context
Tried both caster and dps strategies. Have levelled a bot up to level 12 have not seen it summon a totem at all but other abilities are being used. Note this is a character on my account that I am running as a Bot.

**Comment by liyunfan1223** [comment]
When fighting normal mobs, the bot consider earth totem unnecessary. You can retest it in the dungeon boss fight. The judgment is whether the health of target exceeds a threshold.

**Comment by Silius01** [comment]
Ok, that makes sense. I figured it might be something like that when I saw that the fire totem was working. Sorry for the false alarm. Thanks for the info.
