### ISSUE TITLE
[Request] Remove alt-Playerbot Control/Change Master Command

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#263]
If possible, it would be nice to have a command to relinquish control of a playerbot. In my case, I setup a raid team of alt-playerbots via a GM account for when we reach level 60 (using randombots for dungeons leveling up) and set them up with the gear we want, but realized that the .playerbot bot remove command only makes them go offline, and does not relinquish control so you can't control them on any other character.

If need be I suppose I can make my playthrough account GM to redo all of it in creating the team but the flexibility would be beneficial especially as we need to split control of various bots as well.

**Comment by zhangbo8418** [comment]
It seems that when a player goes offline, his team will not automatically disband. As a result, the robots in his team cannot be invited by other players. I don't know what to do. . .

**Comment by Dreathean** [comment]
Not only that but you can disband and use "playerbot bot remove" and it'll log off that alt bot, but he still can not be recruited by other characters

**Comment by Dreathean** [comment]
Oddly enough, it seems to be working now, not sure why or what changed but closing this.
