### ISSUE TITLE
阿拉希盆地联盟夺取兽栏后全部堆在旗子下无任何动作，部落夺取三个据点后也不会继续进攻了。

### ISSUE THREAD

**Issue by little600** [liyunfan1223/mod-playerbots#264]
![WechatIMG26](https://github.com/liyunfan1223/mod-playerbots/assets/45162542/3a5d8d1a-633d-44e4-a569-ea83ee71726b)

**Comment by xengine-qyt** [comment]
一样的问题...全部都愣住了

**Comment by christan-duplicate** [comment]
请问，有解决吗，估计没有策略？

**Comment by xengine-qyt** [comment]
是的很奇怪.可能不完善.
但是机器人能够正常PK.比如我LM去BL的地方 虽然他们在那里乱逛 但是我过去他们一样会揍我

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/298
