### ISSUE TITLE
Alterac

### ISSUE THREAD

**Issue by Nansydrew** [liyunfan1223/mod-playerbots#266]
On the battlefield alterac valley NPC bots just gather in a bunch near the cemetery capture flag and try to capture it

**Comment by Dreathean** [comment]
This is noted in https://github.com/liyunfan1223/mod-playerbots/issues/69

**Comment by Dreathean** [comment]
Closing as duplicate of https://github.com/liyunfan1223/mod-playerbots/issues/69
