### ISSUE TITLE
No unistd.h 

### ISSUE THREAD

**Issue by Tersoth** [liyunfan1223/mod-playerbots#27]
I am sorry if this is the incorrect place for this but I am loosing my mind lol. 

I am not sure what I am doing wrong but when I trying and use this mod I get this error in Visual Studios "C1083 Cannot open included file: 'unistd.h'.  It says its in the RandomPlayerbotFactory.cpp line#14.  I can find all the other files in RandomPlayerbotFactory.cpp it says to include but can not find the unistd.h anywhere.

I am 99% sure I pulled the correct core (git clone https://github.com/liyunfan1223/azerothcore-wotlk.git  --branch Playerbot --single-branch) and have the correct Mod (I have pulled it from git and also downloaded it from Azerothcore mods page and both did the same thing)

I have done just a separate Azerothcore server and got everything working fine. Really not sure what I am doing with this mod. 

![unistd](https://github.com/liyunfan1223/mod-playerbots/assets/143005434/926771af-dbc9-4963-99dc-6cb0a3e80864)

**Comment by liyunfan1223** [comment]
Fixed. https://github.com/liyunfan1223/mod-playerbots/commit/0adf1b8034858a3fd87f81e985a76b3ee76fe8ec

I sometimes ignore compilation problems under the windows platform. Thanks for your report!

**Comment by Tersoth** [comment]
Repulled everything and recompiled and everything works great now. Thank you
