### ISSUE TITLE
Not a bug but a doubt

### ISSUE THREAD

**Issue by yuan227301** [liyunfan1223/mod-playerbots#270]
@liyunfan1223 
Could you Please read my message in here:
#245

**Comment by christan-duplicate** [comment]
我的也是这样，全新数据库也会

**Comment by liyunfan1223** [comment]
I can't find the message in the PR. Can you post it here?

**Comment by yuan227301** [comment]
Clicking on this link #245  will take you to my message. Strange, am I the only one who can see it?

**Comment by yuan227301** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/18180849/10c32ea0-5f32-407e-8572-5a84498ae5ae)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/18180849/48ee7fcf-023f-4e18-977b-4617cb5cfda7)

**Comment by Dreathean** [comment]
Yeah I couldn't see your message on there either, thanks for sending it here. That is interesting, wonder if something is off with the logic for rti4 vs rti7 because the attack command and skull work perfectly now with these changes lol

**Comment by liyunfan1223** [comment]
You're right, it's a mistake. Could you make a PR to fix it? Thanks! By the way, I really can't see these comments, maybe because they are in pending state?

**Comment by yuan227301** [comment]
> Yeah I couldn't see your message on there either, thanks for sending it here. That is interesting, wonder if something is off with the logic for rti4 vs rti7 because the attack command and skull work perfectly now with these changes lol

Before this submission (245), the attack command was only valid in non-combat state. After entering combat, only targets marked with rti7 would be prioritized by the bot (there was a bug here, some units were not recognized as valid units by the bot because they are not in the robot's attackers list, such as the Kor'kron Battle-Mage in Icecrown Citadel);

**Comment by yuan227301** [comment]
> You're right, it's a mistake. Could you make a PR to fix it? Thanks! By the way, I really can't see these comments, maybe because they are in pending state?

Yes,you are right, only I can see them because their status is pending(￣□￣;)!!；Now,It's not.
I'll try to optimize the logic here a bit and create a PR after testing.

**Comment by Dreathean** [comment]
@yuan227301 this seems to be completed with your PR (thanks by the way!), is this good to close?
