### ISSUE TITLE
Battleground (WSG) Eventually Crashes

### ISSUE THREAD

**Issue by WorstGit** [liyunfan1223/mod-playerbots#273]
Server seems stable when bots are left alone/when playing solo.
When entering a battleground like Warsong Gultch, eventually the worldserver will crash with "Segementation Fault" error code. 
Can't replicate it precisely, but it happens after ~5 minutes. 
Server is logging - "unknown spells" being cast at some stages of being online however it won't crash unless it's in a battleground and I'm not sure if this is even related.

Server is running a few other modules too:
Autobalance
Gain Honor on Guard Kill
Account Acheivements
Auctionhouse Bot 
Time is Time
Solo LFG
Transmog

[7ca3db8]
The hash of the current commit.

1. Start Server
2. Queue for WSG
3. Enter battleground and wait for eventual crash

**Expected behavior**
Not crash, and get some bot-pvp action

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
8gb Ram with 20gb Swap (increased to try to rule out any memory issues) 
Client ran on separate machine - server machine runs only the database, auth and worldservers.
worldserver and authserver both ran under sudo.

**Comment by Dreathean** [comment]
Are you able to post what the worldserver is saying when it crashes?

**Comment by serverwar** [comment]
[b2ecf61e689a+_worldserver.exe_[23-6_12-55-54].txt](https://github.com/user-attachments/files/15946340/b2ecf61e689a%2B_worldserver.exe_.23-6_12-55-54.txt)

**Comment by serverwar** [comment]
[b2ecf61e689a+_worldserver.exe_[20-6_14-44-40].txt](https://github.com/user-attachments/files/15946344/b2ecf61e689a%2B_worldserver.exe_.20-6_14-44-40.txt)

**Comment by aronkleinhans** [comment]
Same segfault crash after 5-7 min in WSG. 

I have these same modules
honor on guard kill
ahbot

I use a few others
Eluna
Better item reload
Random enchants

**Comment by Dreathean** [comment]
@WorstGit Can you test without using Gain Honor on Guard Kill and see if you still get a crash? Because that seems like the culprit here, and I do believe that has been reported before.

**Comment by aronkleinhans** [comment]
> @WorstGit Can you test without using Gain Honor on Guard Kill and see if you still get a crash? Because that seems like the culprit here, and I do believe that has been reported before.

Yeah I got rid of Honor on guard kill, that was the culprit for wsg crashes. 
Memory increase wise it was maps being loaded. if all maps are preloaded, increasing swap works and does not crash.

**Comment by Dreathean** [comment]
Great, going to close this out thanks
