### ISSUE TITLE
Bots spawning in race-appropriate areas

### ISSUE THREAD

**Issue by stevedwray** [liyunfan1223/mod-playerbots#276]
Is it possible to get the bots to start, or teleport to, their own race appropriate area?

So that its more like a normal player experience, eg dwarves and gnomes start over in Dun Morogh and fan out from there, etc.

I had thought this might have them spawn in at their race-appropriate area and then not teleport somewhere else on level up:
# Bots automatically teleport to another place for leveling on levelup
# Only for random bots
# Default: 1 (enabled)
AiPlayerbot.AutoTeleportForLevel = 0

but with this set to 0, I still have all the different races teleporting to all the different starting areas.

Thanks

**Comment by stevedwray** [comment]
Looks like code was changed about a year ago in
RandomPlayerbotMgr.cpp
around line 920, which seems to make the bots teleport. Thats the message I see in the console output when a bot teleports into some random starting area:
"teleport for level and refresh"

The commit for this doesn't have much info, and it doesn't seem to be tied to any issue. Am I looking in the right place?

```
    // enable random teleport logic if no auto traveling enabled
    // if (!sPlayerbotAIConfig->autoDoQuests)
    // {
    uint32 teleport = GetEventValue(bot, "teleport");
    if (!teleport)
    {
        LOG_INFO("playerbots", "Bot #{} <{}>: teleport for level and refresh", bot, player->GetName());
        Refresh(player);
        RandomTeleportForLevel(player);
        uint32 time = urand(sPlayerbotAIConfig->minRandomBotTeleportInterval, sPlayerbotAIConfig->maxRandomBotTel\
eportInterval);
        ScheduleTeleport(bot, time);
        return true;
    }
    // }
```

https://github.com/liyunfan1223/mod-playerbots/commit/0cd1fa4db3d75e59bda889e84f5db84f4e2ed276?diff=unified&w=0#diff-667de61737453110eee8c8da7243b2a58e99a2b0c127bde48dc0261ea6d67c33

I'm not really good with GitHub tho.

**Comment by stevedwray** [comment]
For now I've completely disabled random teleports since its really immersion breaking.
I just added a return at the top of the function
```
void RandomPlayerbotMgr::RandomTeleport(Player* bot, std::vector<WorldLocation>& locs, bool hearth)
```
would be lovely to have a config option to disable it tho. Maybe there already is one and I'm missing it?

**Comment by noisiver** [comment]
Like I said in the AC Discord server, the issue I see with this is accessing certain areas. Do the bots actually run all the way to STV for example? They probably don't go through the Dark Portal so getting to Outland is out of the question, and going to Northrend is also out of the question.

Adding a return at the top of the function is a hackfix. It's better to re-enable the check for autoDoQuests.

**Comment by stevedwray** [comment]
I absolutely agree that its a terrible hack, I just did it to see how they'd respond.
Theres nothing on the commit mess1ages that suggests why 
```
# Chance bot chooses RPG (Teleport to random camp for their level) instead of grinding
AiPlayerbot.RandomBotRpgChance = 0 #unused now
```

is 'unused now'.
I did try changing some of the code around this but, not being an actual programmer, I'm not sure. Would be ideal if a dev could comment on why this functionality was removed.

**Comment by liyunfan1223** [comment]
Teleport only takes into account level and team (alliance / horde), which is a simplification. I am considering adding race to the judgment. I think we only need to consider bots with levels <= 20.

**Comment by liyunfan1223** [comment]
> I absolutely agree that its a terrible hack, I just did it to see how they'd respond. Theres nothing on the commit mess1ages that suggests why
> 
> ```
> # Chance bot chooses RPG (Teleport to random camp for their level) instead of grinding
> AiPlayerbot.RandomBotRpgChance = 0 #unused now
> ```
> 
> is 'unused now'. I did try changing some of the code around this but, not being an actual programmer, I'm not sure. Would be ideal if a dev could comment on why this functionality was removed.

The rpg system is not working properly, so it is disabled to avoid more weird bugs and crashes. Unless someone improves it and verifies its functionality. I think it needs to be rebuilt.

**Comment by liyunfan1223** [comment]
Random teleporting is a temporary solution. Completely simulating the behavior of real players requires a complex state machine, which currently seems unfeasible unless someone is willing to spend a lot of efforts in this part. As we discussed in https://github.com/liyunfan1223/mod-playerbots/issues/12.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/279

A threshold is set on the distance between the initial point and the teleport point to solve this issue. Please pull the latest commit to verify if this solution works. (using command `.playerbot rndbot teleport`)

**Comment by stevedwray** [comment]
this does seem to be working! Thanks
