### ISSUE TITLE
[SOLVED] Immediate crash when logging in entire account (9 other characters).

### ISSUE THREAD

**Issue by LitchLight** [liyunfan1223/mod-playerbots#277]
**Describe the bug**
Server segfault when multiple playerbots log in.

**Commit hash**
AzerothCore rev. 9bbe90d38838+ 2024-05-04 23:35:53 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**To Reproduce**
1. Create 10 lvl 1 characters
2. Log one in and then the rest...
.playerbots bot add [ACCOUNTNAME]
Bots log in then server crashes with below GDB.

**Expected behavior**
Otherwise

**Screenshots**
![crash](https://github.com/liyunfan1223/mod-playerbots/assets/171148097/64515bc9-4001-4863-90cf-79ea97e482c2)

**Desktop (please complete the following information):**
FatDog64 901 (Linux) 6.1.46 2 SMP PREEMPT_DYNAMIC Thu Sep 14 22:07:07 AEST 2023 x86_64 AMD Phenom(tm) II X3 B75 Processor AuthenticAMD GNU/Linux
12GB Ram

cmake version 3.26.2
gcc (GCC) 12.2.0
clang version 15.0.7
ldd (GNU libc) 2.37
BOOST_VERSION
#define BOOST_LIB_VERSION "1_81"
go version go1.22.3 linux/amd64
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
mysqld Ver 10.6.14-MariaDB for Linux on x86_64 (Source distribution)

Modules:
mod-starter-guild
mod-eluna
mod-transmog
mod-guildhouse
mod-1v1-arena
mod-keep-out
mod-ah-bot
mod-playerbots

[gdb.txt](https://github.com/user-attachments/files/15926914/gdb.txt)

**Comment by LitchLight** [comment]
doh! Yes this is the core we are playing on currently. Need to update. Understood.

**Comment by LitchLight** [comment]
In terms of a fix:

/azerothcore-wotlk-playerbots/modules/mod-playerbots/src/PlayerbotAI.cpp

Around line 4190...
```

Item* PlayerbotAI::FindOilFor(Item* weapon) const
{
    Item* oil = nullptr;
    ItemTemplate const* pProto = weapon->GetTemplate();

    if (pProto)
    {
        if (pProto->SubClass == ITEM_SUBCLASS_WEAPON_SWORD || pProto->SubClass == ITEM_SUBCLASS_WEAPON_STAFF || pProto->SubClass == ITEM_SUBCLASS_WEAPON_DAGGER)
        {
            for (uint8 i = 0; i < std::size(uPriorizedWizardOilIds); ++i)
            {
                LOG_DEBUG("playerbots", "Checking wizard oil id: {}", uPriorizedWizardOilIds[i]);
                oil = FindConsumable(uPriorizedWizardOilIds[i]);
                if (oil) {
                    LOG_DEBUG("playerbots", "Found wizard oil for id: {}", uPriorizedWizardOilIds[i]);
                    return oil;
                }

                if (i < std::size(uPriorizedManaOilIds)) {
                    LOG_DEBUG("playerbots", "Checking mana oil id: {}", uPriorizedManaOilIds[i]);
                    oil = FindConsumable(uPriorizedManaOilIds[i]);
                    if (oil) {
                        LOG_DEBUG("playerbots", "Found mana oil for id: {}", uPriorizedManaOilIds[i]);
                        return oil;
                    }
                }
            }
        }
        else if (pProto->SubClass == ITEM_SUBCLASS_WEAPON_MACE || pProto->SubClass == ITEM_SUBCLASS_WEAPON_MACE2)
        {
            for (uint8 i = 0; i < std::size(uPriorizedManaOilIds); ++i)
            {
                LOG_DEBUG("playerbots", "Checking mana oil id: {}", uPriorizedManaOilIds[i]);
                oil = FindConsumable(uPriorizedManaOilIds[i]);
                if (oil) {
                    LOG_DEBUG("playerbots", "Found mana oil for id: {}", uPriorizedManaOilIds[i]);
                    return oil;
                }

                if (i < std::size(uPriorizedWizardOilIds)) {
                    LOG_DEBUG("playerbots", "Checking wizard oil id: {}", uPriorizedWizardOilIds[i]);
                    oil = FindConsumable(uPriorizedWizardOilIds[i]);
                    if (oil) {
                        LOG_DEBUG("playerbots", "Found wizard oil for id: {}", uPriorizedWizardOilIds[i]);
                        return oil;
                    }
                }
            }
        }
    }
    else
    {
        LOG_DEBUG("playerbots", "Weapon template is null");
    }

    LOG_DEBUG("playerbots", "No valid oil found");
    return nullptr; // Return nullptr if no valid oil is found
}

```

**Comment by Dreathean** [comment]
@LitchLight Was a PR used to fix this or was it due to old commit? Not seeing anyone else experience this issue

**Comment by LitchLight** [comment]
AzerothCore revision : 05c9a96ba99c 2024-07-11 12:32:13 +0800 (Playerbot branch)

Can confirm the issue remains in current release, and that the above patch (from one of our devs) stops the crashes.

**Comment by Dreathean** [comment]
as of https://github.com/liyunfan1223/mod-playerbots/pull/445 this issue should be resolved. If anyone encounters this still please make a new issue and post a crash log.
