### ISSUE TITLE
Playerbots error message

### ISSUE THREAD

**Issue by McCrowley** [liyunfan1223/mod-playerbots#280]
I use 

https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot 

https://github.com/liyunfan1223/mod-playerbots 

I always get the error message in worldserver.exe, maybe they can fix the error or change it so that it overwrites it. It would also be nice to know how to reset the player bots or set up the player bots config better. 

Sorry if I worded it wrong in Github, I just wanted to report the error.

**Comment by McCrowley** [comment]
I use

https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot

https://github.com/liyunfan1223/mod-playerbots

I always get the error message in worldserver.exe, maybe they can fix the error or change it so that it overwrites it. It would also be nice to know how to reset the player bots or set up the player bots config better.

Sorry if I worded it wrong in Github, I just wanted to report the error

![20240622_010634](https://github.com/liyunfan1223/mod-playerbots/assets/91791307/680d975e-490f-4c38-8722-ea87a6cdbffa)

**Comment by hermensbas** [comment]
discord support channel pls
