### ISSUE TITLE
'Midsummer Fire Festival' In Stormwind and Ironforge the bots trigger huge amount of NPC around the festival bonfires.

### ISSUE THREAD

**Issue by hermensbas** [liyunfan1223/mod-playerbots#283]
**Describe the bug**
When the midsummer fire festival is active the server shuts down after a while, a huge amount of NPC's are spawned in due the playerbots which grow overtime till the server crashes or makes it unplayable.

**Commit hash**
ddbfb4630b9a692ccd1f60f87e42ab97a94d821d (22 Jun)

**To Reproduce**
1. Enable midsummer fire festival
2. Let the server run for an hour
3. Go to IronForge or Stromwind bonfire festival fire
4. Notice the playerbots triggers a huge amount of NPC without ending.

**Expected behavior**
The bots stop spawning a NPC's

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu live server 20.04 (minimal)
 - Classic setup
 - Using around 3000 bots

**Additional context**
Support forum AzerothCore on discord: 'High latency after 1+ hour of server running'
Temp offered fix; disabling the midsummer fire festival event.

### to disable
use acore_world
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=1;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES (9, 1, 0, '', '', 'Midsummer Fire Festival');

### to enable 'midsummer fire festival' again only run:
use acore_world
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=1;

**Comment by davvvve1** [comment]
Thank you !

**Comment by liyunfan1223** [comment]
I've also noticed a noticeable lag over the past few days, but I'm not sure why. Thank you for your finding that can explain this. I've previously optimized it https://github.com/liyunfan1223/mod-playerbots/commit/3abce62bbaff73802ab28eee17cebcf10a599d43. You can try to see if this issue can be solved by pulling the latest update.

**Comment by hermensbas** [comment]
Credits belong to https://www.youtube.com/watch?v=EZZdnY5iKLI&t=42s, i am just a messager and making sure you as developer have part of it :)

**Comment by hermensbas** [comment]
Testing the bug on the latest builds, will report back in few hours.

- mod-playerbots (3abce62bbaff73802ab28eee17cebcf10a599d43) 
- [liyunfan1223/azerothcore-wotlk](https://github.com/liyunfan1223/azerothcore-wotlk) ( 80309c5f2392d21c55a638b1d8f43b1be6d1f974)

**Comment by hermensbas** [comment]
Can reproduce anymore, 50min running not a single NPC spawn.

![Schermafbeelding 2024-06-24 193704](https://github.com/liyunfan1223/mod-playerbots/assets/31279994/dffb8c05-78e7-48b3-b0d0-c7881257d964)

**Comment by hermensbas** [comment]
Verified after 2 hours of playing.

**Comment by noisiver** [comment]
> Can reproduce anymore, 50min running not a single NPC spawn.
> 
> ![Schermafbeelding 2024-06-24 193704](https://private-user-images.githubusercontent.com/31279994/342438394-dffb8c05-78e7-48b3-b0d0-c7881257d964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTY2MTMsIm5iZiI6MTcxOTI1NjMxMywicGF0aCI6Ii8zMTI3OTk5NC8zNDI0MzgzOTQtZGZmYjhjMDUtNzhlNy00OGIzLWIwZDAtYzc4ODEyNTdkOTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE5MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjAzYzQ4NTI1ZTBjZGI2NmIwNzVkYzZlYjEzMzI1ZThiODUyZDlmMjIyMTBkNzZkZDljY2VlNTM1MDRhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lfkX2U_KlANRQ11zZw44KbgslyFnlUnZ_FQfpt8-jMs)

I'm going to update and test as well, but it might not be helpful if you're seeing a difference.

OOT: What are you using to overhaul the textures?

**Comment by sudlud** [comment]
azerothcore/azerothcore-wotlk#19141

This is my attempt core-side to improve on the issue as unwanted midsummer npc / gameobjects should not be spawned / stay at all.

**Comment by hermensbas** [comment]
> Can't reproduce anymore, 50min running not a single NPC spawn.
> 
> ![Schermafbeelding 2024-06-24 193704](https://private-user-images.githubusercontent.com/31279994/342438394-dffb8c05-78e7-48b3-b0d0-c7881257d964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjI0NTgsIm5iZiI6MTcxOTI2MjE1OCwicGF0aCI6Ii8zMTI3OTk5NC8zNDI0MzgzOTQtZGZmYjhjMDUtNzhlNy00OGIzLWIwZDAtYzc4ODEyNTdkOTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIwNDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODMyYzJhMTdlZDM1NWU0Mzc5M2RmNWJmODIwYWYyZDE5MGQxNDk1YmI2ZjJmOTI3OGU0ZDBkODY1ZjkwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fmkiHwofqDvPXgoV6nty97XDcUKNZXM6w5KxjFeOq-4)

The liyunfan1223/azerothcore-wotlk has been rebased today, and your PR has been merged 12 hours, so the actual fix might be your change. Eitherway i havent detected any NPC respawns anymore. Havent actual checked whether your commit has been rebased into the fork though.

**Comment by noisiver** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/b7bd1360-9fd4-41da-966d-e6225de6fdc7)
Just over 3 hours and no issues. Only the original NPC is spawned. It would be less than 10 minutes before at least 2 would appear previously. I have to say that this seems to have been fixed.

**Comment by Dreathean** [comment]
Excellent, thanks for the help with this sudlud!
