### ISSUE TITLE
Compile fails on Arch Linux

### ISSUE THREAD

**Issue by Caffarius** [liyunfan1223/mod-playerbots#284]
**Describe the bug**
Recent versions are failing to compile under a freshly updated Arch Linux machine. Issue was noted as starting around a month ago but I haven't had much time to debug lately; may coincide with OS updates. The compile error is reported in the file `mod-playerbots/src/Helpers.cpp`.

Relevant compiler error message:
```
[ 14%] Building CXX object modules/CMakeFiles/modules.dir/mod-playerbots/src/LootObjectStack.cpp.o
/home/acore/.build/azerothcore/modules/mod-playerbots/src/Helpers.cpp:45:13: fatal error: no member named 'find_if' in namespace 'std'; did you mean 'std::ranges::find_if'?
   45 |     s.erase(std::find_if(s.rbegin(), s.rend(), [](int c) {return !std::isspace(c); }).base(), s.end());
      |             ^~~~~~~~~~~~
      |             std::ranges::find_if
```

**Commit hash**
azerothcore-wotlk Playerbot branch: **[fb4dbdd](https://github.com/liyunfan1223/azerothcore-wotlk/commit/fb4dbdd6049167687ad5e31d29ecafec65ae31d3)**
mod-playerbots master branch: **[7513b52](https://github.com/liyunfan1223/mod-playerbots/commit/7513b528b1087929cebeeef200de78d07f41e70a)**

**To Reproduce**
Prepare an Arch Linux x86_64 machine with the packages necessary for AzerothCore compilation and attempt to compile as documented.

Bash commands to reproduce:
```
umask 0007
install_path="${HOME}/azeroth-server"
build_path="${HOME}/.build"
mkdir -p "${build_path}"
if [ -d "${build_path}/azerothcore" ]; then
    rm -rf "${build_path}/azerothcore"
fi
cd "${build_path}"
git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch Playerbot --single-branch azerothcore --depth 1
cd "${build_path}/azerothcore/modules"
git clone https://github.com/liyunfan1223/mod-playerbots.git --branch master --single-branch mod-playerbots --depth 1
mkdir "${build_path}/azerothcore/build"
cd "${build_path}/azerothcore/build"
cmake ../ -DCMAKE_INSTALL_PREFIX="${install_path}" -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j "$(expr "$(nproc)" + 1)"
```

The error message gives a clue, so inside `mod-playerbots/src/Helpers.cpp` I change the following two functions from...
```
std::string& ltrim(std::string& s)
{
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](int c) {return !std::isspace(c); }));
    return s;
}

std::string& rtrim(std::string& s)
{
    s.erase(std::find_if(s.rbegin(), s.rend(), [](int c) {return !std::isspace(c); }).base(), s.end());
    return s;
}
```
...to...
```
std::string& ltrim(std::string& s)
{
    s.erase(s.begin(), std::ranges::find_if(s.begin(), s.end(), [](int c) {return !std::isspace(c); }));
    return s;
}

std::string& rtrim(std::string& s)
{
    s.erase(std::ranges::find_if(s.rbegin(), s.rend(), [](int c) {return !std::isspace(c); }).base(), s.end());
    return s;
}
```
Then I reissue the compile steps:
```
cd "${build_path}/azerothcore"
rm -rf "${build_path}/azerothcore/build"
mkdir "${build_path}/azerothcore/build"
cd "${build_path}/azerothcore/build"
cmake ../ -DCMAKE_INSTALL_PREFIX="${install_path}" -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j "$(expr "$(nproc)" + 1)"
if [ -d "${install_path}" ]; then
    mv "${install_path}" "${install_path}.bak"
fi
mkdir -p "${install_path}/log"
make install
sync
```
...and everything completes successfully. The authserver and worldserver seem to run as expected once the code is compiled with the `Helpers.cpp` file modified. I have tested it for a few hours and the server/bots work as well as they did in previously tested versions.

**Expected behavior**
Code compiles without need for modification.

**Desktop**
 - Arch Linux (updated as of 24/06/2024)
 - Linux 6.9.6.zen1-1
 - MariaDB 11.4.2-1
 - Boost 1.83.0-8
 - OpenSSL 3.3.1-1
 - CMake 3.29.6-1
 - Clang 17.0.6-2
 
**Additional context**
 I'm not sure if it's a change in the codebase within the last ~month or if this is an error related to Arch's move to Clang 17. Just wanted to post this in case anyone else is running into the same error.

**Comment by noisiver** [comment]
You could try adding `#include <algorithm>` to Helpers.cpp or Helpers.h

**Comment by Caffarius** [comment]
Sorry for my C++ ignorance, most of my work has been in Java/C# and bash so I only know enough to get in trouble here syntactically. I dug into it a bit more [and you are correct.](https://en.cppreference.com/w/cpp/algorithm/find).

Adding `#include <algorithm>` to Helpers.h is the correct fix. Helpers.cpp can remain unmodified. Tested working on Arch/Clang 17.

**Comment by Caffarius** [comment]
Made a pull request that adds this one line of change. Hopefully it gets accepted so I don't have to keep doing it manually between testing the code from others. 😄

[Pull Request #329](https://github.com/liyunfan1223/mod-playerbots/pull/329)

**Comment by noisiver** [comment]
If the checks pass I'll merge it right away. I just compiled it and logged in to the game fine on Ubuntu 22.04. It's just an include so I don't see why it would fail in any of the checks.
