### ISSUE TITLE
Bot spams "Unknown command ..." + HelpAction::TellChatCommands

### ISSUE THREAD

**Issue by DQuinn97** [liyunfan1223/mod-playerbots#285]
**Describe the bug**
When you log in bots in your team, with certain addons enabled, it'll spam the "Unknown command" error followed by the HelpAction::TellChatCommands prompt.  It's not prohibiting any of the behaviour, but it is mildly annoying trying to read the chat.
I'm assuming PlayerbotAI::UpdateAIInternal is causing this spam?
I don't know if there's a way to detect if an addon caused the unknown command error or not, but if so can it be added to avoid unknown commands from addons spamming the chat?

**To Reproduce**
1. Add Carbonite addon on player client
2. Log in bot and invite to team
3. Wait a few seconds, it'll spam the described problem

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/44023796/3ead1700-a3aa-4d83-a4ab-6460217c7c9c)
![image2](https://github.com/liyunfan1223/mod-playerbots/assets/44023796/6c17fe62-6876-45a1-87f7-1b342d1da5b2)

**Comment by noisiver** [comment]
Jamba is worse. It's an endless spam of unknown command but when it pushes data to the party the bots opens a trade window - and pushing data is happening frequently.

**Comment by desigi** [comment]
I noticed the same happening to me recently. If you disable `Send position and level ups > To friends` in the `Privacy & Com` section of the settings, the spam will stop.
