### ISSUE TITLE
Compatibility notes with mod-aoe-loot/mod-gain-honor-guard

### ISSUE THREAD

**Issue by qyh214** [liyunfan1223/mod-playerbots#288]
**Is your feature request related to a problem? Please describe.**
seems when enable https://github.com/azerothcore/mod-aoe-loot or/and https://github.com/azerothcore/mod-gain-honor-guard
server will crash after running for a period of time. 
need  enable random robots.

**Describe the solution you'd like**
not crash or stop some modules for robots?

**Describe alternatives you've considered**
n/a

**Additional context**
Is there an API that can be easily called by other modules to confirm if it is a robot? If it is a robot, it will not take effect, such as isPlayerbot()?

**Comment by qyh214** [comment]
seems we can use player->getsession()->isbot to test,I will test

**Comment by qyh214** [comment]
### AOE_LOOT
https://github.com/azerothcore/mod-aoe-loot/blob/7633396693b9c490840808979439fc38cd95b2b5/src/aoe_loot.cpp#L29

add:
```c++
    if (player->GetSession()->IsBot())
        return;
```

### mod-gain-honor-guard
https://github.com/azerothcore/mod-gain-honor-guard/blob/258c67ff6e93d2903905c99ad82500e81129983c/src/GainHonorGuard.cpp#L175
```c++
if (!GainHonorGuardEnable || !player->IsAlive() || player->InArena() || player->HasAura(SPELL_AURA_PLAYER_INACTIVE))
```
replace to:
```c++
if (!GainHonorGuardEnable || !player->IsAlive() || player->InArena() || player->HasAura(SPELL_AURA_PLAYER_INACTIVE) || player->GetSession()->IsBot())
```

and
https://github.com/azerothcore/mod-gain-honor-guard/blob/258c67ff6e93d2903905c99ad82500e81129983c/src/GainHonorGuard.cpp#L177
```c++
if (!killed && killed->HasAuraType(SPELL_AURA_NO_PVP_CREDIT))
```
replace to:
```c++
if (!killed || (killed && killed->HasAuraType(SPELL_AURA_NO_PVP_CREDIT)))
```

**Comment by ReKsSam** [comment]
As of today, mod-gain-honor-guard is not working. 
Edits from this topic do not fix the problem.

**Comment by blinkysc** [comment]
You’d likely have to submit issues to the mod creator for those mods to get fixed

**Comment by ReKsSam** [comment]
mod-gain-honor-guard on "default" AzerothCore branch works. 
The problem is only on playerbots branch. I'll notify the mod author of this situation.
