### ISSUE TITLE
Increasing memory usage until crash.

### ISSUE THREAD

**Issue by aronkleinhans** [liyunfan1223/mod-playerbots#289]
**Describe the bug**
So after starting the server memory usage slowly increases from like 3 GB to 8Gb over 7-8 hours. Then the server crashes with bad_alloc.

**Commit hash**
[15d4b7a]

**To Reproduce**
1. build server
2. start server
3. have about 150-200 bots
4. see memory fill up

**Expected behavior**
Memory usage settles after a few minutes uptime.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: pi OS
 - Browser ? chrome
 - Version Bookworm
 - Raspberry Pi5 8Gb
 
**Additional context**
I couldn't find any solution to this, found some issues that lead nowhere, like the one about memory leaks but no indication of the solution being shared.

**Comment by noisiver** [comment]
The thing is, 8GB RAM isn't going to be enough over a longer period of time. All the maps it loads into memory aren't being unloaded. I don't have crashes, and my servers run 24/7 and only restart once a week (unless I trigger a manual restart). A full preload will eat ~11-12GB RAM and if I limit it to maps accessible by the bots it takes 6-7GB. Add on top of that everything else that eats memory.

**Comment by aronkleinhans** [comment]
I see, thanks for explaining!

**Comment by aronkleinhans** [comment]
Increased swap to 16GB 
Loaded all grids
Seems stable for now, can't really say anything about performance.

**Comment by aronkleinhans** [comment]
Yeah so here's how it looks after half a day
Just after start
![IMG_5261](https://github.com/liyunfan1223/mod-playerbots/assets/74680502/d93ccd76-cf90-4d82-936e-738f575e4074)
And after half a day
![IMG_5262](https://github.com/liyunfan1223/mod-playerbots/assets/74680502/b6569e1f-d53c-46ab-a85f-db38553b57ff)
The extra 100% cpu usage and random 1GB RAM usage is with all unused grids loaded and 200 max bots. With a huge swap and preload it is stable. But this is a sign of some leak I think.
Might be a linux specific issue (I suspect even ARM specific), But base AC doesn't have it.

Anyone willing to help me look into this?

**Comment by aronkleinhans** [comment]
[](https://github.com/liyunfan1223/mod-playerbots/issues/273) seems related

**Comment by aronkleinhans** [comment]
Turning off random bots logging in and existing altogether seems alleviate the issue...
So you can still use this to play solo or 2-3 players plus bots raid, but With your own accounts and characters you need to level up yourself normally or via commands.

**Comment by noisiver** [comment]
This was posted in the playerbots discord server.
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/760cbe92-6858-49f1-9e64-6ae22f21c3dc)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/7811aeec-a477-4a90-ae9f-a1ef834e5734)

Over 5 days with a memory usage of 7.6GB and no crashes, and with 1000 bots.

**Comment by aronkleinhans** [comment]
Weirdly enough, I restarted yesterday and it's been stable for 10h 30m no increase in ram or cpu usage. I'll let it run to see what's up.

**Comment by noisiver** [comment]
It is actually slowly creeping up. I have no idea why or if it's normal, or if it'll stop increasing eventually.

Here is just started. It's using 16.3%, 5062MB virt and 3908MB reserved
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/14b51b40-6043-4b44-b7b6-b79adbac0cce)

Here is after 11 hours. It's using 19.8%, 5946MB virt and 4741MB reserved
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/02a456aa-ba66-4e15-a5bc-e28c84c2beb5)

And finally, here is after 24 hours. It's using 21.6%, 6410MB virt and 5183MB reserved
![image](https://github.com/liyunfan1223/mod-playerbots/assets/5157047/e88d02f3-2267-4d09-b811-e2e56738e08d)
