### ISSUE TITLE
当服务器端使用中文DBC文件时机器人读取不到技能

### ISSUE THREAD

**Issue by andywy119** [liyunfan1223/mod-playerbots#29]
当服务器端使用中文DBC文件时（worldserver.conf 里设置 DBC.Locale = 4）机器人读取不到技能，改成英文的DBC机器人可以正常释放技能，是不是不支持中文技能？

**Comment by garfieldz90** [comment]
> 当服务器端使用中文DBC文件时（worldserver.conf 里设置 DBC.Locale = 4）机器人读取不到技能，改成英文的DBC机器人可以正常释放技能，是不是不支持中文技能？

源码里读取技能都是英文的，我看没跑了。

**Comment by liyunfan1223** [comment]
是的，要用英文DBC (enUS) 才能正常放技能，这会导致部分内容未汉化，我不知道是否有方案能解决汉化问题，例如让服务器同时使用中英文DBC

**Comment by AlvinZhu** [comment]
> 是的，要用英文DBC (enUS) 才能正常放技能，这会导致部分内容未汉化，我不知道是否有方案能解决汉化问题，例如让服务器同时使用中英文DBC

1. dbc目录里面同时英文的DBC，dbc\zhCN目录里面放中文DBC。
2. 配置文件设置使用中文dbc（worldserver.conf 里设置 DBC.Locale = 4）
3. 修改playbot相关代码，让playerbot强制使用英文：src/server/game/Server/WorldSession.h
```C++
// Locales
    LocaleConstant GetSessionDbcLocale() const { return _isBot? LOCALE_enUS : m_sessionDbcLocale; }
    LocaleConstant GetSessionDbLocaleIndex() const { return _isBot? LOCALE_enUS : m_sessionDbLocaleIndex; }
    char const* GetAcoreString(uint32 entry) const;
```
4. 修复azerothcore多语言dbc读取时会使用空字符串覆盖已有内容的Bug:src/server/shared/DataStores/DBCDatabaseLoader.cpp
https://github.com/AlvinZhu/azerothcore-wotlk/commit/34a7a947a4747d4c36a9d1e6c1d3fc2f0cd5e099
我的解决方案基本上是这样。
不过我已经在我的代码里面把playerbot移除了，无力维护，所以，加油。

**Comment by liyunfan1223** [comment]
非常感谢，我之后尝试一下

**Comment by acgogo2023** [comment]
最终的解决方案是什么？ 是使用英文DBC 吗？

**Comment by liyunfan1223** [comment]
> 不好意思，不是很明白最终的解决方案是什么？ 是使用英文DBC 吗？

英文dbc是必须要的
