### ISSUE TITLE
Error: Not enough random bot accounts available.

### ISSUE THREAD

**Issue by Phthisicus** [liyunfan1223/mod-playerbots#290]
For some reason it does nog matter how many account i create automaticly i still keep getting this arror.

<img width="776" alt="image" src="https://github.com/liyunfan1223/mod-playerbots/assets/76635863/72d408a3-2d8b-4c36-9a3e-71d9bf6cf11c">

When i create more than 900 accounts i get an error that ther eare not enough names available by simply names or someting.

Does anyone have an awnser for me?

**Comment by shockcollar95** [comment]
Can you add your playerbot.conf file? This would help to understand your settings.

**Comment by Phthisicus** [comment]
I only changed the DB information.

[playerbots.zip](https://github.com/user-attachments/files/16059422/playerbots.zip)

**Comment by shockcollar95** [comment]
Your settings are not correct, you need to change the following value:

From:
AiPlayerbot.RotationPoolSize = 10

To:
AiPlayerbot.RotationPoolSize = 4000

To explain this briefly, since your setting for RandomBotAccountCount is 600, the value of RotationPoolSize must not be less than 600 and not greater than 600*10, so you can choose a value between 600 and 6000. It should definitely work with 4000.

**Comment by Phthisicus** [comment]
> Your settings are not correct, you need to change the following value:
> 
> From: AiPlayerbot.RotationPoolSize = 10
> 
> To: AiPlayerbot.RotationPoolSize = 4000
> 
> To explain this briefly, since your setting for RandomBotAccountCount is 600, the value of RotationPoolSize must not be less than 600 and not greater than 600*10, so you can choose a value between 600 and 6000. It should definitely work with 4000.
> 
> I hope this will help you :)

Thnx! This is the awnser. Some settings are a little bit confusing to be honest. But your explenation made it more clear. I tought is was de amount of charaters that are rotated, but is is the complete pool of characters that rotate.

It is working now :)
