### ISSUE TITLE
Playerbots Stay level 1

### ISSUE THREAD

**Issue by Phthisicus** [liyunfan1223/mod-playerbots#291]
Hi Everyone,

I am testing and monitoring the playerbots while i am offline. But it seems that the bots are staying level 1. Is it possible that the bots level on there own without beeing online?

**Comment by christan-duplicate** [comment]
机器人分两种，1为随机机器人（系统自动上线的，此类机器人会自动在野外做任务和升级，不会随玩家上下线），2为召唤机器人（玩家用命令添加的，此类机器人随玩家上线而上线，下线而下线，不会自动在野外做任务升级)

**Comment by Phthisicus** [comment]
How do i change this type of bot?

**Comment by christan-duplicate** [comment]
暂时没办法更改类型，你直接用插件添加指定的机器人就行啦，只是这类机器人离队后不会自主行动而已。
或者改配置，让自动登录的机器人最大等级同步为在线玩家的等级：AiPlayerbot.SyncLevelWithPlayers = 1

**Comment by Phthisicus** [comment]
Ah ok thnx! If i understand your first comment correctly, the bots wil not complete tasks and level up when everyone is offline?

Becouse when everyone is offline on my server the bots wil stop and stand completely sill and do nothing?

**Comment by noisiver** [comment]
> Ah ok thnx! If i understand your first comment correctly, the bots wil not complete tasks and level up when everyone is offline?
> 
> Becouse when everyone is offline on my server the bots wil stop and stand completely sill and do nothing?

You didn't specify what kind you're talking about. The "random bots" will work while no players are online but player-alt bots will only work if **you're** online.

**Comment by Phthisicus** [comment]
> > Ah ok thnx! If i understand your first comment correctly, the bots wil not complete tasks and level up when everyone is offline?
> > Becouse when everyone is offline on my server the bots wil stop and stand completely sill and do nothing?
> 
> You didn't specify what kind you're talking about. The "random bots" will work while no players are online but player-alt bots will only work if **you're** online.

I ment the "random bots", how do i activate them, becouse it seems that the bots that i have on my server are doing nothing except when i am online.

**Comment by christan-duplicate** [comment]
> Ah ok thnx! If i understand your first comment correctly, the bots wil not complete tasks and level up when everyone is offline?啊，好的，谢谢！如果我正确理解你的第一条评论，当每个人都离线时，机器人将无法完成任务并升级？
> 
> Becouse when everyone is offline on my server the bots wil stop and stand completely sill and do nothing?因为当我的服务器上的每个人都离线时，机器人会停止并完全静止不动，什么也不做？

不对，随机机器人会自动上线和下线，并且会自己做任务升级；而玩家召唤的机器人才会跟随玩家下线而下线，而且不会自主做任务。

**Comment by Phthisicus** [comment]
Then there is something completely wrong with my server bots freeze when i go offline. 
How do i proceed? Because this was a clean build with https://github.com/liyunfan1223/azerothcore-wotlk repository and the https://github.com/liyunfan1223/mod-playerbots as the only addon installed. Dureing the C++ compiling there were a lot of warnings but no error as far as i have seen.

The warnings were the same as described in this issue: https://github.com/liyunfan1223/mod-playerbots/issues/225

Which OS are you using/prefering?
