### ISSUE TITLE
Hunter auto attack

### ISSUE THREAD

**Issue by shockcollar95** [liyunfan1223/mod-playerbots#293]
I don't know if this is a low level bug, but at lower levels hunters don't do autoshots.

My hunter bot is 23 and is not doing any autoshots.

**Comment by Dreathean** [comment]
Can you confirm what commit you're on? I wonder if this is from https://github.com/liyunfan1223/mod-playerbots/commit/51a88063f895481e672877be375bdf8b725f6110, but it could also be related to the commit from today which impacted ammo generation https://github.com/liyunfan1223/mod-playerbots/commit/3556a38dcdd155473b468db2c7f840b0cd944517. Would be interested to see if this occurs to higher level bots or not as well.

**Comment by shockcollar95** [comment]
I´m on this commit [c63fd39](https://github.com/liyunfan1223/mod-playerbots/commit/c63fd39b9211b36367ef1241936fd4010a8e76ac), the fix should be implemented here right?

**Comment by shockcollar95** [comment]
I updated the playerbot mod to the latest and still the hunters did not doing any autoshots.

**Comment by liyunfan1223** [comment]
Can you check if the bot has the correct ammo? It is generally caused by the lack of ammo.

**Comment by shockcollar95** [comment]
Oh, yes you are right. After I initiate the Bots and wrote autogear the bot got a gun but had still arrows in his gear.
I think after autogear the bot, he should change his ammo with arrows or arrows to ammo depends on the weapon he gets.

**Comment by liyunfan1223** [comment]
Got it, I'll fix this later. You should now be able to use the maintenance command to generate the correct ammo.

**Comment by shockcollar95** [comment]
Thanks :)
