### ISSUE TITLE
如何修改队员的职责(dps、tank)之类, 尤其是野德, 毕竟野性天赋有可能是熊, 也有可能是猫

### ISSUE THREAD

**Issue by olidammara** [liyunfan1223/mod-playerbots#296]
我使用的是群晖的AzerothCore端, 更新到了最新的1.0.20, 然后组了个5德队伍, 通过talents spec指定了其余4个AI德的天赋, 分别是
A: talents spec bear pve
B: talents spec cat pve
C: talents spec balance pve
D: talents spec resto pve
目前练到了20级, 均学会了猫形态
但在排随机本的时候, B的职责一直选的是坦克, 同时, 其他德也认为B是坦克, 会给他加荆棘术, B自身也一直用熊形态打怪.
为了5德队伍能正常运作, 我现在只能在排本前, 将B使用talents命令改为平衡并重置AI, 排进本后, 再将其改为cat pve, 然后手动修改AI策略, 去掉熊形态, 增加猫形态
所以, 有什么命令可以指定AI的职责么, 让他认为自己是dps?

**Comment by qyh214** [comment]
我也有类似问题，用的是插件https://github.com/liyunfan1223/unbot-addon

但是，每次都需要调整下策略，最好能有单独命令直接告诉他需要坦克 或者奶 然后切换对应天赋，如果有多个，可以随机，或者进一步让选择

**Comment by christan-duplicate** [comment]
先把天赋切换成野德，然后用插件策略设为dps，就行了，排随机本的时候就会认定你是dps

**Comment by olidammara** [comment]
> 先把天赋切换成野德，然后用插件策略设为dps，就行了，排随机本的时候就会认定你是dps

请问具体是哪个策略? 我在编辑策略中取消了熊形态, 增加了猫形态, 攻击方式也是坦克协助, 他还是认为自己是坦……

**Comment by olidammara** [comment]
> 先把天赋切换成野德，然后用插件策略设为dps，就行了，排随机本的时候就会认定你是dps

我又上去试了一下, 天赋换成了cat pve, 策略取消了熊, 取消了坦克协助, 但无法激活单体dps, 只能点亮dps协助, 排本他还认为自己是坦

**Comment by christan-duplicate** [comment]
单体dps策略是无法开启，能开启群体dps,协助dps，具体规则，要看代码了

**Comment by liyunfan1223** [comment]
Feral druids without the thick hide will now automatically adopt the cat strategy, please note that the cat strategy is now not as smart as most other strategies currently.
