### ISSUE TITLE
Arathi Basin Alliance Bots staying at Stables indefinitely

### ISSUE THREAD

**Issue by Zaedon33** [liyunfan1223/mod-playerbots#300]
**Describe the bug**
Battleground: Arathi Basin - Alliance Bots staying at Stables indefinitely.

**Commit hash**
02786e6b6d583839c879c55c6504446a7111020d

**To Reproduce**
1. Join Arathi Basin via PvP tab > Battlegrounds > Arathi Basin
2. All Alliance Bots will stay at Stables for the entire duration of the battleground.

**Expected behavior**
Alliance Bots should move to other bases/flags to capture them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Additional context**

**Comment by Dreathean** [comment]
This was reported and discussed here https://github.com/liyunfan1223/mod-playerbots/issues/69, fortunately it looks like the main issue has been discovered and a fix is in the works.

**Comment by Zaedon33** [comment]
Excellent!
