### ISSUE TITLE
The worldserver crashes intermittently

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#301]
The worldserver crashes intermittently, sometimes after 0.5 hour, other times after 1-4 hours. It appears that crashes only occur when there is more than one player. Here is the crash log.
[unknown_worldserver.exe_[4-7_16-1-35].txt](https://github.com/user-attachments/files/16104336/unknown_worldserver.exe_.4-7_16-1-35.txt)
[unknown_worldserver.exe_[5-7_2-46-31].txt](https://github.com/user-attachments/files/16104337/unknown_worldserver.exe_.5-7_2-46-31.txt)

**Comment by christan-duplicate** [comment]
看你这错误日志，应该是mod-autobalance引起的，建议删除此mod，本来用了playerbots后，mod-autobalance可有可无了。

**Comment by zbhcn** [comment]
> 看你这错误日志，应该是mod-autobalance引起的，建议删除此mod，本来用了playerbots后，mod-autobalance可有可无了。

希望你说的是对的，感谢

**Comment by zbhcn** [comment]
试过了，不是mod-autobalance的问题，关了没用同样的crash，日志一样的

**Comment by christan-duplicate** [comment]
关了mod-autobalance日志还是一样？我看你发的日志定位就是mod-autobalance里的代码

**Comment by zbhcn** [comment]
> 关了mod-autobalance日志还是一样？我看你发的日志定位就是mod-autobalance里的代码

是的，真正的宕机位置是在第一行后面的都没太大参考价值

**Comment by liyunfan1223** [comment]
Crashes occurred in mod-autobalance.
