### ISSUE TITLE
Bots cast custom spells multiple times

### ISSUE THREAD

**Issue by pilovm** [liyunfan1223/mod-playerbots#308]
**Describe the bug**
If you ask a bot to cast a spell it will attempt to cast it until it fails OR performed the number of times equal to the spell id.

I discovered the bug by teleporting the bot to Stormwind (cast "Teleport: Stormwind", spellId 3561), but it seems to be the problem for all spells, but many of them fail to cast second time due to cooldown.

**Commit hash**
The hash of the current commit: 294b3674c92e9a1e31a7698d40d95a14ebae7139

**To Reproduce**
1. Invite Mage class character to your party
2. Make sure it has more than one Rune of Teleportation: `.additem 17031 5`
3. Ask the bot to cast "Teleport: Stormwind" spell: `cast 3561`
4. See the bot to attempt to cast the spell 3561 times. It is gonna stop only when it runs out of Rune of Teleportation.

**Expected behavior**
The spell should have been casted just once.

**Additional context**
I found that [/src/strategy/actions/CastCustomSpellAction.cpp](https://github.com/liyunfan1223/mod-playerbots/blob/master/src/strategy/actions/CastCustomSpellAction.cpp#L77) contains some logic related to cast counts:
```
castCount = atoi(param.c_str());
if (castCount > 0)
       text = text.substr(0, pos);
```
So, it uses the spell ID from the chat command as an argument for number of times the spell should be casted, which seems to be the cause of the issue.

**Comment by liyunfan1223** [comment]
I agree to remove these codes. Multiple casting seems unnecessary, welcome to make a PR.
