### ISSUE TITLE
Druid Feral DPS "talents spec cat pve" problems

### ISSUE THREAD

**Issue by cptcl** [liyunfan1223/mod-playerbots#309]
**Describe the bug**
A Randombot as Druid Feral only ques up as Tank. even with command "talents spec cat pve" and AIreset, strategy editor shows "bear form" and the druid will not use cat form at all, even after set to "cat" and "cat aoe"

**Commit hash**
1f8b347

**To Reproduce**
Summon a Druid
and initialize him until its feral
/w him "talents spec cat pve"
check his talents -> should look good for feral dps (check for Feral tree and the 2nd row 3rd talent, should not be taken as cat)
Que in dugeonfinder and he will que as Tank
Look into strategy editor and u will see "bear" is active
Click on "cat" and "cat aoe"
Que again in dungeonfinder and he still que up as tank
Try walk into dungeon and summon the druid
go in a fight with the druid on your side 
he will not use any sort of forms

**Expected behavior**
Druid should que up as dps
Druid should use catform 

**Screenshots**
-

**Comment by liyunfan1223** [comment]
Feral druids without the thick hide will now automatically adopt the cat strategy, please note that the cat strategy is now not as smart as most other strategies currently.
