### ISSUE TITLE
AiPlayerBots starter gear

### ISSUE THREAD

**Issue by Ferreira9006** [liyunfan1223/mod-playerbots#310]
**Is your feature request related to a problem? Please describe.**
I've been trying to make the bots that you see on the cities, battlegrounds, and arenas have better gear, but I can't seem to find a solution for this.
Note: I'm not trying to modify the ones that you can summon (called RandomBots I believe). Those (RandomBots) I can change their gear without issues by modifying this https://github.com/liyunfan1223/mod-playerbots/blob/1f8b34778cce0adc08e0534135815ba163d29fd0/conf/playerbots.conf.dist#L187 and using the command .playerbot bot init=auto while being on a party with them.

I've tried checking on the database if any tables specified the gear based on class/spec/faction, but I can't seem to find it, only for the enchants. I believe this is coded somewhere or can be edited, I'm just not finding where 🙂

**Describe the solution you'd like**
A way to modify the player bots gear, or, if this isn't planned for this module, some information on how I can modify their gear :)

**Comment by Dreathean** [comment]
Just to clear up any confusion on the naming, the bots you see in the wild, cities, bgs, etc are the "Randombots", as they are, well, random. The ones you create yourself don't exactly have an official name but are usually referred to as "Alt-bots".

**Comment by liyunfan1223** [comment]
It's not configurable now. I'm going to make it.

**Comment by Ferreira9006** [comment]
Great! 
I figured that if you modify PlayerbotFactory.cpp you can make bots have better equipment. However, what I did is kind of a hack fix, and I'm sure that you want a long term solution :)
