### ISSUE TITLE
BOT Stun in Battlegrounds / Arenas

### ISSUE THREAD

**Issue by Ferreira9006** [liyunfan1223/mod-playerbots#313]
**Describe the bug**
Bots currently don't respect the stun you give them. If you charge anyone as a warrior, they will keep moving (stuttering movement, like they are lagging)

**Commit hash**
The hash of the current commit.

**To Reproduce**
1. Go into BG
2. Charge at someone
3. See the bug

**Expected behavior**
Bots should stand still until the stun passes.

**Comment by Dreathean** [comment]
Fuzz is working on a fix for this, he determined that it is due to bots using the escort movement function.

**Comment by Ferreira9006** [comment]
Great news! Good job team :)

**Comment by Dreathean** [comment]
![image](https://github.com/user-attachments/assets/19e95ab7-faa9-491a-a9a1-5a2ba7326bd7)
Fixed in https://github.com/liyunfan1223/mod-playerbots/pull/318, keep in mind this change in movement could cause other consequences that have not yet been determined.
