### ISSUE TITLE
Bots in Dalaran Sewers

### ISSUE THREAD

**Issue by Ferreira9006** [liyunfan1223/mod-playerbots#314]
**Describe the bug**
Bots in Arena Dalaran Sewers are bugged. They don't jump down from the tube, therefore you can't fight them.

**Expected behavior**
Bots should jump down in order to play the arena.

**Comment by Jgoodwin64** [comment]
Is this still a thing in the latest revision?

**Comment by liyunfan1223** [comment]
It works now. https://github.com/liyunfan1223/mod-playerbots/pull/298
