### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by garfieldz90** [liyunfan1223/mod-playerbots#32]
请问如何去查看服务崩溃的原因？因为每次服务停止只写了一句服务核心停止的语句，不知道什么原因导致的，想了解并且优化自己新增的代码看看哪里导致的服务停止了。 @liyunfan1223

**Comment by liyunfan1223** [comment]
gdb，崩溃后用bt命令查看调用栈，参考 https://www.bitdegree.org/learn/gdb-debugger

**Comment by garfieldz90** [comment]
哇太棒了，谢谢，后续继续贡献高质量代码 @liyunfan1223
