### ISSUE TITLE
Bots cannot open [Satchel of Helpful Goods] item

### ISSUE THREAD

**Issue by 7e3J4y** [liyunfan1223/mod-playerbots#322]
Using Unbot, and by trying to invoke the usage manually by using "u [Satchel of Helpful Goods]", bots are incapable of opening the item and getting the items held inside. In the inventory view of Unbot, trying to use the item causes it to temporarily disappear, but nothing actually happens, as refreshing their inventory reveals it again. I suspect the bots are not capable of using any `<Right Click to Open>` items.

**Comment by Dreathean** [comment]
Should now be able to command bots to open using the new "open items" command - thank you Avirar! https://github.com/liyunfan1223/mod-playerbots/pull/569
