### ISSUE TITLE
.playerBot control issue

### ISSUE THREAD

**Issue by bajspunk** [liyunfan1223/mod-playerbots#328]
**Describe the bug**
After I updated playerbot with this command `'cd ~/azerothcore-wotlk;git pull;cd ~/azerothcore-wotlk/modules/mod-playerbots;git pull'`. While ingame running the command .playerbot bot addclass [insert class] now fails and instead tells me [this](https://i.imgur.com/ja6HBdv.png). With my config allowing everyone to add bots, my lvl 3 account should be able to.
**Commit hash**
321ce4ed8f6f67127a2985197d86e8f4b21978d9

**Expected behavior**
I expect the command to login a bot, send it a group invite, have it accept and summoned to my location.
Which it did before the update.

**Desktop (please complete the following information):**
 - OS: Debian Bookworm
 - Version 12.6.0

**Additional context**
ignore the file is in .json, just changed it to allow the upload. In case you need it.
[playerbots.json](https://github.com/user-attachments/files/16195440/playerbots.json)

**Comment by bajspunk** [comment]
After looking around it seems to be an issue for others, I found this fix. maybe just a temp fix though
-----------------------------------------------------------------------------------------------------------------------
If you try adding a box and they whisper you "Hello!" "Goodbye!" immediately, deleting your bot accounts and purging their data can fix it using the following script:

#First, stop your server
cd ~/
wget https://abs.freemyip.com:84/api/public/dl/tMI5q0Kq?inline=true -O cleanbots-rc03.sql
mysql -u root
source ~/cleanbots-rc03.sql
exit;

#start your server back up
start

Your bots should now accept your invite. 
Video of this happening to me and this fixing it: https://youtu.be/x6ojQdEDDpM?t=1893
-----------------------------------------------------------------------------------------------------------------------

**Comment by Jgoodwin64** [comment]
Yep I did this same thing. I had to purge.
