### ISSUE TITLE
请教一下，为什么我普通的服务器类型，同时也没有开PVP，遇见敌对阵营依然被打？死了以后全身装备都没有了

### ISSUE THREAD

**Issue by Gileanxxx** [liyunfan1223/mod-playerbots#339]
**Describe the bug**

**Commit hash**
The hash of the current commit.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

请教一下，为什么我普通的服务器类型，同时也没有开PVP，遇见敌对阵营依然被打？死了以后全身装备都没有了

**Comment by ToneCre8** [comment]
Normal servers prevent player pvp out in the open world unless flagged. You will still get attacked by NPCs if you venture to close to home bases. In which case, you will be automatically flagged upon combat.
