### ISSUE TITLE
[SOLVED] Current build breaks Eluna

### ISSUE THREAD

**Issue by LitchLight** [liyunfan1223/mod-playerbots#347]
**Describe the bug**
Current PlayerBots/AzerothCore ? build breaks compilation of Eluna with following errors ...

```
/home/acore/azerothcore-wotlk/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp:240:10: error: ‘void Eluna_AllMapScript::OnBeforeCreateInstanceScript(InstanceMap*, InstanceScript*, bool, std::string, uint32)’ marked ‘override’, but does not override
  240 |     void OnBeforeCreateInstanceScript(InstanceMap* instanceMap, InstanceScript* instanceData, bool /*load*/, std::string /*data*/, uint32 /*completedEncounterMask*/) override
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acore/azerothcore-wotlk/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp:333:10: error: ‘bool Eluna_CommandSC::CanExecuteCommand(ChatHandler&, std::string_view)’ marked ‘override’, but does not override
  333 |     bool CanExecuteCommand(ChatHandler& handler, std::string_view cmdStr) override
      |          ^~~~~~~~~~~~~~~~~
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/GameObjectAI.cpp.o

```
**Commit hash**
The hash of the current commit.
* AzerothCore revision            : 05c9a96ba99c 2024-07-11 12:32:13 +0800 (Playerbot branch)
* AzerothCore buildtype           : RelWithDebInfo

* Install core to                 : /home/acore/AzerothCore
* Install libraries to            : /home/acore/AzerothCore/lib
* Install configs to              : /home/acore/AzerothCore/etc

**Desktop (please complete the following information):**
FatDog64 901 (Linux) 6.1.46 2 SMP PREEMPT_DYNAMIC Thu Sep 14 22:07:07 AEST 2023 x86_64 AMD Phenom(tm) II X3 B75 Processor AuthenticAMD GNU/Linux
12GB Ram

cmake version 3.26.2
gcc (GCC) 12.2.0
clang version 15.0.7
ldd (GNU libc) 2.37
BOOST_VERSION
#define BOOST_LIB_VERSION "1_81"
go version go1.22.3 linux/amd64
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
mysqld Ver 10.6.14-MariaDB for Linux on x86_64 (Source distribution)

**Additional context**

* Modules configuration (static):
  |
  +- worldserver
  |   +- mod-1v1-arena
  |   +- mod-ah-bot
  |   +- mod-eluna
  |   +- mod-guildhouse
  |   +- mod-improved-bank
  |   +- mod-keep-out
  |   +- mod-low-level-arena
  |   +- mod-npc-spectator
  |   +- mod-playerbots
  |   +- mod-solocraft
  |   +- mod-starter-guild
  |   +- mod-transmog
  |

Solution:
/home/acore/azerothcore-wotlk/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp

Turn off "override"...

```
class Eluna_CommandSC : public CommandSC
{
public:
    Eluna_CommandSC() : CommandSC("Eluna_CommandSC") { }

    bool CanExecuteCommand(ChatHandler& handler, std::string_view cmdStr) /*override*/
    {
        if (!sEluna->OnCommand(handler, std::string(cmdStr).c_str()))
        {
            return false;
        }

        return true;
    }
};

```

Update Eluna_AllMapScript class to align with "OnBeforeCreateInstanceScript".
This is defined in:
/root/acore/azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllMapScript.h

Change the routine to align to the definiition in that file ^^.
Change must occur in: 
/home/acore/azerothcore-wotlk/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp

```
class Eluna_AllMapScript : public AllMapScript
{
public:
    Eluna_AllMapScript() : AllMapScript("Eluna_AllMapScript") { }

    void OnBeforeCreateInstanceScript(InstanceMap* instanceMap, InstanceScript** instanceData, bool load, std::string data, uint32 completedEncounterMask) override
    {
        *instanceData = sEluna->GetInstanceData(instanceMap);
    }

    void OnDestroyInstance(MapInstanced* mapInstanced, Map* map) override
    {
        sEluna->FreeInstanceId(map->GetInstanceId());
    }

    void OnCreateMap(Map* map) override
    {
        sEluna->OnCreate(map);
    }

    void OnDestroyMap(Map* map) override
    {
        sEluna->OnDestroy(map);
    }

    void OnPlayerEnterAll(Map* map, Player* player) override
    {
        sEluna->OnPlayerEnter(map, player);
    }

    void OnPlayerLeaveAll(Map* map, Player* player) override
    {
        sEluna->OnPlayerLeave(map, player);
    }

    void OnMapUpdate(Map* map, uint32 diff) override
    {
        sEluna->OnUpdate(map, diff);
    }
};
```

**Comment by zbhcn** [comment]
I suspect that my intermittent crashes might also be related to this Eluna issue.

**Comment by LitchLight** [comment]
> I suspect that my intermittent crashes might also be related to this Eluna issue.

No. This issue stops the compile from completing with the above error. If your compile finished 100% then this is not your problem.

**Comment by zbhcn** [comment]
oh,my compile was completed,and there is no problem as you mentioned

**Comment by noisiver** [comment]
You shouldn't use Eluna with Playerbots to begin with.
![image](https://github.com/user-attachments/assets/71945ac8-b11a-486c-8b3a-bcb7705f4033)
![image](https://github.com/user-attachments/assets/be80d92a-c600-4695-ad0d-60c8b45a3ffb)

**Comment by zbhcn** [comment]
> 首先，您不应该将 Eluna 与 Playerbots 一起使用。 ![图像](https://private-user-images.githubusercontent.com/5157047/350167614-71945ac8-b11a-486c-8b3a-bcb7705f4033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI1MjEsIm5iZiI6MTcyMTM1MjIyMSwicGF0aCI6Ii81MTU3MDQ3LzM1MDE2NzYxNC03MTk0NWFjOC1iMTFhLTQ4NmMtOGIzYS1iY2I3NzA1ZjQwMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDEyMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVmNjA3ZGMxNWZlOGVlYmI3ODUyZDk1NjBmNDdhMjNmZDRjNGZjNzk5YzU1YWJkYmVhNTM2ZGVmZjczZGYwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bik0J48xhfycjnEmy7ErHv825iRrfVqeXUxhuAzZEl4) ![图像](https://private-user-images.githubusercontent.com/5157047/350167625-be80d92a-c600-4695-ad0d-60c8b45a3ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI1MjEsIm5iZiI6MTcyMTM1MjIyMSwicGF0aCI6Ii81MTU3MDQ3LzM1MDE2NzYyNS1iZTgwZDkyYS1jNjAwLTQ2OTUtYWQwZC02MGM4YjQ1YTNmZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDEyMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjY4MmY4Y2ZhMDI1YTdlYmQ0YWU5Y2EzYjBhZjU3NmI2MmRiZTU5ZWVlNDEwNjk5MTMzODI2YzRhNzg4MmUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ge8Tdn2392aO00a73KdZJHPtLuhcrUTD75Qzu_YrSW0)

thank you , by the way , where did the information in your picture come from? is it reliable?

**Comment by noisiver** [comment]
The information comes from the AzerothCore discord server, from Foe who is one of the people responsible for the AC Eluna module. It is reliable.

**Comment by LitchLight** [comment]
Performance with less than 1000 bots has been acceptable.
