### ISSUE TITLE
LFG issue.

### ISSUE THREAD

**Issue by nugsforthugs** [liyunfan1223/mod-playerbots#350]
**Describe the bug**
When using LFG, between levels 15 - 29 - if you select "Random Dungeon" it will show on the console everyone of that level range queuing up then it pops and works as intended for that level bracket.

Go into other brackets such as 30 - 40 - 50 - 60, even /who 30-39, /who 40-49, etc there are plenty of bots on my server (1300) and not one of them queues up if you select "Random Dungeon". It shows the same levels 20 - 25 - 30 in the consoles queuing up for your level bracket.

If you select "Specific Dungeon" and select one from the list and then queue, they will queue as intended and show the appropriate levels queuing in console and the dungeon will pop and you'll be able to do it.

**Commit hash**
9b1736e61f3c6a732c721d8045fca19531daf0d4

**To Reproduce**
1. Create new character, either side: type into chat .levelup 15 and then queue for a random dungeon, you'll see it works perfect
2. Leave dungeon, then type .levelup 40, then queue again to random dungeon - you'll sit in queue forever, not one bot queues.
3. Cancel queue for random, select "Specific Dungeon" from the list, select any dungeon you want and then you'll see they queue up and work as intended.

**Expected behavior**
Random dungeon obviously queues bots up at the proper level brackets and selects a random dungeon.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by davvvve1** [comment]
Same here

**Comment by noisiver** [comment]
I don't know, I don't have any issues with it. I selected all roles to make sure I have the best chance of getting a group.

![image](https://github.com/user-attachments/assets/e2e13977-0892-48ee-93a3-f731961e86d4)

**Comment by davvvve1** [comment]
I have recompiled everything - Same fault -. I play dps -Hunter

**Comment by nugsforthugs** [comment]
> I don't know, I don't have any issues with it. I selected all roles to make sure I have the best chance of getting a group.
> 
> ![image](https://private-user-images.githubusercontent.com/5157047/349969987-e2e13977-0892-48ee-93a3-f731961e86d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjUwNDMsIm5iZiI6MTcyMTMyNDc0MywicGF0aCI6Ii81MTU3MDQ3LzM0OTk2OTk4Ny1lMmUxMzk3Ny0wODkyLTQ4ZWUtOTNhMy1mNzMxOTYxZTg2ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTc0NTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQxMDIxYThlYTkwNTc0YWRkMDhkOGM4YWU5M2U3YmY4OTkxYWVmNmJiYzk0MGVjYTVmOGQyNzAzYWEwZmJlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kx7we_a4d9hVX9XwqPmzMr0f9ntJ2TSgnXZmY3KnO7s)

As a Druid or paladin that works cause they can select all 3 roles, as a mage, warlock, rogue, etc that can only select dps this is where the issue is at for me at least.

**Comment by noisiver** [comment]
Well, maybe there aren't enough tanks or healers in your range? I don't see that as an issue with the actual system, although it could be changed to change someone into a tank or a healer if one doesn't exist (that would be nice), but rather the lack of certain roles.

**Comment by davvvve1** [comment]
Nope . If you  /1 @tank who  , alot of tanks at my lvl shows up . Its a bug . Im 41 atm. But looking for specific dungeon works

**Comment by davvvve1** [comment]
I have the server on my other screen . When i press Random Classic Dungeon , it search but the "players" that come up are not the same level .- like lvl 18 - 25  . It should be lvl 40 ish i guess ?

**Comment by davvvve1** [comment]
And another bug is that not all of the bots summon to the dungeon , you have to manual /p summon for it to work .

**Comment by davvvve1** [comment]
Now @level 43 i used Random and it worked .  Gonna try more .

**Comment by noisiver** [comment]
> And another bug is that not all of the bots summon to the dungeon , you have to manual /p summon for it to work .

That's a known issue and happens no matter what way you get there. I can happen even when running in manually with a group of bots.

**Comment by Dreathean** [comment]
Fixed here https://github.com/liyunfan1223/mod-playerbots/pull/377
