### ISSUE TITLE
[SpellInfo missing]当使用cast [spell]来让机器人施放技能时会导致服务崩溃

### ISSUE THREAD

**Issue by olidammara** [liyunfan1223/mod-playerbots#356]
群晖版本, 刚更新到1.0.23
在之前的版本中, 使用cast [spell]时, 机器人会正确使用法术, 而在更新后使用该命令, 会导致服务崩溃, 只能重启整个项目.
查看Playerbots.log, 只有"SpellInfo missing"这一句话. 之前版本中这个log一直是空的.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/353
