### ISSUE TITLE
Level cap for bots

### ISSUE THREAD

**Issue by qoreycube** [liyunfan1223/mod-playerbots#361]
**Is your feature request related to a problem? Please describe.**
I'd like to try to complete raid content before moving on to the next expansions. I can't find a configuration option to stop my bots from leveling beyond a certain level. For example, I'd like them to stop leveling at 60 until we complete the raid content for the original game, 70 for TBC, etc.

**Describe the solution you'd like**
Add a configuration to set a level to stop bots from leveling beyond that level.

**Comment by liyunfan1223** [comment]
Setting Expansion or MaxPlayerLevel should work.

**Comment by Dreathean** [comment]
Closing as this is already a config in the worldserver.conf
