### ISSUE TITLE
Repeated crashing with latest branch.

### ISSUE THREAD

**Issue by ToneCre8** [liyunfan1223/mod-playerbots#362]
See attached.
[unknown_worldserver.exe_[21-7_0-46-42].txt](https://github.com/user-attachments/files/16325614/unknown_worldserver.exe_.21-7_0-46-42.txt)
[unknown_worldserver.exe_[21-7_0-44-1].txt](https://github.com/user-attachments/files/16325615/unknown_worldserver.exe_.21-7_0-44-1.txt)

**Comment by noisiver** [comment]
This isn't really the fault of playerbots. I use junk-to-gold (duh, I made it) with zero issues while some have crashes like this. I seem to remember reading something about Eluna causing some kind of conflict.

**Comment by ToneCre8** [comment]
No, not anymore. I did have crashes before that were directly related to junk-to-gold. But those were easily spotted in the call stack when debugging so I removed the module. 
I also read that Eluna shouldn't be used with player bots so I removed it as well. So my most recent build doesn't include those modules.

**Comment by Dreathean** [comment]
If you're interested, try using junk-to-gold now that you removed Eluna. It's worked for people after removing Eluna before to my knowledge.
