### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by stevenbruy** [liyunfan1223/mod-playerbots#37]
tried to compile the module with the custom server. without module the world compiles with no issues. with the module i always get the same 2 errors. what does it mean?

15>Done building project "modules.vcxproj" -- FAILED.

18>LINK : fatal error LNK1181: cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'
18>Done building project "worldserver.vcxproj" -- FAILED.
19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
19>Building Custom Rule C:/AzerothCore_PB/azerothcore-wotlk/CMakeLists.txt
========== Build: 17 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 8:23 PM and took 17:29.321 minutes ==========

**Comment by ManGuyNY** [comment]
I get the same, seems to be related to a recent commit. Rolling back to [https://github.com/liyunfan1223/mod-playerbots/commit/e8961687692c10c72c23695bd72aac07551879bc](url) compiles fine. 
![image](https://github.com/liyunfan1223/mod-playerbots/assets/115581060/ddba8113-f9a6-458e-bab4-f77e27f4ff8d)

**Comment by stevenbruy** [comment]
> I get the same, seems to be related to a recent commit. Rolling back to [https://github.com/liyunfan1223/mod-playerbots/commit/e8961687692c10c72c23695bd72aac07551879bc](url) compiles fine. ![image](https://user-images.githubusercontent.com/115581060/271011430-ddba8113-f9a6-458e-bab4-f77e27f4ff8d.png)

Aah ty for the reply. Tommorow I'll be back from holiday and try to compile with the mod from link ;-)

**Comment by liyunfan1223** [comment]
should be fixed in https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5

**Comment by ManGuyNY** [comment]
> should be fixed in [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5)

Can confirm. Thanks!

**Comment by stevenbruy** [comment]
Weird, i cloned everything fresh just now (core and module), checked if the cc10cad fix has the correct line. stil get  2 errors on compiling.

18>LINK : fatal error LNK1181: cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'
18>Done building project "worldserver.vcxproj" -- FAILED.
19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
19>Building Custom Rule C:/AzerothCore_PB/azerothcore-wotlk/CMakeLists.txt
========== Build: 17 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:37 PM and took 16:45.117 minutes ==========

> should be fixed in [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5)

**Comment by alexpec1** [comment]
The author has fixed it, now re-git and compile again without error, it can pass, I just compiled it last night.

**Comment by stevenbruy** [comment]
> The author has fixed it, now re-git and compile again without error, it can pass, I just compiled it last night.

deleted everything. cloned everything fresh but still have 2 failed:
18>LINK : fatal error LNK1181: cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'
18>Done building project "worldserver.vcxproj" -- FAILED.
19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
19>Building Custom Rule C:/azerothcore-wotlk/CMakeLists.txt
========== Build: 17 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 2:13 PM and took 16:36.473 minutes ==========

can compile perfectly without the mod. and i use the custom branch that is linked in the readme of the mod. I really have no clue what is happening to cause this since it works for others. i do everything the same way i compile the azerothcorecore + mods.

**Comment by liyunfan1223** [comment]
> Weird, i cloned everything fresh just now (core and module), checked if the [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5) fix has the correct line. stil get 2 errors on compiling.
> 
> 18>LINK : fatal error LNK1181: cannot open input file '......\modules\RelWithDebInfo\modules.lib' 18>Done building project "worldserver.vcxproj" -- FAILED. 19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------ 19>Building Custom Rule C:/AzerothCore_PB/azerothcore-wotlk/CMakeLists.txt ========== Build: 17 succeeded, 2 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 10:37 PM and took 16:45.117 minutes ==========
> 
> > should be fixed in [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5)
> 
> Tried a few mor compiles this time just cloning it right on the c drive to avoid maybe to long paths or so. stil getting quiet some errors. one of such is labeled as fatal error:
> 
> 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxActions.cpp) 15>RogueOpeningActions.cpp 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxMultipliers.cpp) 15>RogueTriggers.cpp 15>CasterShamanStrategy.cpp 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxTriggers.cpp)
> 
> i cloned Liyunfan1223 modded core from the link in the mod-playerbots help file, and cloned the mod-playerbots module into the modules directory, so i dont know why it cant find some files.

Did you clone the right branch of the core? `git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot --depth=1`

**Comment by stevenbruy** [comment]
> > Weird, i cloned everything fresh just now (core and module), checked if the [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5) fix has the correct line. stil get 2 errors on compiling.
> > 18>LINK : fatal error LNK1181: cannot open input file '......\modules\RelWithDebInfo\modules.lib' 18>Done building project "worldserver.vcxproj" -- FAILED. 19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------ 19>Building Custom Rule C:/AzerothCore_PB/azerothcore-wotlk/CMakeLists.txt ========== Build: 17 succeeded, 2 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 10:37 PM and took 16:45.117 minutes ==========
> > > should be fixed in [cc10cad](https://github.com/liyunfan1223/mod-playerbots/commit/cc10cad03ad4cdb9c42974e1f037d18ef29adfc5)
> > 
> > 
> > Tried a few mor compiles this time just cloning it right on the c drive to avoid maybe to long paths or so. stil getting quiet some errors. one of such is labeled as fatal error:
> > 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxActions.cpp) 15>RogueOpeningActions.cpp 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxMultipliers.cpp) 15>RogueTriggers.cpp 15>CasterShamanStrategy.cpp 15>C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxScripts.h(4,10): fatal error C1083: Cannot open include file: '../../../../src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.h': No such file or directory (compiling source file C:\azerothcore-wotlk\modules\mod-playerbots\src\strategy\raids\naxxramas\RaidNaxxTriggers.cpp)
> > i cloned Liyunfan1223 modded core from the link in the mod-playerbots help file, and cloned the mod-playerbots module into the modules directory, so i dont know why it cant find some files.
> 
> Did you clone the right branch of the core? `git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot --depth=1`

Ok i can compile it with the git clone you send. i followed the mod-playerbot readme to: https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot
and cloned the https://github.com/liyunfan1223/azerothcore-wotlk.git link there. seems my knowledge of github is not the best.

thank you for the help and patience!
