### ISSUE TITLE
数据库结构报错

### ISSUE THREAD

**Issue by luyingwei80** [liyunfan1223/mod-playerbots#373]
**Describe the bug**
更新克隆最新azerothcore自定义分支与playerbots插件分支，编译运行后提示“[1054] Unknown column 'modelid1' in 'field list'
”错误，worldserver进程自动终止。更新前项目可正常运行，后尝试重建空数据库，重新克隆项目源码编译，故障依旧，不知如何解决。

**Screenshots**
![image](https://github.com/user-attachments/assets/438a2c11-c44b-4d56-a368-4e1dee4a3d61)
**Desktop (please complete the following information):**
 - OS: ubuntu 24
 - mysql:8.0

**Comment by christan-duplicate** [comment]
acore_world.creature_template 这个表里有 modelid1、modelid2、modelid3、modelid4吗

**Comment by luyingwei80** [comment]
不知为何我即便重新下载源码编译，并清空数据库后依然存在这个问题，是否能将这几个字段添加到补丁中去？

**Comment by christan-duplicate** [comment]
你没有这些字段，说明表结构是旧的，要更新表

**Comment by luyingwei80** [comment]
请问通过哪个文件进行更新？

**Comment by christan-duplicate** [comment]
![image](https://github.com/user-attachments/assets/c0f7a05f-8f1d-4182-80a7-5a2ea2a9c699)
你配置里有没有把数据库自动更新打开，最好打开，不然每次编译后运行，如果对方更新了sql，你的不会跟着更新。

**Comment by luyingwei80** [comment]
麻烦能否告知配置文件里的哪个选项是自动更新数据库的？

**Comment by christan-duplicate** [comment]
authserver.conf
Updates.EnableDatabases = 1

worldserver.conf
Updates.EnableDatabases = 7

**Comment by luyingwei80** [comment]
非常感谢，但是很奇怪我看了我的配置文件里面是按照默认“7”配置的，但不知为啥依然问题依旧。

**Comment by wangmz29** [comment]
看看你都用了什么会读取creature_template表modelid字段的mod或lua，最近更新把creature_template表里的modelid1-4都去掉了，如果你用的mod或lua没更新那也会报错

**Comment by luyingwei80** [comment]
我就用了您的playerbots和eluna2个mod，并且也用git pull做了更新。刚才我也去源码中查看了creature_template.sql文件内容，似乎并没有看到modelid有关的内容，是否这个新结构是放在某个“补丁”sql文件里做更新的？

**Comment by luyingwei80** [comment]
我去掉eluna后这个错误确实消失了。但是有什么办法能让eluna也能一起运行么？

**Comment by wangmz29** [comment]
排查你的lua脚本

**Comment by luyingwei80** [comment]
> 排查你的lua脚本

非常感谢您的提示，我已经找到了lua脚本的问题，服务器程序已经顺利的运行。
