### ISSUE TITLE
not enough random bot accounts available

### ISSUE THREAD

**Issue by boldoran** [liyunfan1223/mod-playerbots#374]
i have an error that reads:

Not enough random bot accounts available. Need 31 more!!
317 new bots
Not enough random bot accounts available. Need 31 more!!
317 new bots
Not enough random bot accounts available. Need 31 more!!
317 new bots
Not enough random bot accounts available. Need 31 more!!
317 new bots

i tried increasing the randombot accounts from 200 to 250 but that doesnt work, it keeps saying it doesnt have enough accounts.
i also should have more then 400 bots but it loads only 226 into the game.

what does this mean and what am i doing wrong?

thanks.

**Comment by boldoran** [comment]
> Can you upload your Playerbots.conf so I can check whats wrong there 
[playerbot.txt](https://github.com/user-attachments/files/16365616/playerbot.txt)

here you go!
 thanks again.

**Comment by boldoran** [comment]
> 58 new bots
> 520/577 Bot Hemin logged in
> Not enough random bot accounts available. Need 5 

it just wont spawn in enough bots/accounts... no idea its weird
 didnt have this before

**Comment by Mr-Deadbeat** [comment]
`# Random bot account
AiPlayerbot.RandomBotAccountCount = 250 <<<<<

# Random bot count
AiPlayerbot.MinRandomBots = 400
AiPlayerbot.MaxRandomBots = 800`

there is your problem you have too few accounts created so logically there are no more bots to spawn change RandomBotAccountCount to 800 and it will work

**Comment by boldoran** [comment]
> `# Random bot account AiPlayerbot.RandomBotAccountCount = 250 <<<<<
> 
> # Random bot count
> AiPlayerbot.MinRandomBots = 400 AiPlayerbot.MaxRandomBots = 800`
> 
> there is your problem you have too few accounts created so logically there are no more bots to spawn change RandomBotAccountCount to 800 and it will work


one accounts makes up to 40 bots, i have 520 out of 577 bots logged into the game at this point. so your solution is incorrect.
ive also tried to increase that and it did nothing.

**Comment by Grimfeather** [comment]
How often have you deleted all random bot accounts?
I don't see anything weird in the config file, so my next thought is that your database is corrupt/messed up.
not everything gets reset/deleted when AiPlayerbot.DeleteRandomBotAccounts = 0 is set to 1.

check your characters database. I'm guessing it has many thousands of entries.

**Comment by wangmz29** [comment]
AiPlayerbot.RotationPoolSize 设置大于800，或者AiPlayerbot.EnableRotation = 0试一下。

**Comment by christan-duplicate** [comment]
#282 
https://github.com/liyunfan1223/mod-playerbots/issues/282#issuecomment-2211737133

删除一下机器人相关的数据，重新运行吧

**Comment by boldoran** [comment]
> How often have you deleted all random bot accounts? I don't see anything weird in the config file, so my next thought is that your database is corrupt/messed up. not everything gets reset/deleted when AiPlayerbot.DeleteRandomBotAccounts = 0 is set to 1.
> 
> check your characters database. I'm guessing it has many thousands of entries.

i made sure i deleted the entrys and cleaned up the database :)

**Comment by boldoran** [comment]
> AiPlayerbot.RotationPoolSize 设置大于800

that worked, thanks!
