### ISSUE TITLE
Unable to use .playerbot bot after latest update 48ac024

### ISSUE THREAD

**Issue by poserbiker** [liyunfan1223/mod-playerbots#375]
**Describe the bug**
Unable to use ".playerbot bot ". 
When you type said command it just returns in the chat window with two "%s"
I disabled all addons and delete Cache folder 
Verified main azerothcore and playerbots are up-to-date
Recompiled from start

**Commit hash**
48ac024

**To Reproduce**
1. Log into the game
2. Enter .playerbot bot

**Expected behavior**
Should get a list of commands and should be able to execute said commands 

**Screenshots**
![image](https://github.com/user-attachments/assets/a376df80-be0d-47d9-802a-3a1525c61cf1)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS x86_64 
 - Kernel: 6.8.0-38-generic

**Comment by liyunfan1223** [comment]
Comfirm.
