### ISSUE TITLE
A bunch of compilation warnings

### ISSUE THREAD

**Issue by zhangbo8418** [liyunfan1223/mod-playerbots#376]
In file included from /azerothcore/modules/mod-playerbots/src/FleeManager.cpp:5:
/azerothcore/modules/mod-playerbots/src/FleeManager.h:49:40: warning: ‘maybe_unused’ attribute ignored [-Wattributes]
   49 |                 [[maybe_unused]] float followAngle; // unused - whipowill
      |                                        ^~~~~~~~~~~

/azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.cpp: In member function ‘const string PlayerbotAIConfig::GetTimestampStr()’:
/azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.cpp:408:29: warning: ‘%02d’ directive output may be truncated writing between 2 and 11 bytes into a region of size between 8 and 15 [-Wformat-truncation=]
  408 |     snprintf(buf, 20, "%04d-%02d-%02d %02d-%02d-%02d", aTm->tm_year + 1900, aTm->tm_mon + 1, aTm->tm_mday, aTm->tm_hour, aTm->tm_min, aTm->tm_sec);
      |                             ^~~~
/azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.cpp:408:23: note: directive argument in the range [-2147483647, 2147483647]
  408 |     snprintf(buf, 20, "%04d-%02d-%02d %02d-%02d-%02d", aTm->tm_year + 1900, aTm->tm_mon + 1, aTm->tm_mday, aTm->tm_hour, aTm->tm_min, aTm->tm_sec);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:894,
                 from /usr/include/c++/11/cstdio:42,
                 from /usr/include/c++/11/ext/string_conversions.h:43,
                 from /usr/include/c++/11/bits/basic_string.h:6608,
                 from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/bits/unique_ptr.h:42,
                 from /usr/include/c++/11/memory:76,
                 from /azerothcore/src/common/Common.h:23,
                 from /azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.h:8,
                 from /azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.cpp:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:35: note: ‘__builtin___snprintf_chk’ output between 20 and 72 bytes into a destination of size 20
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~

/azerothcore/modules/mod-playerbots/src/PlayerbotFactory.cpp: In member function ‘void PlayerbotFactory::EnchantItem(Item*)’:
/azerothcore/modules/mod-playerbots/src/PlayerbotFactory.cpp:1804:36: warning: iteration 3 invokes undefined behavior [-Waggressive-loop-optimizations]
 1804 |                 if (enchant->type[i] != ITEM_ENCHANTMENT_TYPE_STAT)
      |                     ~~~~~~~~~~~~~~~^
/azerothcore/modules/mod-playerbots/src/PlayerbotFactory.cpp:1802:45: note: within this loop
 1802 |             for (uint8 i = ITEM_MOD_MANA; i < MAX_ITEM_MOD; ++i)

/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp: In member function ‘uint32 RandomItemMgr::GetFood(uint32, uint32)’:
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2390:44: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2390 |             items = { 787, 117, 4540, 2680 };
      |                                            ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2392:47: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2392 |             items = { 2287, 4592, 4541, 21072 };
      |                                               ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2394:48: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2394 |             items = { 3770, 16170, 4542, 20074 };
      |                                                ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2396:46: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2396 |             items = { 4594, 3771, 1707, 4457 };
      |                                              ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2398:66: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2398 |             items = { 4599, 4601, 21552, 17222 /*21030, 16168 */ };
      |                                                                  ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2400:65: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2400 |             items = { 8950, 8952, 8957, 21023 /*21033, 21031 */ };
      |                                                                 ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2402:50: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2402 |             items = { 29292, 27859, 30458, 27662 };
      |                                                  ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2404:43: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2404 |             items = { 29450, 29451, 29452 };
      |                                           ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2406:29: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2406 |             items = { 35947 };
      |                             ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2412:32: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2412 |             items = { 159, 117 };
      |                                ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2414:35: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2414 |             items = { 1179, 21072 };
      |                                   ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2416:28: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2416 |             items = { 1205 };
      |                            ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2418:28: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2418 |             items = { 1708 };
      |                            ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2420:28: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2420 |             items = { 1645 };
      |                            ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2422:28: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2422 |             items = { 8766 };
      |                            ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2424:29: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2424 |             items = { 28399 };
      |                             ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2426:29: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2426 |             items = { 27860 };
      |                             ^
/azerothcore/modules/mod-playerbots/src/RandomItemMgr.cpp:2428:29: warning: assignment from temporary ‘initializer_list’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
 2428 |             items = { 33445 };
      |                             ^

In file included from /azerothcore/src/server/game/Entities/GameObject/GameObject.h:26,
                 from /azerothcore/src/server/game/Battlegrounds/Battleground.h:24,
                 from /azerothcore/src/server/game/Entities/Player/Player.h:22,
                 from /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:2:
In member function ‘ObjectGuid Object::GetGUID() const’,
    inlined from ‘bool PvPScript::CheckConditions(Player*, Player*)’ at /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:91:28,
    inlined from ‘virtual void PvPScript::OnPlayerKilledByCreature(Creature*, Player*)’ at /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:41:29:
/azerothcore/src/server/game/Entities/Object/Object.h:107:67: warning: ‘this’ pointer is null [-Wnonnull]
  107 |     [[nodiscard]] ObjectGuid GetGUID() const { return GetGuidValue(OBJECT_FIELD_GUID); }
      |                                                       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/azerothcore/src/server/game/Entities/Object/Object.h: In member function ‘virtual void PvPScript::OnPlayerKilledByCreature(Creature*, Player*)’:
/azerothcore/src/server/game/Entities/Object/Object.h:139:30: note: in a call to non-static member function ‘ObjectGuid Object::GetGuidValue(uint16) const’
  139 |     [[nodiscard]] ObjectGuid GetGuidValue(uint16 index) const;
      |                              ^~~~~~~~~~~~
In member function ‘bool PvPScript::CheckConditions(Player*, Player*)’,
    inlined from ‘virtual void PvPScript::OnPlayerKilledByCreature(Creature*, Player*)’ at /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:41:29:
/azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:95:39: warning: ‘this’ pointer is null [-Wnonnull]
   95 |         if (!killer->isHonorOrXPTarget(killed))
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:2:
/azerothcore/src/server/game/Entities/Player/Player.h: In member function ‘virtual void PvPScript::OnPlayerKilledByCreature(Creature*, Player*)’:
/azerothcore/src/server/game/Entities/Player/Player.h:2096:10: note: in a call to non-static member function ‘bool Player::isHonorOrXPTarget(Unit*) const’
 2096 |     bool isHonorOrXPTarget(Unit* victim) const;
      |          ^~~~~~~~~~~~~~~~~

**Comment by hermensbas** [comment]
we know

**Comment by hermensbas** [comment]
we are aware
