### ISSUE TITLE
请求修复战场

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#38]
机器人不会动。
请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场请求修复战场

**Comment by zbhcn** [comment]
Okay, I will provide timely feedback on various possible bugs

**Comment by rogerc66** [comment]
bots are moving now but their moment waypoint z-axis seems not correctly implemented, they are mounted and moving in mid-air or underground.
