### ISSUE TITLE
multi-threading race condition issues

### ISSUE THREAD

**Issue by zbhcn** [liyunfan1223/mod-playerbots#382]
When there is only one real player, the worldserver remains stable and does not crash, regardless of how many bots are teamed up with them. However, when the ThreadPool parameter is set to more than 2,or MapUpdate.Threads > 1 ,or when multiple real players are teamed up with bots, crashes become frequent. I believe there is a high likelihood of thread race conditions causing these frequent crashes. Therefore, I suggest checking the bot code for potential multi-threading race condition issues.

**Comment by zbhcn** [comment]
when MapUpdate.Threads set more than 1 ,then easy to cause crash

**Comment by liyunfan1223** [comment]
Missing crash log. Knowing only that it's multi-threaded doesn't help in solving the problem.
