### ISSUE TITLE
Bots in Alterac Valley with disabled movelinepaths in Battlegrounds will phase into capture point flags and become unattackable due to LOS.

### ISSUE THREAD

**Issue by Thatharis** [liyunfan1223/mod-playerbots#387]
**Describe the bug**
Bots in Alterac Valley with disabled movelinepaths in Battlegrounds will phase into capture point flags and become unattackable due to LOS. This happens by them standing directly inside of the flag and since the player can't get phase through world objects like that, they cannot be damaged by regular players.

Commit ec04b28

**Comment by noisiver** [comment]
This happens to me with the default value (not disabled).

**Comment by Dreathean** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/422 resolved this issue
