### ISSUE TITLE
BG's show "{}" for bases in chat

### ISSUE THREAD

**Issue by poserbiker** [liyunfan1223/mod-playerbots#390]
**Describe the bug**
Seeing "{}" in text for bases and faction in BG's, possibly other places but this is what I observed so far

**Commit hash**
8816758

**To Reproduce**
1. Log in, join a LFG
2. When a base is under attack it will produce a "{}" for the base and faction

**Expected behavior**
Should show the base name 

**Screenshots**
![image](https://github.com/user-attachments/assets/b942dac3-c9cf-45e0-bacb-2c67a119c07c)
![image](https://github.com/user-attachments/assets/decf1a63-f1a3-4979-a6bc-f5ba919135a8)
![image](https://github.com/user-attachments/assets/af53f0cf-a2e9-44d5-af63-26e47c8eb375)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 23H2 (OS Build 22631.3880

**Comment by fuzzdeveloper** [comment]
This was a bug with the core (nothing to do with playerbots), it was introduced recently, and fixed shortly after in this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/19486
