### ISSUE TITLE
Bots wont be stunned while walking

### ISSUE THREAD

**Issue by boldoran** [liyunfan1223/mod-playerbots#394]
bots will not get stunned while walking. when charged, kidney shotted etcetra, the bots will continue to move.

the bots when charged or stunned otherwise will show the "stunned" animation, but will continue to move.
slowing does work, but stunning/charging them while walking will result in them moving off.

tested this behavior in BG's and in the overworld

**Comment by fuzzdeveloper** [comment]
This is a known issue and you can stop it by setting AiPlayerbot.DisableMoveSplinePath to 1 (fixes it in BG only) or 2 (fixes everywhere). Note that it will have the side-effect of making bot movement a bit more glitchy (with bots sometimes flying through air or going underground) though this is less of an issue than it used to be.

**Comment by boldoran** [comment]
ill give that a shot, thanks!

**Comment by fuzzdeveloper** [comment]
FYI @liyunfan1223 you can fix this without making your own movement generator if you make this change to EscortMovementGenerator.cpp in the core (the selected code):
![image](https://github.com/user-attachments/assets/ffdf7055-bb5b-40ad-845a-98c36f05ac37)

Obviously this would effect other usages of EscortMovementGenerator (though with the IsPlayer() check, I'm sure it'd be quite limited). Up to you if you want to go this direction.

If you do fix this please dont remove AiPlayerbot.DisableMoveSplinePath option - it's very useful for finding waypoint/path issues in battlegrounds :-)

**Comment by liyunfan1223** [comment]
Fixed.
