### ISSUE TITLE
Compile errors...7/28/24 from "master branch"

### ISSUE THREAD

**Issue by Stady234** [liyunfan1223/mod-playerbots#399]
[  0%] Building C object deps/argon2/CMakeFiles/argon2.dir/argon2/opt.c.o
In file included from /root/azerothcore-wotlk/deps/argon2/argon2/opt.c:26:
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:64:22: error: unknown type name '__m128i'
static BLAKE2_INLINE __m128i fBlaMka(__m128i x, __m128i y) {
                     ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:64:38: error: unknown type name '__m128i'
static BLAKE2_INLINE __m128i fBlaMka(__m128i x, __m128i y) {
                                     ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:64:49: error: unknown type name '__m128i'
static BLAKE2_INLINE __m128i fBlaMka(__m128i x, __m128i y) {
                                                ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:65:11: error: unknown type name '__m128i'
    const __m128i z = _mm_mul_epu32(x, y);
          ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:110:24: error: unknown type name '__m128i'
static void fill_block(__m128i *state, const block *ref_block,
                       ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:112:5: error: use of undeclared identifier '__m128i'
    __m128i block_XY[ARGON2_OWORDS_IN_BLOCK];
    ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:118:50: error: unknown type name '__m128i'
                state[i], _mm_loadu_si128((const __m128i *)ref_block->v + i));
                                                 ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:119:13: error: use of undeclared identifier 'block_XY'
            block_XY[i] = _mm_xor_si128(
            ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:120:50: error: unknown type name '__m128i'
                state[i], _mm_loadu_si128((const __m128i *)next_block->v + i));
                                                 ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:124:13: error: use of undeclared identifier 'block_XY'
            block_XY[i] = state[i] = _mm_xor_si128(
            ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:125:50: error: unknown type name '__m128i'
                state[i], _mm_loadu_si128((const __m128i *)ref_block->v + i));
                                                 ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier '__m128i'
        BLAKE2_ROUND(state[8 * i + 0], state[8 * i + 1], state[8 * i + 2],
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:148:9: note: expanded from macro 'DIAGONALIZE'
        __m128i t0 = D0;                                                       \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier '__m128i'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:149:9: note: expanded from macro 'DIAGONALIZE'
        __m128i t1 = B0;                                                       \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier 't0'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:153:56: note: expanded from macro 'DIAGONALIZE'
        D0 = _mm_unpackhi_epi64(D1, _mm_unpacklo_epi64(t0, t0));               \
                                                       ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier 't0'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:153:60: note: expanded from macro 'DIAGONALIZE'
        D0 = _mm_unpackhi_epi64(D1, _mm_unpacklo_epi64(t0, t0));               \
                                                           ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier 't0'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:154:33: note: expanded from macro 'DIAGONALIZE'
        D1 = _mm_unpackhi_epi64(t0, _mm_unpacklo_epi64(D1, D1));               \
                                ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier 't1'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:156:56: note: expanded from macro 'DIAGONALIZE'
        B1 = _mm_unpackhi_epi64(B1, _mm_unpacklo_epi64(t1, t1));               \
                                                       ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier 't1'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:179:9: note: expanded from macro 'BLAKE2_ROUND'
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:156:60: note: expanded from macro 'DIAGONALIZE'
        B1 = _mm_unpackhi_epi64(B1, _mm_unpacklo_epi64(t1, t1));               \
                                                           ^
/root/azerothcore-wotlk/deps/argon2/argon2/opt.c:130:9: error: use of undeclared identifier '__m128i'
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:184:9: note: expanded from macro 'BLAKE2_ROUND'
        UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                         \
        ^
/root/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:161:9: note: expanded from macro 'UNDIAGONALIZE'
        __m128i t0, t1;                                                        \
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
gmake[2]: *** [deps/argon2/CMakeFiles/argon2.dir/build.make:132: deps/argon2/CMakeFiles/argon2.dir/argon2/opt.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Any.cpp.o
[

**Comment by Grimfeather** [comment]
Installation
Please note that this module requires specific custom changes to AzerothCore. To ensure compatibility, you must compile it with a custom branch from my fork, which can be found here: [liyunfan1223/azerothcore-wotlk/tree/Playerbot](https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot).

**Comment by Stady234** [comment]
That is the fork i used.  I was able to redownload everything and make a copy of the config folder since it clones into a subfolder (dist) under config and the compiler cant find the config files.  Anyway, i got it figured out and i have a working server.
