### ISSUE TITLE
playerbot mod 编译时有很多错误无法通过

### ISSUE THREAD

**Issue by alexpec1** [liyunfan1223/mod-playerbots#40]
Before I put your module into someone else's kernel, compilation will prompt a lot of errors can not pass, and then I put down your own kernel, not yet put the playbot module, compile the kernel prompted a number of errors, the compilation is unsuccessful, can you help me to see what is going on? The errors are as follows:
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\PvpValues.cpp(132,19): error C2664: “ReputationRank Unit::GetFactionReactionTo(const FactionTemplateEntry *,const Unit *) const”: It is not possible to set the parameter2 从“const FactionTemplateEntry *”convert to“const Unit *”
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\PvpValues.cpp(132,72): message : Points to an unrelated type; conversion requires reinterpret_cast、C Style-forced conversions or style-forced conversions of functions with parentheses
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1512,20): message : confer (cf.)“Unit::GetFactionReactionTo”(compiling the source file D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\PvpValues.cpp)
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\PvpValues.cpp(132,19): message : Try to match the parameter list“(const FactionTemplateEntry *, const FactionTemplateEntry *)”hour
22>SnareTargetValue.cpp
21>boss_emperor_dagran_thaurissan.cpp
21>boss_eviscerator.cpp
21>boss_general_angerforge.cpp
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\RtiTargetValue.cpp(44,30): error C2039: "GetTargetIcon": fault "Group" members
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Player\Player.h(59,7): message : See the declaration of "Group".
22>SpellCastUsefulValue.cpp
22>SpellIdValue.cpp
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(166,12): error C2664: “ReputationRank Unit::GetFactionReactionTo(const FactionTemplateEntry *,const Unit *) const”: Unable to convert parameter 2 from "const T *" to "const Unit *".
22>        with
22>        [
22>            T=FactionTemplateEntry
22>        ]
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(166,100): message : Unrelated; conversion requires reinterpret_cast, C-style forced conversion, or parenthesized function-style forced conversion.
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1512,20): message : See the declaration of "Unit::GetFactionReactionTo" (compiled source file D).:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp)
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(166,12): message : When trying to match the parameter list "(const FactionTemplateEntry *, const T *)"
22>        with
22>        [
22>            T=FactionTemplateEntry
22>        ]
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(219,22): error C2664: “ReputationRank Unit::GetFactionReactionTo(const FactionTemplateEntry *,const Unit *) const”: 无法将参数 2 从“const T *”转换为“const Unit *”
22>        with
22>        [
22>            T=FactionTemplateEntry
22>        ]
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(219,110): message : Unrelated; conversion requires reinterpret_cast, C-style forced conversion, or parenthesized function-style forced conversion.
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.h(1512,20): message : See the declaration of "Unit::GetFactionReactionTo" (compiled source).D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp)
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\QuestValues.cpp(219,22): message : When trying to match the parameter list "(const FactionTemplateEntry *, const T *)"
22>        with
22>        [
22>            T=FactionTemplateEntry
22>        ]

22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\TargetValue.cpp(55,50): error C2039: "GetTargetIcon": Not a member of "Group"
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Player\Player.h(59,7): message : See the declaration of "Group".
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\strategy\values\TargetValue.cpp(62,38): error C2039: "GetTargetIcon": Not a member of "Group"
22>D:\eryuwow\yunfan_Core\azerothcore-wotlk\src\server\game\Entities\Player\Player.h(59,7): message : See the declaration of "Group".

**Comment by brian8544** [comment]
Same, using https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot branch for compilation

**Comment by alexpec1** [comment]
The error I got above was in VS when I compiled using the branch you mentioned, did you compile it correctly?

**Comment by brian8544** [comment]
Sorry for my vague previous reply. No, I get the same problems as you 😄

**Comment by alexpec1** [comment]
fellow sufferers empathize with each other (idiom); misery loves company，Let me know when you've solved it.

**Comment by alexpec1** [comment]
After I recompiled in the branch, I got 2 more errors:

4>WheatyExceptionReport.cpp 22>D:\eryuwow\Yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\PlayerbotAIConfig.cpp(592,36). error C2398: Element "1": conversion from "int" to "_Ty" requires contraction 22> with 22> [ 22> _Ty= uint32 22> ] 22>D:\eryuwow\Yunfan_Core\azerothcore-wotlk\modules\mod-playerbots\src\PlayerbotAIConfig.cpp(592,83): error C2398: Element "4": Conversion from "int" to "_Ty" requires contraction 22> with 22> [ 22> _Ty=uint32 22> ]

I don't know what's wrong because I don't know C++, so I don't know what's wrong.
The error jumps to these lines of code:

 for (int tab = 0; tab < 3; tab++) {
     if (tab_links.size() <= tab) {
         break;
     }
     std::sort(spells[tab].begin(), spells[tab].end(), [&](TalentEntry const* lhs, TalentEntry const* rhs) {
         return lhs->Row != rhs->Row ? lhs->Row < rhs->Row : lhs->Col < rhs->Col;
     });
     for (int i = 0; i < tab_links[tab].size(); i++) {
         if (i >= spells[tab].size()) {
             break;
         }
         int lvl = tab_links[tab][i] - '0';
         if (lvl == 0) continue;
         orders[tab].push_back({tab, spells[tab][i]->Row, spells[tab][i]->Col, lvl});

**Comment by conan513** [comment]
No compile error here on arch linux but the server crash after a few second if a bot join into the server.
Segment fault

**Comment by alexpec1** [comment]
I was compiled under WINDOWS, and then I changed zhengpeiru's core and then compiled, compiled successfully, and now also open the random robot, into the normal play, the server will not crash, only to start the worldserver there are a lot of lines of red, I looked at what seems to be related to the NPCBots do not have a database, but I will not be able to combine the two! together.

**Comment by alexpec1** [comment]
This problem has now been fixed, last night after re-git compilation can be passed, hard work author, I hope the optimisation is getting better and better, the AI robot is getting smarter and smarter.
