### ISSUE TITLE
Unable to compile anymore with Auctionator module

### ISSUE THREAD

**Issue by cjfrick13** [liyunfan1223/mod-playerbots#408]
**Describe the bug**
Unable to compile Azerothcore with playbots module in the last couple of weeks. Using latest commit of playerbots fork of Azerothcore as well as playerbots module and Auctionator module. Auctionator has not made any changes in the last two months. I have various other modules installed as well, but Microsoft Visual Studio is able to compile with no issues with every other module added except when i enable Auctionator. The moment I enable Auctionator, Visual Studio fails to compile.

**Commit hash**

mod-playerbots: 7c3f56c8f9ebf1a78886b0b490820eafac0eb5bd

azerothcore-wotlk: f7ad415b3ff9efdcf7418306ebeb907d352a9be6

Auctionator: aa411c94210e47823b490d8051b752757069892a

**To Reproduce**
Add latest commit of Auctionator module
Attempt to compile on Windows with CMake and Visual Studio
Visual Studio fails with two errors and four warnings.

**Expected behavior**
Visual Studio to successfully compile and be able to run latest commits of Azerothcore with playbots and various other modules like Auctionator.

**Screenshots**
![ACCompileErrors](https://github.com/user-attachments/assets/1531beed-9cfe-4a41-962f-242798cad1fe)
![ACErrors](https://github.com/user-attachments/assets/b855fcb9-9471-4d1c-af31-b99ea83030a5)

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - Browser: Edge
 - Version 127.0.2651.74

**Additional context**
Not sure if the Auctionator module needs to be updated or if some commit to Azerothcore, the playerbots fork of Azerothcore, or the playerbots module in itself is causing some type of confliction that is causing this. Have been trying for the last couple of weeks with all the latest commits of everything to see if it has been fixed yet to no avail.

**Comment by Dreathean** [comment]
If Auctionator hasn't been updated in the last 2 months, the issues lies between it and the core, not Playerbots. AC had several updates recently that most modules had to update to work with. Try compiling a default server, non-playerbots, with auctionator and see if that works?

**Comment by cjfrick13** [comment]
Thank you for the information. I was wondering if Azerothcore's various updates may have caused the issue. I did confirm with compiling Auctionator with original Azerothcore still causes compiling errors. At this point I am convinced that Auctionator needs to be updated. I submitted an issue on Auctionator's github repo to hopefully get it fixed.

**Comment by Dreathean** [comment]
Closed as issue is with Auctionator and core, not playerbots
