### ISSUE TITLE
This robot has been standing in this position for almost an hour, and even at level 2, it has an epic sword

### ISSUE THREAD

**Issue by christan-duplicate** [liyunfan1223/mod-playerbots#412]
![image](https://github.com/user-attachments/assets/0fad4325-15ad-4a3a-9740-8c124f0e33ad)

This robot has been standing in this position for almost an hour, and even at level 2, it has an epic sword

**Comment by Dreathean** [comment]
Their random item selection will include changed items and anything within their level range, so if that weapon doesn't have any level restrictions, which it doesn't seem to, it is a valid option for the bot.

**Comment by christan-duplicate** [comment]
> Their random item selection will include changed items and anything within their level range, so if that weapon doesn't have any level restrictions, which it doesn't seem to, it is a valid option for the bot.

But this robot has been standing here for a long time, and it's not just this one; many robots are standing there motionless.

**Comment by Dreathean** [comment]
Yeah that is definitely a bug, sorry I don't have an answer for that, was just commenting on the sword part. Hopefully the logic can be fixed but it is a complex issue.

**Comment by liyunfan1223** [comment]
Confirmed this is a movement related issue, which usually occurs when they target a mob with uneven paths.

**Comment by liyunfan1223** [comment]
I have no idea with this sword. It looks like some customized modifications to items caused this.
