### ISSUE TITLE
There is no AiPlayerbot.RandomBotGuildTalk in the configuration file

### ISSUE THREAD

**Issue by christan-duplicate** [liyunfan1223/mod-playerbots#414]
![image](https://github.com/user-attachments/assets/5836b14c-25b1-4f38-ab99-8213a6c612c4)
There is no `AiPlayerbot.RandomBotGuildTalk` in the configuration file

**Comment by Dreathean** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/415 fixed here
