### ISSUE TITLE
Guilds have not been Generated

### ISSUE THREAD

**Issue by Hynisel** [liyunfan1223/mod-playerbots#417]
**Describe the bug**
Guilds have not been generated.

**Commit hash**
[30a25ba]

**To Reproduce**
Generate bots for the first time.

**Expected behavior**
Expect the bots to create and join guilds.

**Screenshots**
![WoWScrnShot_073024_160258](https://github.com/user-attachments/assets/b1e0e70f-ed56-4447-8853-c69c1334b5bb)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 127.0.6533.73

**Additional context**
Guilds have not been generate, is there any solution to that? Thx.

**Comment by atidot3** [comment]
guild are disable by defaut.
You may need to add +guild to the strategies in your cfg

**Comment by Hynisel** [comment]
> guild are disable by defaut.
> You may need to add +guild to the strategies in your cfg

Thank you for replying. Could you please give me more details on how to do that?

**Comment by atidot3** [comment]
In:
AiPlayerbot.RandomBotCombatStrategies = "+some stuff, -some stuff"

append at the end +guild

**Comment by Hynisel** [comment]
> In:
> AiPlayerbot.RandomBotCombatStrategies = "+some stuff, -some stuff"
> 
> append at the end +guild

Thank you, I have tried but it did not work. Does it work if the bots have already been generated or only if modified before generating them?

**Comment by mtm84** [comment]
I believe +guild should go into AiPlayerbot.RandomBotNonCombatStrategies but it might actually be better to be in both.  It will not create guilds as such, but it will allow bots to start guild petitions and ask for signatures for said guilds.  This is a long process currently, but it does start the process of bots forming guilds in game.

**Comment by Hynisel** [comment]
> I believe +guild should go into AiPlayerbot.RandomBotNonCombatStrategies but it might actually be better to be in both. It will not create guilds as such, but it will allow bots to start guild petitions and ask for signatures for said guilds. This is a long process currently, but it does start the process of bots forming guilds in game.

Thank you. I have applied the necessary changes and will observe if new guilds will be create, in case not, I will update this issue.

![Conf Playerbots](https://github.com/user-attachments/assets/8ddc402e-6c70-42c8-ad15-6882b167187f)

**Comment by Hynisel** [comment]
Hello, after running it for a couple days with the new settings, no new guild has been formed, some bots talk about wanting to join a guild (In the various channels) but it does not happen. Is there anything else that I should check?

Thx.

**Comment by mtm84** [comment]
I did notice this behavior previously where after checking the SQL database, a ton of guild petitions had been made, but virtually non of them had any signatures.  However, as of a recent PR (yesterday I think?), the number of signatures skyrocketed.  If you haven't updated in a bit try that and see if guilds start forming. 1000 bots should be plenty for guilds to start forming.  What are your conf settings for AiPlayerbot.RandomBotGuildCount and AiPlayerbot.DeleteRandomBotGuilds ?

**Comment by Hynisel** [comment]
I did update quite recently, like a week ago, but if it helps I can do it again. My settings are the following (default):

# Random bot guild count
AiPlayerbot.RandomBotGuildCount = 20

# Delete all random bot guilds
AiPlayerbot.DeleteRandomBotGuilds = 0
