### ISSUE TITLE
Issue with WizardOil

### ISSUE THREAD

**Issue by poserbiker** [liyunfan1223/mod-playerbots#428]
**Describe the bug**
I had been getting crashes when starting the server and adding bots, even when deleting all bots and re-adding them it seemed like right after they were added i would get a "Segmentation fault". 

After gathering info from gdb i finally was able to find out it was something to do with the WizardOil, In one of my tests i removed anything to do with the wizard oil being applied and it seems to be stable. I've been running it without the WizardOil params and no crashes. Not sure if this is a me issue.

PlayerbotAI::FindOilFor (this=0x7fff6b7ea000, weapon=weapon@entry=0x7fff6b7dd300)
    at /azerothcore-wotlk-no-change/modules/mod-playerbots/src/PlayerbotAI.cpp:4237
4237                oil = FindConsumable(uPriorizedWizardOilIds[i]);

**Commit hash**
966cc1b

**To Reproduce**
1. Start server
2. Wait for bots to load
3. Segmentation fault

**Expected behavior**
n/a

**Screenshots**
![image](https://github.com/user-attachments/assets/f3427e12-b0be-49ca-8966-521c8ef25066)

**Desktop (please complete the following information):**
 - OS: OS: Ubuntu 24.04 LTS x86_64
 - Kernel: 6.8.0-39-generic

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/445
