### ISSUE TITLE
AiPlayerbot.RandomGearQualityLimit config option doesn't work

### ISSUE THREAD

**Issue by entropiccode** [liyunfan1223/mod-playerbots#429]
**Describe the bug**
AiPlayerbot.RandomGearQualityLimit is non-functional. I currently have it set to 2 (uncommon), but bots are still running around with rares as soon as they hit level 14.

**Commit hash**
78cdc11ba507e35dd18412ca80aa502306591c97

**Comment by entropiccode** [comment]
After some further digging, it looks like most of the rares the bots are running around with were common/uncommon at some point in time, but were upgraded to rare later. I'm not certain where they're getting this data however as I haven't made any modifications to item rarity at all.

**Comment by entropiccode** [comment]
Did some further testing, set the gear quality limit to 1 (common only), and the bots were still getting uncommons around level 5 or so, far more than happening to find greens on mob kills and too low to be rewards from quests.

The option is definitely broken in some fashion, I'm not clear on if its because the item cache being built is not referencing the actual item DB, or if the option just isn't checked when giving bots gear.

**Comment by liyunfan1223** [comment]
Comfirmed. They upgrade their gear when levelup, and the gear quality is hard-coded as rare. https://github.com/liyunfan1223/mod-playerbots/blob/16887eb33cb73d46b8af12ccf1589e9ecf659c65/src/strategy/actions/AutoLearnSpellAction.cpp#L213

Thanks for the report, it will be fixed later.

**Comment by liyunfan1223** [comment]
Fixed in https://github.com/liyunfan1223/mod-playerbots/pull/448

**Comment by entropiccode** [comment]
> Fixed in #448

This has stopped the bots from getting rare items regardless of config, but the config itself still seems to be broken. I set AiPlayerbot.RandomGearQualityLimit back to 2 (my desired setting), reset the bots and had them start leveling again.

The bots are now reaching level 11, and are equipped in full gray/white gear. Previously, the bots would start getting uncommon items around level 5, now none of them have anything rarer than a common item.

Possible config options of note:
```
AiPlayerbot.KillXPRate = 5

AiPlayerbot.DisableRandomLevels = 1
AiPlayerbot.RandombotStartingLevel = 8

AiPlayerbot.RandomGearQualityLimit = 2
AiPlayerbot.RandomGearScoreLimit = 0
AiPlayerbot.LimitGearExpansion = 60
AiPlayerbot.RandomGearLoweringChance = 0
AiPlayerbot.EquipmentPersistence = 1
AiPlayerbot.EquipmentPersistenceLevel = 18
AiPlayerbot.AutoUpgradeEquip = 1

AiPlayerbot.RandomBotNonCombatStrategies = "+grind,+loot,+custom::say,+guild"

AiPlayerbot.ProbTeleToBankers = 0
```

**Comment by liyunfan1223** [comment]
Oh i made a mistake. Now it should work https://github.com/liyunfan1223/mod-playerbots/pull/450. Use init/refresh command in console to give them start equip.

**Comment by entropiccode** [comment]
After re-initializing bots everything seems to be working as intended.
