### ISSUE TITLE
Bots arn't moving or accepting/declining invites

### ISSUE THREAD

**Issue by stevenbruy** [liyunfan1223/mod-playerbots#43]
After getting the compiling done i could log on and see bots. but none of the bots are moving or accepting/declining invites or duels. bg's can also not be played ( checked if enough 80's where on on both sides). I also checked the config and everything seems in order (played before with playerbots from celguars project).  is there something i need to do extra to get them to"activate"? I dont know if i should place all these questions in issues or if there is a beter place?

edit: it does work with a char from my own account

**Comment by Grakazela** [comment]
after applying todays updates I also have this issue. was working for the most part using a version from ~2 weeks ago

**Comment by alexpec1** [comment]
Right, I updated the latest one and it's also random bots standing motionless in the newbie village.

**Comment by liyunfan1223** [comment]
Introduced the bug by mistake :(, fixed in https://github.com/liyunfan1223/mod-playerbots/commit/844a0e36d2fead4a0d12f95a9b358fc99eda7943
