### ISSUE TITLE
Server crash - Wrong placed table

### ISSUE THREAD

**Issue by BenWagner-UX** [liyunfan1223/mod-playerbots#436]
```
Initializing arena teams...
[1146] Table 'acore_characters.playerbots_arena_team_names' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

#----------------------------------------------------------------------#
```

Still don't get it why playerbot database tables are placed in azerothcores character database.

**Comment by icemansparks** [comment]
I have similar errors. Is there any way to resolve them easily? 
`1146] Table 'acore_characters_playerbots.dungeonrespawn_playerinfo' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.`

**Comment by liyunfan1223** [comment]
Try running a clean database without manually modifying it.
