### ISSUE TITLE
leveling with bots in LFG not taking role/talents

### ISSUE THREAD

**Issue by Grakazela** [liyunfan1223/mod-playerbots#44]
while leveling 1-80, bots dont seem to want to swap to the talent role I tell them to, or select the appropriate role for lfg.
when whispered they will return the correct build, but when inspected the do not, and still que dps instead of tank

**Comment by liyunfan1223** [comment]
The responsibilities of lfg depend on the bot's strategy. Can you give specific steps to reproduce the situation you mentioned?

**Comment by Grakazela** [comment]
Invite a bot that is a tank class. Whisper it .talents [pve tank spec name] it says it takes it. Queue for lfg. Tank class will sometimes take dps/heal instead of tank. Also inspecting it they dont seem to like taking the talents
Ie warrior that says it has pve port talents when inspected is 30 points into arms

**Comment by Dreathean** [comment]
What exactly is the talent command? I tried using .talents holy for a priest and it says the command doesn't exist

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/1d21feb1ea15fc45dee62efb1302e0ad7630429f

Now you can use the command to specify the talents of the bot. You can check the usage by chatting with the bot 'talents'.
You need to update the configuration file and overwrite the original configuration file with the new playerbots.conf.dist.
