### ISSUE TITLE
Potential Out-of-Bounds Access in FindOilFor Function

### ISSUE THREAD

**Issue by LUX-YU** [liyunfan1223/mod-playerbots#441]
**Describe the bug**
In the function Item* PlayerbotAI::FindOilFor(Item* weapon) const, there is a potential out-of-bounds access that could lead to undefined behavior and potentially cause a crash.

In the first loop, if i == 4 and oil has not been found, the statement oil = FindConsumable(uPriorizedWizardOilIds[i]); will cause an out-of-bounds access, leading to undefined behavior and potentially causing a crash.

**Commit hash**
87640727a2c956a52e61e94f20730fa77c24f01b

**To Reproduce**
Ensure that the uPriorizedWizardOilIds array has fewer than 5 elements.
Ensure that no oil is found within the first 4 iterations of the loop.
Observe the out-of-bounds access in the loop when i equals 4.

**Expected behavior**
The function should correctly handle the boundary conditions without causing an out-of-bounds access.

**Desktop (please complete the following information):**
Platform not related.

**Proposed Fix**
```cpp
Item* PlayerbotAI::FindOilFor(Item* weapon) const
{
    Item* oil = nullptr;
    ItemTemplate const* pProto = weapon->GetTemplate();
    static constexpr auto num_of_wizard_oil = std::size(uPriorizedWizardOilIds);
    static constexpr auto num_of_mana_oil   = std::size(uPriorizedManaOilIds);
    if (pProto && (pProto->SubClass == ITEM_SUBCLASS_WEAPON_SWORD || pProto->SubClass == ITEM_SUBCLASS_WEAPON_STAFF ||
                   pProto->SubClass == ITEM_SUBCLASS_WEAPON_DAGGER))
    {
        for (uint8 i = 0; i < num_of_wizard_oil; i++)
        {
            oil = FindConsumable(uPriorizedWizardOilIds[i]);

            if (oil)
                return oil;
        }

        for(uint8 i = 0; i < num_of_mana_oil; i++)
        {
            oil = FindConsumable(uPriorizedManaOilIds[i]);

            if (oil)
                return oil;
        }
    }
    else if (pProto &&
             (pProto->SubClass == ITEM_SUBCLASS_WEAPON_MACE || pProto->SubClass == ITEM_SUBCLASS_WEAPON_MACE2))
    {
        for(uint8 i = 0; i < num_of_mana_oil; i++)
        {
            oil = FindConsumable(uPriorizedManaOilIds[i]);

            if (oil)
                return oil;
        }

        for (uint8 i = 0; i < num_of_wizard_oil; i++)
        {
            oil = FindConsumable(uPriorizedWizardOilIds[i]);

            if (oil)
                return oil;
        }
    }

    return oil;
}
```

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/445
