### ISSUE TITLE
Horde bots will get stuck on path outside Horde base when carrying flag in WSG

### ISSUE THREAD

**Issue by entropiccode** [liyunfan1223/mod-playerbots#442]
**Describe the bug**
Horde bots will pause on slope outside Horde base when carrying flag. This leads to extremely disproportionate number of Alliance victories.
![botbgstats](https://github.com/user-attachments/assets/7727901d-b47a-41de-8d22-46da6912650b)

**Commit hash**
78cdc11ba507e35dd18412ca80aa502306591c97

**To Reproduce**
1. Join Warsong Gulch match.
2. Have Horde bot pick up Alliance flag
3. Escort them back to Horde base, watch to see if they go in tunnel or up side path
3a. If they go up side path, observe flag carrier bot getting stuck.

**Expected behavior**
Bot will navigate up path without issue.

**Screenshots**
![WoWScrnShot_080524_123903](https://github.com/user-attachments/assets/cbe51320-7bc0-4198-9d48-684f767b4b7e)

**Additional context**
AiPlayerbot.MaxMovementSearchTime has been increased from the default of 3 to 5 with no change in this behavior.

**Comment by entropiccode** [comment]
May be worth noting that AiPlayerbot.DisableMoveSplinePath is set to 1

**Comment by fuzzdeveloper** [comment]
Nicely reported (I like the BG's stats you included), easily fixed too... Going to bundle this up with another WSG fix but if you just cant wait the branch is here: https://github.com/fuzzdeveloper/mod-playerbots/tree/wsg-fixes

Let me know if you know of any other pathing issues in WSG I can fix (while I've got the method for it full of additional logging).

**Comment by entropiccode** [comment]
My server is level capped at level 19 so I've been playing a lot of WSG, this seems to be the only major pathing issue I've found, other than bots scaling some impossible slopes, however I've seen players pull off the same thing in classic/retail so its not something I'm too bothered by.

**Comment by entropiccode** [comment]
> Nicely reported (I like the BG's stats you included), easily fixed too... Going to bundle this up with another WSG fix but if you just cant wait the branch is here: https://github.com/fuzzdeveloper/mod-playerbots/tree/wsg-fixes
> 
> Let me know if you know of any other pathing issues in WSG I can fix (while I've got the method for it full of additional logging).

This fix works like a charm, thank you.

**Comment by fuzzdeveloper** [comment]
> the only major pathing issue I've found other than bots scaling some impossible slopes
Yeah that's the tradeoff with AiPlayerbot.DisableMoveSplinePath setting, with it set to 0 the bots (mostly) don't make unrealistic movements, but if the path/waypoint they navigating asks the bot to make an unrealistic movement (or make a movement to a waypoint too far away for bot to calculate a path to) the bot simply wont move at all (and if the objective/path selection code doesn't select a different objective/path next time the bot might be stuck there indefinitely).

With AiPlayerbot.DisableMoveSplinePath > 0 the failure mode is unrealistic movement, where the bot will clip though objects and/or float in midair instead - its up to you which is a worse outcome (the combined improvements made to BG paths/waypoints and the code which selects paths for given destination have educed the occurrence of both failure modes significantly).

**Comment by fuzzdeveloper** [comment]
Fixed in https://github.com/liyunfan1223/mod-playerbots/pull/447
