### ISSUE TITLE
Bots doesnt join Alterac Valley as they did before.

### ISSUE THREAD

**Issue by rogerc66** [liyunfan1223/mod-playerbots#443]
**Describe the bug**
Bots doesnt line up Alterac Valley as they did before, I'm not sure it's a bug or purposely designed.

**Commit hash**
Latest revision.

**To Reproduce**
1. log in
2. queue for AV battleground.

**Expected behavior**
Bots should queue for BG as player does.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Linux 22.04
 - Browser [Chrome]

**Additional context**
None.

**Comment by fuzzdeveloper** [comment]
Just tried this myself (definitely on latest commit) and it works fine, are certain that sure NO bots are queuing? You can see whether anyone queues up by looking for messages like this:
![image](https://github.com/user-attachments/assets/c74bfb57-d689-4091-b3f7-ee1cb3c3f488)
Reason I bring that up is that it's possible (depending on number and distribution of bots in your server) that there's not enough bots of your level bracket to get an AV game going (if you use the command `playerbot rndbot stats` in console you can see a level breakdown of bots on your server)

**Comment by rogerc66** [comment]
![Screenshot 2024-08-06 at 10 26 21 PM](https://github.com/user-attachments/assets/b9de118f-8c93-4cfd-9ede-2f007e8eb0e8)
![Screenshot 2024-08-06 at 10 27 23 PM](https://github.com/user-attachments/assets/309e28e5-9f16-4d19-a441-31d0714c9ea3)
looks there is no bots queues after Checking BG queue on my server

**Comment by fuzzdeveloper** [comment]
Those settings are related to bots queuing _without_ players, you don't need those to have an AV game, `AiPlaybot.RandomBotJoinBG = 1` (the first setting in your pic) should be enough.

Those population numbers look like they _could_ be an issue, you need 40 per faction to fill an AV game, not sure how many needed to start but you definitely dont have 40 per faction in *any* bracket. I'd up bot count (or set min-max bot levels closer to your own level and reroll them with `playerbot rndbot init`) and see if that resolves it.

**Comment by rogerc66** [comment]
I have increased bot number to 900+ and now both fraction has 70+ bots each bracket, but no luck, I will pull a clean version of code and test again, will get back later

**Comment by fuzzdeveloper** [comment]
Did you try `AiPlayerbot.RandomBotAutoJoinBG = 0` like I said?

**Comment by rogerc66** [comment]
> Did you try `AiPlayerbot.RandomBotAutoJoinBG = 0` like I said?

Yes, I found out why it was not working, I have npcbot integrated and mod-solo-lfg, I have disabled npcbot join bg and disabled mod-solo-lfg, now playerbot start to queue bg, before, my npcbot can join bg with playerbot together, now they seems repell each other, I wonder how to make them both join bg without conflict.

**Comment by rogerc66** [comment]
> > Those settings are related to bots queuing _without_ players, you don't need those to have an AV game, `AiPlaybot.RandomBotJoinBG = 1` (the first setting in your pic) should be enough.
> > Those population numbers look like they _could_ be an issue, you need 40 per faction to fill an AV game, not sure how many needed to start but you definitely don't have 40 bots per faction in _any_ bracket. I'd increase the bot count (or set min-max bot levels closer to your own level and reroll them with `playerbot rndbot init`) and see if that resolves it.
> > [edit] Actually, taking another look at your settings the AiPlaybot.RandomBot**Auto**JoinBG setting is likely causing you issues too, as it's making the bots start their own bot only games, which likely leaves you with not enough to join **your** game (especially considering you don't have enough for a full AV game as it is). I would disable that. So in sum make sure these settings are in place: `AiPlayerbot.RandomBotJoinBG = 1` `AiPlayerbot.RandomBotAutoJoinBG = 0` (this makes the remaining AiPlayerbot.RandomBotAutoJoinXXX settings in your pic redundant so you don't need need to modify those)
> > Those settings are the defaults by the way (but you've probably adjusted them trying to resolve this issue), try adjust these settings first, then if that doesn't work, try adjust bot numbers/levels as mentioned above.
> 
> If AiPlaybot.RandomBotAutoJoinBG was enabled, I would still expect no bots to be auto joining WSG/Arena based on the count configurations (@rogerc66 has 0 listed for everything)
> 
> I thought it could possibly have been a performance issue, since bots won't queue if latency/diff is high.
> 
> I have no idea how npcbot Integrated works, but it could be for a whole bunch of things such as bots being in combat, bots somehow being queued for an unrelated BG that never pops (only one queue allowed at a time) etc
> 
> You may need to do some playing around with npcbots integrated enabled to try figure out what state the bots are in that could be causing them not to queue when a player queues. (Are the bots you are using even 'playerbots'?)

Thank you! I figured it out, I just have to wait a few second for playerbots to line up and then they will join bg with npcbot, 2 type of bots has different stategy and pathing, make bg more complex and more fun to watch them fight.

Easy to tell the difference of 2 bots, playerbot are lvl80 and npcbot are lvl70, and they behave differently as well.

![屏幕截图 2024-08-10 055952](https://github.com/user-attachments/assets/de95367f-8057-4505-81b0-fac2de093b87)
![屏幕截图 2024-08-09 232530](https://github.com/user-attachments/assets/c378fbd9-864b-42a7-840e-219b384e1ffe)
![屏幕截图 2024-08-09 232335](https://github.com/user-attachments/assets/45cbf023-7cf2-418e-b1c0-6824fc246478)
![屏幕截图 2024-08-09 232515](https://github.com/user-attachments/assets/0482d470-4709-43ee-8f53-d2dc99879451)
![屏幕截图 2024-08-09 232734](https://github.com/user-attachments/assets/7fd53c5e-309d-4b4f-a533-4217353efe10)

**Comment by ToneCre8** [comment]
Sorry to ask this here, but you've had success running NPCBots together with Playerbots? What were the hurdles?

**Comment by rogerc66** [comment]
> What were the hurdles?

Yeah, not much, just merge a few conflict files and compile them, carefully mock with conf setting, and it will run, so that you can bring your pet bot into playerbot bg having lots of fun.

**Comment by fuzzdeveloper** [comment]
> I thought it could possibly have been a performance issue, since bots won't queue if latency/diff is high.
That' only happens if you use enablePrototypePerformanceDiff (which isnt the default)

**Comment by hermensbas** [comment]
> > I thought it could possibly have been a performance issue, since bots won't queue if latency/diff is high.
> 
> That' only happens if you use enablePrototypePerformanceDiff (which isnt the default)

Indeed that was the cause with that enabled they only join if ping is low. These feature has been removed entirely for now for different reasons.
