### ISSUE TITLE
[Suggestion] - Add periodic check to enchant non-initialized gear

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#45]
Following up on previous discussions, currently the PlayerBot Enchant process only impacts gear generated during initialization. This feature would run periodic checks on PlayerBot equipped gear to check for missing enchants so that it can enchant gear that is acquired normally through world drops/dungeons/raids/etc.

This would be especially beneficial to those using the new configuration that prevents PlayerBots from initializing new gear after reaching level cap and requiring gear acquired by the above mentioned means.

This is definitely not a pressing issue, and thank you for all the improvements you have made on this project!

**Comment by Dreathean** [comment]
Along similar lines, it would make sense to include checking for empty gem slots for BC/WOTLK gear as well. 

This also makes me think of tier token gear for T4+ and what the best way to handle those drops would be. I can't think of something that isn't simply bruteforce matching each token and checking for player class + spec which sounds like it would be a lot of effort? Not imperative though as in the meantime most people using Playerbots are small groups or individuals and can simply GM add the equivalent item on a case by case basis.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/124fa9d5e05679c67606f231a9ef8ebb7e657672

Now we can enchant and set gems by `maintenance` command. At the same time, random bots will also initialize their enchantments and gems during `refresh` or `init`, which is performed periodically.

**Comment by Dreathean** [comment]
Incredible!! Will try to test this out when I get a chance though it might be a while before I can. Thank you so much for adding this functionality, I think it significantly enhances the experience people can have with Playerbots.
