### ISSUE TITLE
ChatQueuedReply::ChatQueuedReply(...) crash

### ISSUE THREAD

**Issue by zpl-zak** [liyunfan1223/mod-playerbots#453]
**Describe the bug**
Server crashes on the latest commit in `ChatQueuedReply::ChatQueuedReply(...)` constructor method.

**Commit hash**
[c0836c2](https://github.com/liyunfan1223/mod-playerbots/commit/c0836c26e6fc16c2617b0c1ce272130544029fb5)

**To Reproduce**
1. Enable `AiPlayerbot.RandomBotTalk`
2. Play for a while, eventually it crashes the server

**Expected behavior**
Crash should not happen

**Screenshots**
![image](https://github.com/user-attachments/assets/01599c0a-8153-498d-97fe-16756a0e6bb7)

**Additional info**
My server runs with 2500 random bots right now.

**NOTE**: I am building a Debug version of core right now, to get a better crash log as the data above is not precise.

**Comment by zpl-zak** [comment]
I was not able to reproduce it upon full rebuild anymore. If anything comes up again I'll try to provide core dump with debug symbols, closing it for now as invalid.

Sorry!

**Comment by zpl-zak** [comment]
I was eventually able to reproduce it.

Here's the new crash backtrace:
![image](https://github.com/user-attachments/assets/45835aee-d91b-4289-8ff8-192394ab0928)

**Comment by atidot3** [comment]
Hi, this is fixed with a pending PR. Awaiting merge.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/433
