### ISSUE TITLE
Why not join the AzerothCore organization

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#457]
Why not join the AzerothCore organization? Wouldn't that be more convenient?

**Comment by Dreathean** [comment]
I'm not really sure what you're expecting here, Liyunfan and the other developers have no affiliation with Azerothcore, and the main developers of Azerothcore are understandably not interested in supporting Playerbots. There is no real organization to join anyway, everything here and there is people willingly putting their free time into developing and contributing.
