### ISSUE TITLE
[Suggestion] Add additional option to PlayerBot Summon to only prevent summon during combat

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#46]
Following up on previous discussion, currently there are two options for PlayerBot summons: on or off. Off being no summoning at all, and on meaning you can always summon (which also revives) at any time. While this is a great QOL, this also enables users to repeatedly summon/revive PlayerBots during boss fights to cheese the encounter.

Therefore, would it be possible to add an option to only disable summons during combat? I feel that would be a good middle-ground preventing infinite summons/revives cheesing boss fights while still retaining the QOL aspect.

Please let me know what you think or if there is a better way to approach this!

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/e5e05988b2494d7f24f6f9002335061b2679e327

Now AiPlayerbot.BotReviveWhenSummon can be set to 0/1/2. (0 = never, 1 = enable when non-combat and alive, 2 = enable always)

**Comment by acgogo2023** [comment]
这个功能稳定吗？ 我选择了1，但是 我测试了在战斗状态还是可以复活机器人，，，，是我忽略了什么吗？
