### ISSUE TITLE
worldserver端大量1062错误

### ISSUE THREAD

**Issue by GesiIvy128** [liyunfan1223/mod-playerbots#48]
Waiting for 800 characters load into database...
SQL(p): INSERT INTO characters (guid, account, name, race, class, gender, level, xp, money, skin, face, hairStyle, hairColor, facialStyle, bankSlots, restState, playerFlags, map, instance_id, instance_mode_mask, position_x, position_y, position_z, orientation, trans_x, trans_y, trans_z, trans_o, transguid, taximask, cinematic, totaltime, leveltime, rest_bonus, logout_time, is_logout_resting, resettalents_cost, resettalents_time, extra_flags, stable_slots, at_login, zone, death_expire_time, taxi_path, arenaPoints, totalHonorPoints, todayHonorPoints, yesterdayHonorPoints, totalKills, todayKills, yesterdayKills, chosenTitle, knownCurrencies, watchedFaction, drunk, health, power1, power2, power3, power4, power5, power6, power7, latency, talentGroupsCount, activeTalentGroup, exploredZones, equipmentCache, ammoId, knownTitles, actionBars, grantableLevels, innTriggerId, extraBonusTalentCount) VALUES (800,80,Hille,4,11,1,1,0,2000000,2,0,4,3,4,0,2,0,1,0,0,10311.3,832.463,1326.41,5.69632,0,0,0,0,0,100663296 0 0 8 0 0 0 0 0 0 0 0 0 0 ,2,0,0,0,1697449987,0,0,0,4,0,0,0,0,,0,1000,0,0,0,0,0,0,4096,4294967295,0,64,110,0,0,100,0,0,0,0,1,0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ,0 0 0 0 0 0 0 0 6123 0 0 0 6124 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3661 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ,0,0 0 0 0 0 0 ,0,0,0, 0)
 [ERROR]: [1062] Duplicate entry '800' for key 'characters.PRIMARY'
 
 类似这样的，在载入时能刷一堆，我在原项目看到有人说这是主键重复了，ZhengPeiRu大佬说已解决，但是很多人还是会报错，出这个问题

**Comment by alexpec1** [comment]
确实每次启动时如果加载了机器人时就会出现很多闪动的红字，但有时候启动没有红字闪时，机器人又没加载出来，期待大佬修复。但zhengpeiru21的好像我每次启动不会出现红字啦，而且每次都能成功加载机器人。

**Comment by alexpec1** [comment]
playerbots的还是天蓝大佬的比较不错，还有米库的80团本机器人听说相当智能，能自动带着玩家打团本。但还是希望zhengpeiru21和liyunfan大佬可以开发越来越完善的playerbots，毕竟开源了可以让更多人享受自己编译的乐趣

**Comment by alexpec1** [comment]
期待又一个大佬的崛起，到时可以在有爱论坛上玩上你的端

**Comment by liyunfan1223** [comment]
Partially solved in https://github.com/liyunfan1223/mod-playerbots/commit/4e867606f20cc5bafad621202e5d1b45a44e264b. There still some unsolved database deadlock errors during characters creation, but do no acutal harm to the server.
