### ISSUE TITLE
cant summon/revive bots during combat

### ISSUE THREAD

**Issue by boldoran** [liyunfan1223/mod-playerbots#481]
**Describe the bug**
after the last update we cant "revive the bots" during combat

**Commit hash**
uh,, most recent

**To Reproduce**
enter a dungeon or any other form of combat
let bots die (happens anyway cause theyre stupid) 
try to summon/revive them when they die of stupidity

**Expected behavior**
i expect to be able to revive/summon them cause the settings should enable this.
it makes running certain dungeons quite hard/impossible cause the bots die of alot of stuff.

is this a known bug? or am i being daft?

thanks!

**Comment by dripone** [comment]
Did you enable this option in the playerbots config?
There was a recent change, where it will be set disabled default. You have to change it manually.

**Comment by boldoran** [comment]
> Did you enable this option in the playerbots config? There was a recent change, where it will be set disabled default. You have to change it manually.

![image](https://github.com/user-attachments/assets/f1138e6c-493f-4d91-934f-47f203322535)

guess so, or do i need to remake the config??

**Comment by boldoran** [comment]
to add to this: if i make the bots release spirit first, then i can summon them back in.. but sometimes this bugs them out

**Comment by boldoran** [comment]
FIXED:  i had to copy the new config, cause it didnt update it automaticly.

**Comment by dripone** [comment]
Exactly, after each update, you have to check if the configs are up to date and if not, you have to update them **manually**. The same applies to modules too.
