### ISSUE TITLE
Problem with invite

### ISSUE THREAD

**Issue by serverwar** [liyunfan1223/mod-playerbots#482]
![image](https://github.com/user-attachments/assets/472b0b57-a38f-4a22-8585-5099fa819692)
Bots are getting stuck in groups and this is very disruptive, sometimes there are many bots in Dalaran, but none are available for groups. Is this a problem? Or is there a different setting, the ones I had I activated.

I noticed that the bots are grouped in corners because they are in groups, I removed group .group remove and they started walking.

**Comment by serverwar** [comment]
Uploading World of Warcraft 2024-08-16 18-54-14.mp4…  
Here it shows me trying to invite to the group.

**Comment by hermensbas** [comment]
whisper the bot with /leave group

**Comment by Dreathean** [comment]
@serverwar are you still experiencing this issue? Or can anyone else confirm if they are having this issue? I haven't run into it myself personally
