### ISSUE TITLE
Excuse me, if the bot does not undertake quests, is it due to improper configuration or a bug

### ISSUE THREAD

**Issue by christan-duplicate** [liyunfan1223/mod-playerbots#483]
![image](https://github.com/user-attachments/assets/8d821b7a-ae89-46d4-b2b8-d893508bce45)

Excuse me, if the bot does not undertake quests, is it due to improper configuration or a bug？

**Comment by noisiver** [comment]
It's because they aren't programmed that way, yet. It's something Ati is working towards but baby steps. That counter has never said anything but Idling for me no matter what the bots are doing so I don't know where those flags are set (or rather isn't).

**Comment by christan-duplicate** [comment]
> It's because they aren't programmed that way, yet. It's something Ati is working towards but baby steps. That counter has never said anything but Idling for me no matter what the bots are doing so I don't know where those flags are set (or rather isn't).

Thank you for your answer.

**Comment by noisiver** [comment]
`playerbots rndbot stats` in the worldserver terminal.

**Comment by Mr-Deadbeat** [comment]
> `playerbots rndbot stats` in the worldserver terminal.

ah thanks yeah a bit inconvenient when you run the server as a systemd service so you get no output what so ever
would it be possible to get those commands to output to telnet terminal as well ?

**Comment by noisiver** [comment]
I couldn't tell you. I don't run them as a service because it gives me almost no control. I just use Screen.
