### ISSUE TITLE
worldserver Crash

### ISSUE THREAD

**Issue by cjl3230** [liyunfan1223/mod-playerbots#49]
启动到加载机器人的地方 崩溃了  不知道什么原因 mod和azerothcore-wotlk目前都是最新的

azerothCore-wotlk:   liyunfan1223/azerothcore-wotlk的Playerbot分支 https://github.com/liyunfan1223/azerothcore-wotlk/commit/a5e27362d8b5e4989815a34307fbe73947c8ae23
mod-playerbots:        liyunfan1223/mod-playerbots的master分支  https://github.com/liyunfan1223/mod-playerbots/commit/29b748803ec0d040fcd6d1dcef7f31d89e367f3f
 

[a5e27362d8b5_worldserver.exe_[20-10_10-55-28].dmp](https://github.com/liyunfan1223/mod-playerbots/files/13049523/a5e27362d8b5_worldserver.exe_.20-10_10-55-28.dmp)
[a5e27362d8b5_worldserver.exe_[20-10_10-55-28].txt](https://github.com/liyunfan1223/mod-playerbots/files/13049526/a5e27362d8b5_worldserver.exe_.20-10_10-55-28.txt)

**Comment by Jinxlynx** [comment]
Any resolve to this got the same issue it seems like. Also I noticed on server log its got a lot of handledummyauroproc none existing triggered spell for a hot minute. My issue appears randomly after 2-10 hours.

**Comment by Jinxlynx** [comment]
Threw it at ai something about money looting script

**Comment by Jinxlynx** [comment]
"PlayerScript.cpp"
"ScriptMgrMacros.h"
"ScriptMgr::OnAfterCreatureLootMoney"

Something about those I think

**Comment by Dreathean** [comment]
@cjl3230 are you still experiencing this issue? I haven't had any crashes in a while.

**Comment by cjl3230** [comment]
@Dreathean The latest version of azerothcore playerbot branch and mod-player has not crashed for a long time

**Comment by Dreathean** [comment]
Great, going to close this out thanks.
