### ISSUE TITLE
The new version can no longer automatically create and import databases. . .

### ISSUE THREAD

**Issue by zhangbo8418** [liyunfan1223/mod-playerbots#490]
The new version can no longer automatically create and import databases. . .

**Comment by zhangbo8418** [comment]
playerbots_names.sql cannot be imported

**Comment by hermensbas** [comment]
Can you describe abit more? maybe show some console logs. I've been running aaaaaalot of build from scratch with no issue's tbh. Maybe its a local thing, maybe not but we need more information.
