### ISSUE TITLE
Request training 

### ISSUE THREAD

**Issue by Ethusn** [liyunfan1223/mod-playerbots#494]
Request training and settings for bllizzlike server (normal)

Please give me an explanation how to change the conf so that I don't get into trouble on the first day of starting the server
1: How to set up their level up so that they level up like real players!
2: How to set up so that they can join the arena and random dungeon finder like real players without the intervention of real players, which will increase the activity in pve and pvp.
3: How to set the bots to have an independent guild.
4: Is there a way they can use whisper or reply normally and like real players
5: I am a newbie and I have a problem creating crash.log in Linux Ubuntu 24. Can anyone tell me the required commands, I would appreciate it.
6: There is a way to develop bots to use arena 1v1 and solo 3v3. azerohcote module
Finally, I would like to thank those who showed mercy for this great module

**Comment by Dreathean** [comment]
Please use the discord for any further regular questions https://discord.com/channels/1119972709091250236/1254868576729432144
