### ISSUE TITLE
Priest alt bot gets stuck in casting animation.

### ISSUE THREAD

**Issue by Grimfeather** [liyunfan1223/mod-playerbots#498]
**Describe the bug**
Priest alt bot seems to try and cast a spell, but is unable to. Casting animation gets stuck, his hands keep glowing, the casting sound keeps playing. It "fixes" itself when I remove a priest buff from myself, so the priest is forced to buff me.
But the issue will return.

I'm wondering if it has something to do with: https://github.com/liyunfan1223/mod-playerbots/pull/475/files
I see something there about cast guardianspiritonparty. but from my understanding that's a retail spell.
https://www.wowhead.com/spell=255312/guardian-spirit
I don't see it listed in the wotlk section. but that's just a guess after looking at recent commits

**Commit hash**
AzerothCore rev. fdb6fedc0050 2024-08-26 23:05:53 +0800 (Playerbot branch) (Win64, Release, Static) (worldserver-daemon)

**To Reproduce**
1. party with a priest alt bot for a bit.
2. after a while the priest will get stuck in a casting animation. light blue glowing hands.

**Expected behavior**
No stuck casting animations.

**Screenshots**
(https://i.gyazo.com/a044189edb3cad9e17fcf81daeaeb30f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by liyunfan1223** [comment]
Does the bot have [inner focus](https://www.wowhead.com/wotlk/spell=14751/inner-focus) aura? I’ve experienced something similar.

**Comment by Grimfeather** [comment]
> Does the bot have [inner focus](https://www.wowhead.com/wotlk/spell=14751/inner-focus) aura? I’ve experienced something similar.

yes, it does. disc priest spec

**Comment by liyunfan1223** [comment]
So it's a normal aura effect, just a little annoying, especially the sound effects.

**Comment by Grimfeather** [comment]
> So it's a normal aura effect, just a little annoying, especially the sound effects.

oh you're right. it is. I just never realized it because an actual player would cast it right before using it.
the bot just walks around with it for 5+ minutes.

annoying yes

**Comment by Grimfeather** [comment]
not really a bug then.
