### ISSUE TITLE
Old problem

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#5]
This is an old problem, which is a little annoying.

https://github.com/ZhengPeiRu21/mod-playerbots/issues/121

**Comment by liyunfan1223** [comment]
Not sure if this issue is caused by mod, or is it also present in the original Azerothcore.

**Comment by Blandyoung** [comment]
> 兄弟，我发现了问题所在，请打电话给我 Discord 以便我向您展示？
May I ask what the problem is? I would like to try to fix it

**Comment by Blandyoung** [comment]
> Bro @liyunfan1223 , I found out where the problem is, call me on Discord so I can show you?

May I ask what the problem is? I would like to try to fix it

**Comment by Dreathean** [comment]
@htc16 were you able to get this resolved with liyunfan?

**Comment by Dreathean** [comment]
Should this be closed?
