### ISSUE TITLE
Bot mining AI

### ISSUE THREAD

**Issue by Grimfeather** [liyunfan1223/mod-playerbots#505]
**Describe the bug**

- Right now in LootObjectStack.cpp the code only checks for a normal mining pick.

    if (skillId == SKILL_MINING && !bot->HasItemCount(2901, 1))
        return false;

There are a few more items that can be used as a mining pick (2901). I would like those to be added as well.
Gouging Pick - 1819
Brann's Trusty Pick - 20723

Maybe something like this?

    if (skillId == SKILL_MINING && (!bot->HasItemCount(2901, 1) || !bot->HasItemCount(1819, 1) || !bot->HasItemCount(20723, 1) ))
        return false;

**Commit hash**
AzerothCore rev. fdb6fedc0050 2024-08-26 23:05:53 +0800 (Playerbot branch) (Win64, Release, Static) 

**To Reproduce**
1. party up with an alt bot with the mining skill
2. replace his normal mining pick with one of the others.
3. stand next to a mining node
4. notice nothing is happening.

**Expected behavior**
- Gouging Pick and Brann's Trusty Pick to also be viable mining tools.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by aekinskjaldi** [comment]
Thank you for direction, I faced same problem (but with different mining pick capable item) and managed to solve it.

First i made sql query against acore_world database to find ID of items suitable as mining pick:
`select entry,name,description from item_template where description like "%mining pick%";`

After testing some "if" conditions in test cpp program I changed condition at 240 str in LootObjectStack.cpp this way:
`    if (skillId == SKILL_MINING && !bot->HasItemCount(756, 1) && !bot->HasItemCount(778, 1) && !bot->HasItemCount(1819, 1) && !bot->HasItemCount(1893, 1) && !bot->HasItemCount(1959, 1) && !bot->HasItemCount(2901, 1) && !bot->HasItemCount(9465, 1) && !bot->HasItemCount(20723, 1) && !bot->HasItemCount(40772, 1) && !bot->HasItemCount(40892, 1) && !bot->HasItemCount(40893, 1) )`

and in ItemUsageValue.cpp after line 359 added this items as well, so mining section got look like this:
```
        case 756:  // Tunnel Pick
            return botAI->HasSkill(SKILL_MINING);
        case 778:  // Kobold Excavation Pick
            return botAI->HasSkill(SKILL_MINING);
        case 1819:  // Gouging Pick
            return botAI->HasSkill(SKILL_MINING);
        case 1893:  // Miner's Revenge
            return botAI->HasSkill(SKILL_MINING);
        case 1959:  // Cold Iron Pick
            return botAI->HasSkill(SKILL_MINING);
        case 2901:  // Mining Pick
            return botAI->HasSkill(SKILL_MINING);
        case 9465:  // Digmaster 5000
            return botAI->HasSkill(SKILL_MINING);
        case 20723:  // Brann's Trusty Pick
            return botAI->HasSkill(SKILL_MINING);
        case 40772:  // Gnomish Army Knife
            return botAI->HasSkill(SKILL_MINING);
        case 40892:  // Hammer Pick
            return botAI->HasSkill(SKILL_MINING);
        case 40893:  // Bladed Pickaxe
            return botAI->HasSkill(SKILL_MINING);
```
now my bot mate mining ores with Miner's Revenge from low level quest, I think this should work for other mining picks as well.

**Comment by Grimfeather** [comment]
should be fixed now.
