### ISSUE TITLE
Bots and creatures ignoring LoS as of recent

### ISSUE THREAD

**Issue by Dohtt** [liyunfan1223/mod-playerbots#510]
**Describe the bug**
Both playerbots and creatures started clipping through walls or floating around recently.
Reports of this happening started coming in on the discord from 9/04/2024

**Commit hash**
1b7f94d

**To Reproduce**
1. Go to a dungeon or pvp zone
2. Try to line of sight an enemy or watch bot movement
3. See them clip through previously non clipped obstacles and terrain (walls, the floor,...)

**Expected behavior**
Both the bots and the npcs shouldn't be clipping through

**Screenshots**

https://github.com/user-attachments/assets/ebdb56c0-7a15-4cd1-a0be-dde39ae31829

**Comment by liyunfan1223** [comment]
Comfirmed. This seems to be fixed in latest AC https://github.com/liyunfan1223/azerothcore-wotlk/commit/6f5b504e4cfa46f54442b9b4c7f4b3294800214e, please confirm.

**Comment by Dohtt** [comment]
Confirmed, solved the issue for me.
