### ISSUE TITLE
Group with bots

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#52]
Hello, I've been trying to get in a group with bots. 
They are all already in a group, but I think its with eachother or someone offline. No new bots are appearing though. 
How can I make a group when that happens?

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/966c33f9446b11960c0145ce5ea67c0c9eb03b32

I modified the bot group so that when the leader of the group is not a player, the bot will automatically leave the group. This should solve most cases.

**Comment by evrydayjunglist** [comment]
you can whisper the bot "invite" and they'll invite you if they're leader, if not they'll tell you who the leader is.
then you can tell the bot "give leader" once you're in the group.
