### ISSUE TITLE
Spells are not rewarded by quests

### ISSUE THREAD

**Issue by sogladev** [liyunfan1223/mod-playerbots#531]
**Describe the bug**
Spells are not rewarded by quests. Quest completes,  but no spell is learned until the player relogs

**Commit hash**
bfbc451bfb97

**To Reproduce**

create undead warlock
complete voidwalker quest
```
.quest add 1471
.quest complete 1471
```

reward command or turn in at npc
```
.quest reward 1471
.go c id 5675
```

reset
```
.quest remove 1471
```

1. add quest
2. complete quest
3. reward quest
4. see no spell is learned

**Expected behavior**
spell is learned upon completion

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
On stock AzerothCore this clause fails and the spell is cast:
- https://github.com/azerothcore/azerothcore-wotlk/blob/8030ef4ba0ed7ee20b3647c58fe421f91c1e1274/src/server/game/Entities/Player/PlayerQuest.cpp#L832

playerbots: 
on playerbots, this clause fails and no spell is cast:
- https://github.com/liyunfan1223/azerothcore-wotlk/blob/af776520dbd5bc0bb27762e546b8c499281db56d/src/server/game/Entities/Player/PlayerQuest.cpp#L832

**Comment by hermensbas** [comment]
Confirmed, works in the original AC core, but fails in our branch.

**Comment by hermensbas** [comment]
![image](https://github.com/user-attachments/assets/372fc013-f194-4e0e-8c95-66cde770819e)

https://github.com/liyunfan1223/azerothcore-wotlk/commit/414805e692abaf8e4322f59e6660faff81e979f2

**Comment by noisiver** [comment]
414805e692abaf8e4322f59e6660faff81e979f2 removed a part of that code, mainly the curly brackets and the else at the bottom so it stopped working. It should be updated to use what AC uses.

**Comment by liyunfan1223** [comment]
Confirmed. This was introduced by a conflict merging mistake.
