### ISSUE TITLE
Low Level RandomBots initializing with 1 high level BC belt

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#54]
Noticed that some low level (10-13) are initializing with the following item - 25582, qr-9867-druid-moonkin-belt

![WoWScrnShot_102823_142411](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/9fe3e6d8-cf4f-4d11-adf4-216e1e33c0b0)
![WoWScrnShot_102823_142647](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/31fa97c0-9704-4109-85cf-c32bb5f1d310)

**Comment by liyunfan1223** [comment]
Confirmed. Gonna fix it, thank you!

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/af44b22ce1c4b83276a56c81620b4b0e065860d0
