### ISSUE TITLE
Delete all randombot accounts (reset randombots) in.conf does not work properly.

### ISSUE THREAD

**Issue by gutoukuaiken** [liyunfan1223/mod-playerbots#541]
**Describe the bug**
Will the conf file AiPlayerbot. DeleteRandomBotAccounts = 0 to 1, all build bots account information has not been completely removed. The same is true for Windows and Ubuntu.

**Code version**
AzerothCore rev. 6f5b504e4cfa 2024-09-07 14:27:11 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static)

**Comment by SAMBILI** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme
I put the necessary dlls in the archive

**Comment by gutoukuaiken** [comment]
Above is a link with a virus, everyone do not click to download.

**Comment by gutoukuaiken** [comment]
Note: There is still data for random robots in the acore_characters characters table of the database. The other tables should have data on randombots.
