### ISSUE TITLE
Running into C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by dan-garcia** [liyunfan1223/mod-playerbots#545]
**Describe the bug**
World server is crashing upon attempted login. It's related to OpenSSL, specifically `libcrypto-3-x64.dll`, and giving an `ACCESS_VIOLATION`.

**Commit hash**
rev 1bf88ad3a341 and 9780dbab7e11

**Desktop (please complete the following information):**
 - OS: Win 10HE x64

**Additional context**
https://gist.github.com/dan-garcia/f33b8f33905cf19f52046163497e0ac2
https://gist.github.com/dan-garcia/5b594ffebbda3c14e7ca96ee03fe728d

**Comment by hermensbas** [comment]
Unrelated to mod-playerbots though

**Comment by Dreathean** [comment]
Closing as not related to playerbots
