### ISSUE TITLE
Raid sharing cd

### ISSUE THREAD

**Issue by serverwar** [liyunfan1223/mod-playerbots#557]
![image](https://github.com/user-attachments/assets/0138a186-8c7d-4f2a-a047-33711472562d)
I would like some help, icc 10 man and 25 man are sharing cd together with 10 hc and 25hc, I looked for something about it in azeroth and didn't find it, does anyone know which part of the cod that changes this?

![image](https://github.com/user-attachments/assets/9fde2daa-4759-4e3e-aa36-e62f6c598dee)
I killed 10n and got 10hc

**Comment by EricksOliveira** [comment]
#
#   Instance.SharedNormalHeroicId
#        Description:  Forces ICC and RS Normal and Heroic to share lockouts.  ToC is uneffected and Normal and Heroic will be separate.
#        Default:  1 - Enable
#                  0 - Disable
#

Instance.SharedNormalHeroicId = 1
