### ISSUE TITLE
The little bot followed the main one for a few monsters and then stopped attacking

### ISSUE THREAD

**Issue by alexyang-sea** [liyunfan1223/mod-playerbots#56]
@liyunfan1223 I compiled with your latest source code, now there is no red error, but I grouped a small number under the robot to do quests together to fight monsters, and found that after 4/5 monsters the robot stopped attacking, I do not know if it's because of my configuration file needs to be where to set up or its own source code reasons? Looking forward to the answer, thanks!

**Comment by liyunfan1223** [comment]
Thanks for your report. Please provide more details for reproducing.

**Comment by alexyang-sea** [comment]
I built 5 numbers with Horde, Hunter, Knight, Shaman, Warlock, Warrior, and then started a quest in the newbie village with several other numbers in the Hunter's group, and found out that the bots don't attack after 4 monsters when I was hunting boars. What other details do you need?

**Comment by alexyang-sea** [comment]
Sorry, I think I found the problem, it has nothing to do with your source code, it's because I set the wrong guid for ahbot, I changed the guid, now there is no problem of not attacking, sorry to bother you. Your bot is getting better and better, more and more playable, looking forward to your bot mods getting better and better.
