### ISSUE TITLE
您好，从哪能看到命令说明呢？

### ISSUE THREAD

**Issue by CoffeeFantasy** [liyunfan1223/mod-playerbots#57]
您好，从哪能看到命令说明呢？我没有找到··

**Comment by liyunfan1223** [comment]
Here's a manual for original version of playerbots by ike3, most of the basic commands are available for this module https://ike3.github.io/mangosbot-docs/.

We lack documentation for newly added commands, the project is still under development.

**Comment by Dreathean** [comment]
That manual is exactly what I had been looking for, sweet!

**Comment by CoffeeFantasy** [comment]
Thank you very much！

**Comment by Dreathean** [comment]
@liyunfan1223 I know a lot of people have asked for and could use this documentation on the main Playerbots github, is there any way you can link it/reference it in the About or ReadMe for others to see and use?
