### ISSUE TITLE
Worldserver crash on leaving a WotLK dungeon

### ISSUE THREAD

**Issue by HennyWilly** [liyunfan1223/mod-playerbots#574]
**Describe the bug**
Leaving a WotLK dungeon while at least one bot is still inside causes a worldserver crash.
I first noticed this after trying out Utgarde Keep Heroic, as new bot strategies were implemented in #560.
I haven't tested all dungeons, but this also happened to me in Utgarde Pinnacle HC and Violet Hold HC.

Additionally, after the worldserver restart, if I make the bot that is still in the dungeon go online, the worldserver crashes again.

**Commit hash**
9ebdbd84593a78d40842476aa7493322d6978a38

**To Reproduce**
1. Enter, for example, Violet Hold HC with at least one bot.
2. Order the bot to stay.
3. Leave the dungeon.
4. After a few seconds, the worldserver will crash and restart.

**Expected behavior**
The worldserver should not crash.

**Screenshots**
Not really a screenshot but here is the [gdb-crashlog.txt](https://github.com/user-attachments/files/17245949/gdb-crashlog.txt) after I enabled GDB in the Dockerfile.
I'm not really fluent with GDB logs and C++ in general, but it looks to me that [KelesethFrostTombTrigger::IsActive](https://github.com/liyunfan1223/mod-playerbots/pull/560/files#diff-8f086e10108fb9048c61f2f39918ebb2c2cdded11f31d0b3f3670a011554b930R11) causes these crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Docker Desktop

**Comment by avirar** [comment]
#575

**Comment by Bobblybook** [comment]
FYI most wotlk dungeons do not have strats currently and default to Utgarde Keep as a placeholder, these will be implemented shortly, I'm getting through them
