### ISSUE TITLE
One Question

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#58]
Hello, congratulations on all your efforts, the results are very obvious and good!  

One question, I realize that we have an extensive list of bot players, however, most of the time, only the same ones enter the server, or is it just me?

**Comment by Dreathean** [comment]
I'm not sure which one but one of the toggles at the lower portion of the .conf controls how frequently they get rotated, have you had your server running for days straight without it ever switching bots?

Personally I set about 200 and like having the same bots so it's not a problem for me haha, but this is all useful info to learn more about for sure.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/b84542a74520731fbdc939c304e3dda4660c8d9f

Setting AiPlayerbot.EnableRotation and AiPlayerbot.RotationPoolSize can meet. Note that you need to enter `playerbot rndbot reset` in the console after modifying the settings to make it take effect.
