### ISSUE TITLE
server freezing

### ISSUE THREAD

**Issue by serverwar** [liyunfan1223/mod-playerbots#584]
Before it happened once a week, now it happens 3 times a day

Error logs from the last crashes:
![image](https://github.com/user-attachments/assets/8555b172-6b18-4c60-aded-ff2c2516f1f3)

![image](https://github.com/user-attachments/assets/37286e4b-ee16-4037-9b19-14476658aa67)

server.log

![image](https://github.com/user-attachments/assets/f4188d3d-650a-48ee-8a14-172fe2a25bc3)

Playersbots.log 

![image](https://github.com/user-attachments/assets/d6ae5f16-4640-43b3-bffd-548fe9e00f0d)

I'm trying to figure out what's causing this, does anyone have any idea to help me?

**Comment by noisiver** [comment]
You're not really including all the information. What's your update interval for bots set to, how many bots do you have logged in, what % of active bots do you have and all that jazz.

We determined that even though the server looks like it's running decently, in the background it could actually be choking very badly without you knowing it. You have to look at RAM usage to get some kind of image of how badly.

**Comment by Mr-Deadbeat** [comment]
from what i saw above he has deadlock issues with the database wonder if he has fiddled with the worker threads ?

**Comment by serverwar** [comment]
> You're not really including all the information. What's your update interval for bots set to, how many bots do you have logged in, what % of active bots do you have and all that jazz.
> 
> We determined that even though the server looks like it's running decently, in the background it could actually be choking very badly without you knowing it. You have to look at RAM usage to get some kind of image of how badly.

# INTERVALS
#
#

# All In seconds
AiPlayerbot.RandomBotUpdateInterval = 90
AiPlayerbot.RandomBotCountChangeMinInterval = 3600
AiPlayerbot.RandomBotCountChangeMaxInterval = 10800
AiPlayerbot.MinRandomBotInWorldTime = 7200
AiPlayerbot.MaxRandomBotInWorldTime = 21600
AiPlayerbot.MinRandomBotRandomizeTime = 302400
AiPlayerbot.MaxRandomBotRandomizeTime = 1209600
AiPlayerbot.RandomBotsPerInterval = 300
AiPlayerbot.MinRandomBotReviveTime = 120
AiPlayerbot.MaxRandomBotReviveTime = 300
AiPlayerbot.MinRandomBotTeleportInterval = 7200
AiPlayerbot.MaxRandomBotTeleportInterval = 21600
AiPlayerbot.RandomBotInWorldWithRotationDisabled = 86400

GENERAL
#
#

# Maximum number of bots added by one account
AiPlayerbot.MaxAddedBots = 4

# Maximum number of bots per class added by one account
AiPlayerbot.MaxAddedBotsPerClass = 4
# Enable/Disable create bot by addclass command (0 = GM only, 1 = enable)
# default: 1 (enable)
AiPlayerbot.AddClassCommand = 1

# Set the addclass command account pool size
# Addclass command uses a subset of accounts from RandomBotAccountCount
AiPlayerbot.AddClassAccountPoolSize = 10
# Bot group invitation permission level (0 = GM only, 1 = accept based on level, 2 = always accept)
# default: 1 (accept based on level)
AiPlayerbot.GroupInvitationPermission = 2

# Random bot account
AiPlayerbot.RandomBotAccountCount = 200

# Random bot count
AiPlayerbot.MinRandomBots = 50
AiPlayerbot.MaxRandomBots = 50

![image](https://github.com/user-attachments/assets/147b2c91-f1fe-439c-9749-fc72402ef35a)

**Comment by noisiver** [comment]
Yeah, total RAM usage is helpful. It would be more helpful if you actually looked at the usage of worldserver though.

**Comment by serverwar** [comment]
> Yeah, total RAM usage is helpful. It would be more helpful if you actually looked at the usage of worldserver though.

![image](https://github.com/user-attachments/assets/545315eb-b6fe-424e-9af3-a4366d24feb0)

**Comment by noisiver** [comment]
Thank you a bunch. Well, worldserver is using 6.5GBish. What could be eating the rest though? Oh well. IS the server frozen at this point?

**Comment by noisiver** [comment]
If MySQL keeps growing like that, at some point you'll run out of RAM and worldserver can't get any so it'll freeze. Possibly a combination of both, MySQL taking the majority and worldserver keeps growing slowly until there's none left. You should look at it when it's frozen.

**Comment by Mr-Deadbeat** [comment]
btw have you changed the default values on these at all ?
```#
#    PlayerbotsDatabase.WorkerThreads
#        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
#                     statements. Each worker thread is mirrored with its own connection to the
#                     MySQL server and their own thread on the MySQL server.
#        Default:     1 - (PlayerbotsDatabase.WorkerThreads)

PlayerbotsDatabase.WorkerThreads     = 1

#
#    PlayerbotsDatabase.SynchThreads
#        Description: The amount of MySQL connections spawned to handle.
#        Default:     1 - (PlayerbotDatabase.WorkerThreads)

PlayerbotsDatabase.SynchThreads     = 1 ```

mainly thinking about your database deadlocks above

**Comment by serverwar** [comment]
> a propósito, você alterou os valores padrão deles?
> 
> ```
> #    PlayerbotsDatabase.WorkerThreads
> #        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
> #                     statements. Each worker thread is mirrored with its own connection to the
> #                     MySQL server and their own thread on the MySQL server.
> #        Default:     1 - (PlayerbotsDatabase.WorkerThreads)
> 
> PlayerbotsDatabase.WorkerThreads     = 1
> 
> #
> #    PlayerbotsDatabase.SynchThreads
> #        Description: The amount of MySQL connections spawned to handle.
> #        Default:     1 - (PlayerbotDatabase.WorkerThreads)
> 
> PlayerbotsDatabase.SynchThreads     = 1 ```
> 
> mainly thinking about your database deadlocks above
> ```

![image](https://github.com/user-attachments/assets/00a93341-caa5-4727-b04b-509821d68269)
I didn't modify that part

**Comment by Mr-Deadbeat** [comment]
ok then the issue lies elsewhere thought it might have been the cause for one of the issues

**Comment by serverwar** [comment]
> ok then the issue lies elsewhere thought it might have been the cause for one of the issues

Thank you, I'm racking my brains over this.

**Comment by Loopher** [comment]
Are you running the Auction House bot?  I had a similar issue where my SQL server was growing uncontrollably.  I found the AH bot malfunctioned and created over 1.2 million items eating up all my RAM in the process.  Took me a few days to find it, like you I thought it was a configuration issue.

**Comment by serverwar** [comment]
![image](https://github.com/user-attachments/assets/5f16d88d-9b17-4314-9c72-09bfa3763dce)
Just today there were 2 crashes, morning and afternoon

**Comment by serverwar** [comment]
> ![image](https://private-user-images.githubusercontent.com/65511189/373982507-5f16d88d-9b17-4314-9c72-09bfa3763dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTE3NzksIm5iZiI6MTcyODI1MTQ3OSwicGF0aCI6Ii82NTUxMTE4OS8zNzM5ODI1MDctNWYxNmQ4OGQtOWIxNy00MzE0LTljNzItMDliZmEzNzYzZGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIxNTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzAxZmE0Y2JkNzQwNWI0YmJkMjJlMTA5YTU4MGVlMDBkNzdkZjNkNDEwOWMyZWI5MmVmZDFkZjk5N2IzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CB-O17czvX_z48y6iQ4pXI1rYXItLJYqZDBg-8MYbQY) Just today there were 2 crashes, morning and afternoon
Logs is crash antifreeze

**Comment by serverwar** [comment]
> Are you running the Auction House bot? I had a similar issue where my SQL server was growing uncontrollably. I found the AH bot malfunctioned and created over 1.2 million items eating up all my RAM in the process. Took me a few days to find it, like you I thought it was a configuration issue.

![image](https://github.com/user-attachments/assets/e3dfa0d6-ca9e-4637-bdaa-78c7c63a42c6)
I'm going to disable it to see if anything changes.

**Comment by Loopher** [comment]
If it already has added items in the DB, it is not going to change anything.  Check your acore_characters DB, look for the auctionhouse table and see how much space it is using.

**Comment by noisiver** [comment]
That's a good call. I have the module installed but only use it to buy my items, not sell any, so I never noticed that. If it is that, 50GB.. that'd be quite a large table.

**Comment by serverwar** [comment]
> Thank you a bunch. Well, worldserver is using 6.5GBish. What could be eating the rest though? Oh well. IS the server frozen at this point?
> 
> Edit: Hang on... I just noticed.. mysql taking up 50GB? What in the holy hell.

Guy works with me reserve % for mysql

**Comment by noisiver** [comment]
MySQL shouldn't take up 50GB of RAM. Even if I leave mine running for months it even get 5% of the usage you have. It's bad.

**Comment by Mr-Deadbeat** [comment]
i have ah bot as well and it has never been causing me any issues might be you have configured it with too many items and during processing of the items it grows out of control ??

also i'm using both buyer and seller with dedicated account for it

**Comment by noisiver** [comment]
Look at the `auctionhouse` table in the `acore_characters` database. See how many rows there are. That'll tell you if it's that or not.

**Comment by serverwar** [comment]
Thanks for the information, I'll make some changes and see if anything changes. I'll also check the tables mentioned. The crash rate is zero due to errors, it's just this daily freeze.

**Comment by Mr-Deadbeat** [comment]
ok keep us in the loop of how things progress :)

**Comment by noisiver** [comment]
It is a weird one. The only thing that comes to mind is what's been discussed lately and that's the memory issue. But if it's happening several times a day, 200 bots shouldn't cause that that fast. Hard to tell though, best to look at it when it's happening unfortunately. Hopefully this can be solved so you can enjoy the server again because it's annoying for sure.

**Comment by Mr-Deadbeat** [comment]
yeah for sure i have 400 bots and server has 32gb ram just for the game world
and most of the time server consumes around 7gb ram db server is remote but on the same server as a vm with 8gb ram and so far no issue so this was a strange one indeed

**Comment by serverwar** [comment]
Everything was normal, sometimes it started freezing out of nowhere, this stresses me out, because I get lost without logs, I'll check and make some changes, thanks for the help, really appreciated.

Note: Average real players = 85 - 100 + bots

**Comment by noisiver** [comment]
It kind of sucks that you can't (easily, at least) log resource usage. It would be very helpful to be able to look back at that stuff. At least you know now that you need to look at it when you notice the server locking up, if nothing else so you can eliminate it as the cause.

**Comment by serverwar** [comment]
I figured out the crashing problem
![image](https://github.com/user-attachments/assets/89387137-041a-446d-a7f8-91cd1d26fd17)
They are using programs to attack
After I started flooding the server crashed
