### ISSUE TITLE
Outfitting a robot doesn't automatically wear

### ISSUE THREAD

**Issue by alexyang-sea** [liyunfan1223/mod-playerbots#59]
I'm disturbing you again.I compiled zhengpeiru21's in September, then give the robot equipment, as long as you can wear and better than now on the body equipment, the robot will automatically wear, but I found that now after the latest compilation of the robot equipment, they will not be automatically wear, you need to open the wear pieces in the robot's backpack, and then point to the robot equipment in the appropriate location, out of the backpack on the choice of equipment on the robot in order to wear! I'd like to suggest you to let the robots wear the equipment by themselves. It is recommended to let the robots wear better equipment than what is in their backpacks, and if the equipment given to the robots is unsuitable, don't let the equipment disappear, it will remain in the backpack and can be traded over to the auction house by the player.

**Comment by Dreathean** [comment]
I have also experienced similar, I noticed when I tested GM adding better gear to playerbot inventory that it seemed to automatically add some pieces but not all even though they were all significant improvements (IE T3 gear vs currently wearing lvl 58 rares).

**Comment by liyunfan1223** [comment]
Did you set AiPlayerbot.AutoEquipUpgradeLoot=1 to enable auto equip upgrade?

**Comment by liyunfan1223** [comment]
> if the equipment given to the robots is unsuitable, don't let the equipment disappear, it will remain in the backpack and can be traded over to the auction house by the player.

Comfirmed this. Prepare to fix it later.

**Comment by alexyang-sea** [comment]
> Did you set AiPlayerbot.AutoEquipUpgradeLoot=1 to enable auto equip upgrade?

It's true that this item is not set to 1. For a newcomer like me, a lot of the configurations aren't clear, so it would be nice if there was a document explaining them. In addition, the current bots do not teleport with the player through Hearthstone, they need to be summoned through the plugin. It is recommended that when a player teleports through Hearthstone, the bots in the team can also teleport together.
