### ISSUE TITLE
How to upgrade talent points for bots under the same number

### ISSUE THREAD

**Issue by alexyang-sea** [liyunfan1223/mod-playerbots#60]
@liyunfan1223 Sorry, although I know you're busy, I still have a question to ask, and maybe this one seems elementary: I see in the config file that the settings about talent point upgrades are already defaulted to auto upgrades # Bot automatically picks talent points on levelup # Bot automatically picks Talent points # Default: 1 (enabled) # Default: 1 (enabled) AiPlayerbot.AutoPickTalents = 1 But I find that their talent points are still 0 and not automatically added, even after I specify their function in the plugin, even though they have available talent points. Is it possible to add a function on the plugin that specifies their talents and can be toggled at any time, and then the bot automatically upgrades the talents by the best talent points for that lineage? Is the current method to go on each number and manually upgrade their talent points?

**Comment by liyunfan1223** [comment]
The configuration is only for random bots leveling up, and the configuration is indeed not cleared :(. Currently you must manually pick talents for player created characters, I'm considering adding this feature.

**Comment by acgogo2023** [comment]
不错的建议， 还有，是否考虑过机器人自动跟随玩家传送的选项？

**Comment by alexyang-sea** [comment]
是的，自动跟随玩家传送的功能我也提过了，每次都需要点插件的传送机器人才过来也不方便

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/1d21feb1ea15fc45dee62efb1302e0ad7630429f

Now you can use the command to specify the talents of the bot. You can check the usage by chatting with the bot 'talents'.
You need to update the configuration file and overwrite the original configuration file with the new playerbots.conf.dist.
