### ISSUE TITLE
Report an error“Bot GUID Full: 0x0000000000000486 Type: Player Low: 1158 H:35 <Jake> can't find a spirit healer”

### ISSUE THREAD

**Issue by gutoukuaiken** [liyunfan1223/mod-playerbots#603]
**Describe the bug**
The background was flooded with this message“Bot GUID Full: 0x0000000000000486 Type: Player Low: 1158 H:35 <Jake> can't find a spirit healer”，After a period of time, the resources of the server will be heavily occupied.

**Commit hash**
AzerothCore rev. 0e1fb788c101+ 2024-10-05 00:12:41 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static)
playerbot-modules 4c13a11ff243a2cb9e91e94c7ab22c01424d3f58 

**To Reproduce**
There's no specific way. It's random.

**Desktop (please complete the following information):**
 ubuntu 22.04

**Comment by gutoukuaiken** [comment]
This situation occurs when the bot automatically fights monsters and upgrades, no one operates the bot, and all the bots act autonomously.

**Comment by gutoukuaiken** [comment]
It only happens when the robot doesn't reanimate itself, right?

**Comment by gutoukuaiken** [comment]
> I don't know how to explain why this happens. as Bots should revive automatically. However, this error occurs. To correct this error, simply use the GM command .revive.
That means this only happens if the robot can't revive itself, right?

**Comment by EricksOliveira** [comment]
Yes. He is close to the Spirit Healer and cannot revive.

**Comment by gutoukuaiken** [comment]
> Yes. He is close to the Spirit Healer and cannot revive.

How can I limit the bot's use of some commands? For example, limit the use of the ".grind "command.
