### ISSUE TITLE
Some altbots don't move after playerbots bot add command.

### ISSUE THREAD

**Issue by lidstah** [liyunfan1223/mod-playerbots#604]
Hi,

First of all, thanks alot for maintaining and developing the playerbots module and Azeroth Core playerbot branch. It's great for us selfhosters and tinkerers to bring life to our little worlds.

**Describe the bug**
updated AzerothCore playerbots to latest commit ([418afce](https://github.com/liyunfan1223/azerothcore-wotlk/commit/418afce6d74c72a583fd259e1a14f33df522017a)) and playerbot branch to latest commit (see next section). Did a clean build (I'm also using mod-ah-bot) through make clean, then make -j6 and make install.

When I login, and add my alts as bots, some of them don't move, don't buff the other bots of my group and it seems they're "lagging", for e.g. if I mount, they'll use their mounts with a 10s interval while the non-stuck altbots use their mounts almost instantly, or if I use tell commands like "talents", they answer with around 10 seconds "lag", while the non-stuck altbots behave as intended.

I'm adding my altbots through a macro which invokes `.playerbots bot add BOTNAME` sequentially.

The random bots work as intended (750 bots).

I've rollback to last week version (I always backup azcore and database before upgrading) but I'll be glad to do tests if needed.

I can provide my playerbot and worldserver configuration if needed.

Edit: Forgot to precise, but the two "stuck" altbots were a Warrior Prot PVE and a Priest Holy PVE. Rogue (combat pve) and Paladin (ret pve) were working as intended at first glance. I tried teleport/logout/login again the "stuck" altbots to no avail, but I've not tested teleporting them in an instance.
 
**Commit hash**
[58abb0d](https://github.com/liyunfan1223/mod-playerbots/commit/58abb0d9cef7de5b15e5dbed686407749ca57135)

**To Reproduce**
1. login
2. add your alt bots
3. some of them will get 'stuck'

**Expected behavior**
Alt bots should behave as intended.

**Server setup:**
 - Type: Proxmox VM
 - CPU: Ryzen 7 4800U
 - OS: Debian 12
 - Cores: 6 vCPUs ("host" type)
 - RAM: 32GB
 - Storage: SSD
 - VxLAN setup (MTU: 1450)
 - Database: Proxmox VM, CPU: i5-10210U, Debian 12, 2 vCPUs (exposed as host CPU to the VM), 4GB RAM, SSD storage, mysql 8.4, VxLAN setup.

Once again, thanks for your awesome work.

**Comment by liyunfan1223** [comment]
Hi Iidstah,

Does the stuck always happen to these two bots? Even after the server restarts.

**Comment by lidstah** [comment]
Hi liyunfan1223,

First, thank you for your answer.

In fact, when I first started the server after the update, only the priest was stuck, then I restarted the server, and the priest and the warrior were stuck. I then rollbacked to my backup, but if you want I can compile it again tomorrow (Friday) and do more extensive tests.

**Comment by lidstah** [comment]
Hi again,

So, managed to properly compile everything, with latest commits from mod-playerbots (599c26b), and I can't reproduce the bug, my altbots are working properly. I'll thus close this issue, which might be due to my setup.
