### ISSUE TITLE
[Feature Request] Ability to unequip specific slots on bots

### ISSUE THREAD

**Issue by F-Lambda** [liyunfan1223/mod-playerbots#608]
Currently, you can tell bots to equip specific items, or to destroy items in their inventory. However, the destroy command doesn't work on items they're currently wearing, nor can you specifically tell them to unequip an inventory slot, just replace it with another item in their inventory.

It'd be nice if you could tell them to unequip an item without needing a replacement item (for example, if you've previously given them a shirt and it no longer fits with the appearance of their current gear).

**Comment by Dreathean** [comment]
The command is "ue [linked item]" to unequip
