### ISSUE TITLE
Login is extremely slow

### ISSUE THREAD

**Issue by yimo0871** [liyunfan1223/mod-playerbots#614]
**Describe the bug**
服务启动后的首次登录会卡在“已经连接”、"获取角色列表"界面很久。
For the first login after the service is started, it will be stuck on the interface of "Connected" and "Obtaining role list" for a long time.

**Commit hash**
16ea1777f4003fc1d21170b7e8e0b5c76bb19555

**To Reproduce**
1. Enable plugins[mod-ah-bot]、[mod-playerbots]、[mod-anticheat]
2. Start authserver、worldserver
3. login

**Expected behavior**
服务端启动成功后，真实玩家应该可以直接登陆，而不应该需要等待。
After the server is successfully started, real players should be able to log in directly instead of having to wait.

**Screenshots**
![image](https://github.com/user-attachments/assets/195e3926-b675-4907-84aa-e9dff8a9360e)

**Desktop (please complete the following information):**
 - OS: CentOS Stream 9 x86_64

**Comment by mw108** [comment]
I've had a similar issue that was caused by a weird bot config. Can you please post your playerbots.conf? Remember to remove your MySQL credentials.

**Comment by hermensbas** [comment]
closed for now, slow as first logon is acceptable. Too slow not reproducable
