### ISSUE TITLE
Changing DBC.Locale = 8 breaks bots

### ISSUE THREAD

**Issue by MRafStudio** [liyunfan1223/mod-playerbots#62]
For a long time I couldn’t understand why the bots stopped working normally with their spells. As it turns out, changing the DBC.Locale parameter in worldserver.conf from 255 to 8 drives them crazy. Although this is not a bug and can be cured by restoring the parameter to 255, it’s just curious that such a thing from the server config breaks the bot’s work.

**Comment by MRafStudio** [comment]
And, by the way, with locale 8 it is impossible to sign the Guild and, perhaps, some other problems that you are not aware of, but which work on the original server without problems. However, to be honest, this is not a super important problem. The main thing is that we managed to localize this bug.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/azerothcore-wotlk/pull/1
