### ISSUE TITLE
crash worldserver

### ISSUE THREAD

**Issue by tarawow** [liyunfan1223/mod-playerbots#628]
crash worldserver last update playerbots
[Uploading New Text Document (4).txt…]()

**Comment by tarawow** [comment]
[New Text Document (4).txt](https://github.com/user-attachments/files/17451698/New.Text.Document.4.txt)

**Comment by EricksOliveira** [comment]
I was working on this Crash yesterday. But no correction yet.

**Comment by serverwar** [comment]
[3cbd6b378c62+_worldserver.exe_[20-10_20-57-24].txt](https://github.com/user-attachments/files/17452939/3cbd6b378c62%2B_worldserver.exe_.20-10_20-57-24.txt) - I am facing same problems

**Comment by serverwar** [comment]
> [3cbd6b378c62+_worldserver.exe_[20-10_20-57-24].txt](https://github.com/user-attachments/files/17452939/3cbd6b378c62%2B_worldserver.exe_.20-10_20-57-24.txt) - I am facing same problems

@liyunfan1223 Sorry to tag you, you're the guy who solves the DCs

**Comment by serverwar** [comment]
Dude, is what you marked there from my crash log? If so, how did you find this error, could you give an explanation on top of it?

**Comment by avirar** [comment]
No sorry @serverwar, I was working based on original log file provided by @tarawow. Your log indicates the FreezeDetector thread identified that the main world thread had been unresponsive for over 60 seconds

**Comment by hermensbas** [comment]
Please next time add description :)
