### ISSUE TITLE
Not a problem, but waiting for a commit for mod-autobalance #17387

### ISSUE THREAD

**Issue by MRafStudio** [liyunfan1223/mod-playerbots#63]
As I already said, it’s not really a big problem. Just an annoying hindrance to using the module [mod-autobalance](https://github.com/azerothcore/mod-autobalance)

**Comment by evrydayjunglist** [comment]
You can use this commit of autobalance and it should compile successfully: https://github.com/azerothcore/mod-autobalance/tree/9100569ccbc2a86cc118da256da41bb02599c5aa

**Comment by MRafStudio** [comment]
Oh yes, thank you very much - it helped. But I could have guessed it myself! :) Thanks again!
