### ISSUE TITLE
Unknown database 'acore_playerbots'

### ISSUE THREAD

**Issue by mw108** [liyunfan1223/mod-playerbots#633]
**Describe the bug**

I already have the latest AzerothCore installation setup and running. Wanted to add the PlayerBots mod.

So I followed the installation instruction in the `README.md`:

```
cd ~
git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot
cd azerothcore-wotlk/modules
git clone https://github.com/liyunfan1223/mod-playerbots.git --branch=master
cd ..
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j 6
make install
```

Compilation passed without errors.

I updated `~/azerothcore/env/disct/etc/modules/playerbots.conf` and added my MySQL credentials.

Tried to restart `authserver`. Passed.
Tried to restart `worldserver`. Failed.

```
Opening DatabasePool 'acore_playerbots'. Asynchronous connections: 1, synchronous connections: 1.
Could not connect to MySQL database at 127.0.0.1: Unknown database 'acore_playerbots'
Database "acore_playerbots" does not exist
```

**Commit hash**
`mod-playerbots`
599c26bc2ec20729de4f0b52f20596865ffd1ec3

`azerothcore-wotlk`
2e37c1ff1d7fb36d5a003edc44a15a939a2d4667

**To Reproduce**

Have the latest AzerothCore installation setup and running.
Follow the `mod-playerbots` installation instruction.
Update `playerbots.conf` and fill in your MySQL credentials.
Start the `worldserver`.

**Expected behavior**

Worldserver starts.

**Screenshots**

![image](https://github.com/user-attachments/assets/985ca699-c1ff-4c9a-9fce-1ce1aca72095)

**Comment by Bobblybook** [comment]
You do not have the playerbots table in your db - likely because the SQL has not been run. Check the modules/mod-playerbots/sql for the relevant sql files

**Comment by mw108** [comment]
Ok, the trick was to import the `modules/mod-playerbots/sql/playerbots/create_mysql.sql` manually.
