### ISSUE TITLE
Bots dont join Dungeon Finder

### ISSUE THREAD

**Issue by mw108** [liyunfan1223/mod-playerbots#636]
**Describe the bug**

I experience the same problem as in #262:

Bots are not joinining the Dungeon Finder, even though the settings are enabled in playerbots.conf.

When I queue for LFG as DD I instantly get an invite to the dungeon but then I'm sitting there alone and nothing happens. No bots are joining. There are a lot of bots around my level online who could join though.

`AiPlayerbot.RandomBotJoinLfg` is enabled.

```
# Enable LFG for random bots
AiPlayerbot.RandomBotJoinLfg = 1
```

Am I missing something or am I doing something wrong?

**Commit hash**
Latest azeroth-core.wotlk and mod-playerbots commits.

**Screenshots**

[YouTube Video](https://youtu.be/nBGftct_bN8)

**Additional context**

Mods:
- mod-ah-bot
- mod-playerbots

**Comment by Mr-Deadbeat** [comment]
there is a glitch sort of with the dungeon finder code the solution is go to the dungeon finder and set up for a replacement manually by ticking "YES" sometimes it seems to work as intended other times you have to put yourself in the queue manually it will eventually find replacements although it did so previously i've had the same happen to me and the solution was what i described above

also there has been a lot of code changes lately so might be something else causing it as well going to test it tomorrow morning i have created a solo account just to test different scenarios and have 3 characters i will test against Deadmines will update if above solution does not work anymore

**Comment by mw108** [comment]
Thanks for the feedback. I'll also try to analyze the problem further.

What do you mean with `the solution is go to the dungeon finder and set up for a replacement manually by ticking "YES"`?

**Comment by mw108** [comment]
I just purged and reset everything. I've been experimenting with some other modules before. One of which was SoloLfg. I disabled it, recompiled the core but it seemed to still have had an effect. With a fresh setup and only mod-playerbots Lfg works now. 👍

**Comment by Mr-Deadbeat** [comment]
what i mean is if a bot leaves the party when inside the instance go to the dungeon finder and there should be an option to place you in the queue again so it starts searching for new players although the dungeon finder seems to be totally broken now just tested it with my low level account and my level 80 account and i never got a dungeon started even bots decline everytime and i get placed first in the queue all over again rinse and repeat

so i do not know what they have done recently but LFG is borked going to file an issue

**Comment by mw108** [comment]
> what i mean is ...

Yes, I understand now. With the issue I had before there was no such option. I suspect that the SoloLfg module was causing this trouble.

> although the dungeon finder seems to be totally broken now

I managed to get LFG working now with a fresh setup. Had a few LFG runs which went smooth. But I also experienced a similar behavior you are describing:

1. Bots are declining their role in the queue many times. It takes a while until the group is complete.
2. Bots happen to leave the dungeon immediately. When a bot leaves you can search for a replacement with the method you've been describing.

While I find it funny that it mimics the behavior of real players, bots shouldn't do that.

**Comment by Mr-Deadbeat** [comment]
i don't mind if it mimics real life but i sat there for a good 30 minutes trying to get a dungeon group going with my level 80 and it failed every time also i do not use any mods that modifies any LFG functions only using ahbot, weekend xp, and ip tracker and those should not interfere with the dungeon finder functions to my knowledge

either way i posted an issue lets see if the devs can find a solution for the problems
i should mention dungeon finder works as intended if you do a premade group run it only fails if soloing and trying to find a group
