### ISSUE TITLE
Dungeon Finder totally broken

### ISSUE THREAD

**Issue by Mr-Deadbeat** [liyunfan1223/mod-playerbots#637]
**Describe the bug**
Tested dungeon finder to see if there were issues with it and tested both with my low level character and my level 80 my low level character never found any kind of dungeon what so ever

and when i tested my level 80 character for a normal Northrend dungeon a party was being assembled but one or more bots always declined so got put first in queue again over and over and over again so currently it's FUBAR and not working

**Commit hash**
Core: 2e37c1ff1d7fb36d5a003edc44a15a939a2d4667
Bots: 599c26bc2ec20729de4f0b52f20596865ffd1ec3

**To Reproduce**
1. use dungeon finder "i"
2. Click on Find group
3. wait for a group to be found
4. See the problem

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 Server

**Additional context**
if doing a premade group run it works and you get inside the dungeon

**Comment by zbhcn** [comment]
me too , one or more bots always declined

**Comment by Mr-Deadbeat** [comment]
did some more testing and from what i have seen the above issue manifests itself when you queue as a Tank when i changed spec to DPS and tried i got in almost immediately so there is something strange in the code somewhere

**Comment by zbhcn** [comment]
> did some more testing and from what i have seen the above issue manifests itself when you queue as a Tank when i changed spec to DPS and tried i got in almost immediately so there is something strange in the code somewhere

No matter what role I take on, my situation is the same: occasionally quick, but in most cases, always refusing, requiring more than five attempts in line.

**Comment by Mr-Deadbeat** [comment]
managed to get in with Tank just now so it's very much a random thing but with DPS i can get a group going every time only as a Tank do i get issues so something is wrong somewhere should not be near impossible to get a dungeon run as a Tank "Paladin" in this case

**Comment by Mr-Deadbeat** [comment]
closing this issue since there apparently was a issue posted already referring to the same problems
