### ISSUE TITLE
如何限制使用BOT登录他人账号下角色 ？

### ISSUE THREAD

**Issue by CoffeeFantasy** [liyunfan1223/mod-playerbots#64]
如何能禁止随便登录他人账号下的角色，似乎只要是加完好友或者加入到公会，对方如果不在线，就可以任意让bot登录对方角色，是否有地方修改这个设置呢？playerbots.conf好像没找到，求助下大佬！！！！
感谢@liyunfan1223大佬

**Comment by oiuv** [comment]
另外，还可以加对立阵营的人为好友，这算BUG吗？

**Comment by oiuv** [comment]
如果这样，是不是理论上可以上别人的号，盗别人的金币和物品？那这就不太安全了

**Comment by oiuv** [comment]
> This function is not available for the time being. I will add a configuration later to prohibit adding characters from the same guild.

应该是禁止把非RNDBOT的账号加为机器人，除非是自己同一个账号下的角色，否则我把别的玩家以机器人队友的方式组队，然后把他的物品和金币都可以交易过来。

**Comment by oiuv** [comment]
还应该增加一个禁止交易机器人金币的配置，要不能把机器人洗劫一空。

**Comment by CoffeeFantasy** [comment]
> > This function is not available for the time being. I will add a configuration later to prohibit adding characters from the same guild.
> 
> 应该是禁止把非RNDBOT的账号加为机器人，除非是自己同一个账号下的角色，否则我把别的玩家以机器人队友的方式组队，然后把他的物品和金币都可以交易过来。

是这样的，当前可以任意登录bot账号更适合单人模式，多人模式不太适合，希望能增加个配置

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/171
