### ISSUE TITLE
maintenance command with Gem

### ISSUE THREAD

**Issue by gododog85** [liyunfan1223/mod-playerbots#646]
When I use the maintenance command with my Jewelcrafting proficiency at 450, the AI puts a Dragon's Eye in every gem slot and the item disappears.

This is because you can only have a total of 3 Dragon's Eyes in your gear.

 Is it possible to use the maintenance command and only put Epic gems (not Dragon's Eye) in the gem slots, even if my Jewelcrafting skill is 450?

**Comment by Bobblybook** [comment]
Thanks for the report, fixed in #648. Will now autogear up to 3 JC gems only, the rest will fall back to standard gems.
