### ISSUE TITLE
做任务时，机器人无法与任务物品进行交互

### ISSUE THREAD

**Issue by CoffeeFantasy** [liyunfan1223/mod-playerbots#66]
比如我带一个机器人做任务，任务是拾取箱子，机器人无法与任务箱子进行交互。我查了下好像没看到有类似的命令操作，任务箱子无法右键点击（类似采矿命令）
请大佬们指点

**Comment by bing88868** [comment]
请问用什么命令与任务拾取的箱子交互？

**Comment by CoffeeFantasy** [comment]
> 请问用什么命令与任务拾取的箱子交互？

正常是你站在那附近等会bot自己会去，我重新编译后就好了，矿这种的鼠标右键bot会跟上

**Comment by bing88868** [comment]
您说的bot是随机机器人还是自建的角色当机器人，我发现给随机机器人学了挖矿，但并没鸟用，也不会自己挖矿。做任务站任务箱子边上也不会有任何动作。

**Comment by bing88868** [comment]
可能我最新的还没编译，一会编译最新的在看看。

**Comment by CoffeeFantasy** [comment]
用最新的试试吧，我用的是角色机器人这部分交互应该互通的吧，感觉漫游机器人还需要优化等大佬优化完再说
