### ISSUE TITLE
Oculus crash

### ISSUE THREAD

**Issue by Regrad** [liyunfan1223/mod-playerbots#661]
If you leave a group with bots while in Oculus, the server will crash.

**Comment by zbhcn** [comment]
OculusMultipliers.cpp
//line 23 add:
 if (!master)  // Check if master is not null , prevent crash
    {
        return 1.0f;
    }

**Comment by Bobblybook** [comment]
Yes looks like the issue is master nullptr check for mounting multiplier, PR coming shortly
