### ISSUE TITLE
最新版本机器人不会做任何动作

### ISSUE THREAD

**Issue by Sheih2** [liyunfan1223/mod-playerbots#664]
**Describe the bug**
更新到最新版本后，创建的机器人召唤到身边后，不会执行任何动作，类似于不存在
While update to the latest version, new created bots would doing nothing, like they are not exists.
**Commit hash**
dc55bdd8dc3764826ac89db5fa3c58dbe6dd800f

**To Reproduce**
1. creating bots: .playerbots bot addclass paladin
2. init bots: .playerbots bot init=rare NAME1
3. Summon it to side:   call "summon" in party.
4. ask to follow , it would doing nothing(trying "autogear" and "reset botAI").  

**Expected behavior**
BOT should follow, and attack mob.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 
 - 12

**Additional context**

**Comment by Sheih2** [comment]
logs on the server like this:

Initialization Done.
Andrio --- AI Tick ---
Andrio T:levelup
Andrio PUSH:auto maintenance on levelup - 103.000000 (trigger)
Andrio PUSH:follow - 1.000000 (default)
Andrio A:auto maintenance on levelup - PREREQ
Andrio A:auto maintenance on levelup - OK
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio T:summon
Andrio PUSH:summon - 100.000000 (trigger)
Andrio PUSH:follow - 1.000000 (default)
Andrio A:summon - PREREQ
Andrio A:summon - OK
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed
Andrio --- AI Tick ---
Andrio PUSH:follow - 1.000000 (default)
Andrio no actions executed

**Comment by hermensbas** [comment]
Disable smartscale in the configuration

**Comment by hermensbas** [comment]
Pull the latest build or set smartscale on 0 in the configuration. See if that fixes anything for you. Dont think it will but it might.

**Comment by Sheih2** [comment]
> Pull the latest build or set smartscale on 0 in the configuration. See if that fixes anything for you. Dont think it will but it might.

OK, I'll have a try..

**Comment by Grimfeather** [comment]
I also experience this non responsive behaviour.
AzerothCore rev. abd9b4ebb862 2024-10-30 21:43:42 +0800 (Playerbot branch)

alt bots just standing around. not following, not attacking.
giving the follow command has a huge delay, the bots do respond in chat with a "Following!" message,
but no action is taken. they remain idle.
giving the summon command also has a huge delay, they do teleport after a while but then again nothing. 

botActiveAloneSmartScale = 0, BotActiveAlone = 100

something been seriously broken for several weeks now.

**Comment by zhangbo8418** [comment]
> Pull the latest build or set smartscale on 0 in the configuration. See if that fixes anything for you. Dont think it will but it might.

It doesn't seem to be an issue with botActiveAloneSmartScale = 0; here, it’s not following me. Let me reproduce it for you:

https://github.com/user-attachments/assets/d2a86f6b-c3c5-49b5-a7b3-3f289d503092

**Comment by hermensbas** [comment]
I know thereby leave autoscale disabled for now.

**Comment by Sheih2** [comment]
I've test today, https://github.com/liyunfan1223/mod-playerbots/commit/2f0f8ad496fc522c1575d8f89f527f415326780d fixed the issue for me, too.

**Comment by zhangbo8418** [comment]
> I've test today, [2f0f8ad](https://github.com/liyunfan1223/mod-playerbots/commit/2f0f8ad496fc522c1575d8f89f527f415326780d) fixed the issue for me, too.

Is that the issue with random bots being disabled? Can someone like me replicate it?

https://private-user-images.githubusercontent.com/46797568/382629129-d2a86f6b-c3c5-49b5-a7b3-3f289d503092.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Nzc5MDAsIm5iZiI6MTczMDc3NzYwMCwicGF0aCI6Ii80Njc5NzU2OC8zODI2MjkxMjktZDJhODZmNmItYzNjNS00OWI1LWE3YjMtM2YyODlkNTAzMDkyLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAzMzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzMwYmE1YjJhY2ZiNDA1YjY3YjY5YTE1OWFmYzg2NWU2YTU2MWNjZTRhODg1N2QwNTZiZjFlZmQxYzZlNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dUWbumhsK6Z9ms7OQ6O-4aCtFc2-qrcPn4mzJnFK9UI

**Comment by hermensbas** [comment]
update to latest version and read https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration
