### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by gododog85** [liyunfan1223/mod-playerbots#668]
**Describe the bug**
i have compiling error on latest commit

67.65 [ 68%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npc_stave_of_ancients.cpp.o
67.76 [ 68%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npc_taxi.cpp.o
67.78 [ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npcs_special.cpp.o
67.85 [ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/player_scripts.cpp.o
67.91 [ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/server_mail.cpp.o
68.03 [ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/world_script_loader.cpp.o
68.20 [ 69%] Linking CXX static library libscripts.a
74.64 [ 69%] Built target scripts
74.64 gmake: *** [Makefile:136: all] Error 2
------
failed to solve: process "/bin/sh -c git config --global --add safe.directory /azerothcore     && cmake /azerothcore        -DCMAKE_INSTALL_PREFIX=\"/azerothcore/env/dist\"         -DAPPS_BUILD=\"all\"                                     -DTOOLS_BUILD=\"$CTOOLS_BUILD\"                          -DSCRIPTS=\"$CSCRIPTS\"                                  -DMODULES=\"$CMODULES\"                                  -DWITH_WARNINGS=\"$CWITH_WARNINGS\"                      -DCMAKE_BUILD_TYPE=\"$CTYPE\"                            -DCMAKE_CXX_COMPILER=\"clang++\"                         -DCMAKE_C_COMPILER=\"clang\"                             -DCMAKE_CXX_COMPILER_LAUNCHER=\"ccache\"                 -DCMAKE_C_COMPILER_LAUNCHER=\"ccache\"                   -DBoost_USE_STATIC_LIBS=\"ON\"                        && cmake --build . --config \"$CTYPE\" -j $(($(nproc) + 1))     && cmake --install . --config \"$CTYPE\"" did not complete successfully: exit code: 2

Is there any solution?

**Comment by ThomasRambaud** [comment]
Hello, same here.
If you scroll up in the logs you will have the detailed error message.
![{295E66C8-FE18-44B3-8910-9874A67CEF4B}](https://github.com/user-attachments/assets/f49e0b07-2471-4c38-8bb3-7674115f6493)

**Comment by gododog85** [comment]
Ploblem solved. Error was not come grom Playerbot module. It's come from Autobalance mode. I updated that to Latest commit then compile succed
