### ISSUE TITLE
Run via Docker

### ISSUE THREAD

**Issue by rwzdoorn** [liyunfan1223/mod-playerbots#67]
Hi,

First: really appreciate your work! 

I'm running the official AzerothCore now via Docker. In your installation you refer to use 2 git commands (your fork of AzerothCore and Playerbots itself). When I remove the official AzerothCore docker images and do docker-compose up, I only get the 'ac-database' (MySQL). Am I correct that you only need this and the official AzerothCore docker? Or how can I run this?

**Comment by Dreathean** [comment]
Was this resolved and can this be closed?

**Comment by Dreathean** [comment]
Closing as this should be resolved and no update from OP, please open a new issue if this is still a problem.
