### ISSUE TITLE
some Bots not getin dungeon

### ISSUE THREAD

**Issue by leewheel** [liyunfan1223/mod-playerbots#673]
**Describe the bug**
LFG, the player has entered the dungeon, but there is always a certain chance that one or two bots will not enter, and they cannot be summoned

**Commit hash**
The hash of the current commit.

**To Reproduce**
Just lfg and test.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![WoWScrnShot_110424_143217](https://github.com/user-attachments/assets/702539e6-f4a1-4008-8fc3-ca02aedb8ff9)

**Comment by EricksOliveira** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/681

**Comment by WOWSade77** [comment]
I have the same issue. i runb Ubuntu 24.04 lts. everything except 2 major issues so far. This one where on or more bots wont enter Dungeon in 90% of cases where this happens the bots are in fight at the moment (questing / killing ) and they are not entering dungeon. in some cases its only possible to appear next to npc bot and then port back into dungeon, but this wont work always. 
Is there maybe a ways to make a point in config wehere it allows to immidiately force port the NPC BOTS to dungeon ?
There is another problem with Druid tanks and DDs they use the opposite skillsets. When Druid is tank in Dungeon he appears as CAT  .... and when druid is DD he appears as BEAR. 

PLEASE HELP :))))

<img width="1274" alt="NPC_playerbot_LFG_1Player_prio_quest" src="https://github.com/user-attachments/assets/fb70a600-e8a9-4325-ae89-1fa03835ed5e">

**Comment by noisiver** [comment]
Well, this isn't npcbots but I'm going to assume you actually mean playerbots.

Just type summon in party chat.
Druid set to `bear pve` specialization will tank and if set to `cat pve` will dps.

**Comment by WOWSade77** [comment]
thanks a lot @noisiver
that helps :)

**Comment by leewheel** [comment]
OK , I see! thanks
