### ISSUE TITLE
Playerbot Chat

### ISSUE THREAD

**Issue by ApexxCode** [liyunfan1223/mod-playerbots#68]
![Screenshot 2023-11-24 015351](https://github.com/liyunfan1223/mod-playerbots/assets/76696891/cb53cffa-203b-4110-9d7e-a6cc023803e7)

Everything seemed to install okay. I did get quite a bit of warnings importing the MySQL database queries. The bots are speaking in Guild chat, but there's no actual words being presented. Any ideas?

Also - I can't seem to get the following to work:
```
# Prefix for bot chat commands (e.g. follow, stay)
AiPlayerbot.CommandPrefix = "follow, stay"
```

**Comment by Jinxlynx** [comment]
Try reinstalling with a clean database. I had cloned mine over thinking I could save some presets. Didn't work out.

**Comment by evrydayjunglist** [comment]
> Try reinstalling with a clean database. I had cloned mine over thinking I could save some presets. Didn't work out.

Are you saying your bots in guild actually say things without prompt, in guild chat?
I see the same behavior reported by OP. Bots in my guild "say" things in guild chat with no prompt from real player, but there are no words, like in the OP screenshot.
In other contexts, bots do speak words in response to commands, in party and whispers.

**Comment by evrydayjunglist** [comment]
> ![Screenshot 2023-11-24 015351](https://private-user-images.githubusercontent.com/76696891/285524949-cb53cffa-203b-4110-9d7e-a6cc023803e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDk5NDYsIm5iZiI6MTcwMTEwOTY0NiwicGF0aCI6Ii83NjY5Njg5MS8yODU1MjQ5NDktY2I1M2NmZmEtMjAzYi00MTEwLTlkN2UtYTZjYzAyMzgwM2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE4MjcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNjNhNTM5NjZjY2VmMTI1ZWVhMGEzZjRmNGE4YmQyM2M1OGEwODMwMWYyMzkwZTYyMTA2MjI4MTZkNzJkODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjjK13chYGnoaQ2O5Z_hG717kFLwUVah_N-ypLqO6wU)
> 
> Everything seemed to install okay. I did get quite a bit of warnings importing the MySQL database queries. The bots are speaking in Guild chat, but there's no actual words being presented. Any ideas?
> 
> Also - I can't seem to get the following to work:
> 
> ```
> # Prefix for bot chat commands (e.g. follow, stay)
> AiPlayerbot.CommandPrefix = "follow, stay"
> ```

Also, I just noticed the config option you copied.
You should leave AiPlayerbot.CommandPrefix default blank or use a special character, like a slash or period:
AiPlayerbot.CommandPrefix = ""
or
AiPlayerbot.CommandPrefix = "/"

This config is just what goes before your command. If left default blank, in game you would just type "follow" with no quotes. If you chose a special character then in game you would type "/follow" with no quotes, and with whatever special character you put in the config.

**Comment by Jinxlynx** [comment]
At first they didn't do anything. After I reinstalled clean i was able to get the normal reply text from follow ect. But otherwise mine is also a blank reply most of the time.

**Comment by Dreathean** [comment]
This should be mostly all be fixed with Atidot's chat fixes and additions.
