### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Badgermilk0** [liyunfan1223/mod-playerbots#688]
The World Server Daemon continously allocated more memory and never releases any.

Compiled today ~4 hours ago, server has climbed from about 2GB of ram to currently 10 GB of ram.
Growing about 0.5MB per second continously

It has not crashed yet.

No other modules installed.
Only AzerothCore Playerbot Branch and the PlayerBot module.

Random bot count
AiPlayerbot.MinRandomBots = 250
AiPlayerbot.MaxRandomBots = 500

No other settings changed from "default"

Running on Win11

**Comment by zhangbo8418** [comment]
> Noticed that there was a new commit since I compiled from hermensbas regarding bot scaling.
> 
> Recompiling and will leave it on for a few hours to see if it is the same on the new build.

It seems normal to me. When the AzerothCore map is fully loaded, the memory usage is about 10G.

**Comment by Badgermilk0** [comment]
Server was online for the entire night with about 1000 bots, no crash.
I'm assuming this is a non-issue.

**Comment by PaoloBenigni** [comment]
A few things, some memory increase over time is typical up to a certain limit. 
There is a random movement cache that exists for npcs that when active (default is on for DontCacheRandomMovementPaths in worldserver). Will cause memory increasing. That coupled with bots moving to different maps will also cause those to get loaded. Im not sure where it tops out, but a system with < 16 gb of ram can very easily find itself maxing out with everything loaded and many bots in play.
