### ISSUE TITLE
State of Battlegrounds

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#69]
Spent some time testing the battlegrounds out of curiosity, here are my current findings:

WSG: Works pretty dang well. No major issues here. Capturing flags, attacking flag bearers, all working well.

AB: A few major issues: Alliance stuck on Stables, enemy not all attacking on sight right away, Horde skipping Farm, Horde also not assaulting Stables at all

![WoWScrnShot_112623_133630](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/c16e3e88-74c7-4a28-bb3f-4d78791c755c)
![WoWScrnShot_112623_133633](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/259f0315-aea8-4876-b5d3-056c29420e17)

AV: Similarly a few major issues here. At the start, Alliance went heavy defense without defending general or front bases.

![WoWScrnShot_112623_135819](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/75ce8807-0f37-49ca-86ad-317e371bde97)

Horde did well defeating the General as well as capturing bases and graveyards, though they went REALLY all-in each step of the way. The alliance failed to defend or capture anything.

![WoWScrnShot_112623_141756](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/4e38c2ed-70bd-49b3-9821-7fc5c3eec2c5)

The other big issue is significant flying underground and over ground on this map. 

![WoWScrnShot_112623_135934](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/afdeea01-ac66-4094-b79c-6a9cb51a009e)
![WoWScrnShot_112623_141417](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/8a5f45ef-5b5d-478e-bf76-98d7600d10e7)
![WoWScrnShot_112623_142154](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/30108fb7-9219-4691-9c69-95a32ddef683)

All that said, very excited by the major progress made on this module and looking forward to future improvements!

**Comment by liyunfan1223** [comment]
Thanks for testing, very valuable and specific information! I have understood the reason for the flying and will resolve this issue as a priority.

**Comment by zbhcn** [comment]
非常期待

**Comment by zbhcn** [comment]
@liyunfan1223 顺便适配一下Azerothcore的最新代码吧，你的已经是3个月前的了

**Comment by Dreathean** [comment]
Awesome, you rock! And zbhcn the reason I think Liyunfan has not updated is due to a bug getting heavily impacted (specifically with the bots maybe?) causing extreme server lag and I'm not 100% sure if that bug has been resolved yet or not. It is strange because I'm not noticing any issues being up to date on my non-playerbot server.

From https://github.com/azerothcore/azerothcore-wotlk/issues/17580

**Comment by Dreathean** [comment]
@liyunfan1223 It does look like that issue shouldn't be currently present as judging by this it was only temporarily an issue when they tried passing this person's original PR which they subsequently removed until it was improved:

https://github.com/azerothcore/azerothcore-wotlk/pull/17843
![image](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/6829251f-e067-4dde-9eb6-f1c2f4a3d38d)

So as far as I'm aware you should be good to update to latest without running into that issue.

**Comment by Twiggstar** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/21956275/adf0ab45-2611-434a-8fa8-7eddf318ac1d)

Arathi basin, bots are still stuck on stables

**Comment by Dreathean** [comment]
@liyunfan1223 Is there anything I can do to help further with this? I'm assuming it has something to do with https://github.com/liyunfan1223/mod-playerbots/blob/master/src/strategy/actions/BattleGroundTactics.cpp and updating to Azerothcore?

I did notice 
![image](https://github.com/liyunfan1223/mod-playerbots/assets/132776330/49d96319-26be-4468-bc3c-1e848f241cb2)
which I thought was interesting but doesn't make sense as this just leads the Horde dominating the Alliance?

I know you have a lot on your plate you're already working on and unfortunately I don't know enough to understand what is wrong with this code, just trying to see if I can be of any assistance!

**Comment by Zerkenn** [comment]
In BattleGroundTactics.cpp,  The alliance code is checking the ownerId of the objective and not the state causing bots to get stuck at stables. Applying the fix in the screenshot below makes it so alliance bots don't get stuck at stables, however there is still much work to be fixed as they eventually capture some objectives and then both teams get stuck defending and never attack.

![image](https://github.com/liyunfan1223/mod-playerbots/assets/88915224/4e7d4fc2-b8a4-4a07-b6c6-3a6a5e1028de)

**Comment by Dreathean** [comment]
That's a nice find! At least some progress, maybe submit a pull request for Liyunfan?

**Comment by jpmckown** [comment]
> In BattleGroundTactics.cpp, The alliance code is checking the ownerId of the objective and not the state causing bots to get stuck at stables. Applying the fix in the screenshot below makes it so alliance bots don't get stuck at stables, however there is still much to be fixed as they eventually capture some objectives and then both teams get stuck defending and never attack.
> 
> ![image](https://private-user-images.githubusercontent.com/88915224/337935950-4e7d4fc2-b8a4-4a07-b6c6-3a6a5e1028de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjQ1ODEsIm5iZiI6MTcxODU2NDI4MSwicGF0aCI6Ii84ODkxNTIyNC8zMzc5MzU5NTAtNGU3ZDRmYzItYjhhNC00YTA3LWI2YzYtM2E2YTVlMTAyOGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE4NTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NTIyMGZmZjI3MDBkYjJiMWZhYzhmZDY2MjE4MmE4NjdhNTlhMjgxMWFhZGRlNDVmYzY2ODA4MzQyYzQ0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S9y3e8lOddY2J0u7xiSda1Kg11uzu7DQf1lGLxsBdro)

I gave this a try and the bots just went piecemeal to Mine and were immediately gibbed. Then they just parked themselves right back at stables. 

I actually gutted the whole logic in BattleGroundTactics.cpp and ported over the current Playerbots... and it had no effect. Ally bots all parked themselves at Stables. Just for S&Gs I hard coded Horde bots to park themselves at Farm in BattleGroundTactics.cpp, and the Horde bots 4 capped anyways. At this point I have to assume someone has hard-coded a Horde 4 cap in AB somewhere outside of Tactics because the Horde bots won't go near stables (they swarm Mine honestly) and the Ally bots stay at stables.

**Comment by Dreathean** [comment]
That is a really great find! Would you like to submit a PR for that?

**Comment by Dreathean** [comment]
@jpmckown can you submit a PR with these changes for Liyunfan? If not I will see if I get a chance this weekend.

**Comment by kevin-coyle** [comment]
I tested out the changes that @jpmckown and @Zerkenn put in. Worked pretty well! Only played one match (and lost as horde).

**Comment by shockcollar95** [comment]
Does anyone know if these changes have already been implemented in the repo?

**Comment by Dreathean** [comment]
They have not been yet, anyone is welcome to submit a PR for them, if I get a chance later this week I will but definitely feel free to submit them if you can!

**Comment by Dreathean** [comment]
After a PR is made for those changes, I plan on closing out this issue as some of the problems have been fixed and it will likely be better moving forward to have the remaining bugs split into independent issues.

**Comment by fuzzdeveloper** [comment]
ok i've fixed it but the bots cant get stuck at lumber mill (and probably mine) going back and forth and I think its because they're being switched between defence/attack roles too quickly (and in general getting objective reset too often, before they can actually get between objectives), I will see what I can do about that

**Comment by Dreathean** [comment]
That is great progress! Thank you for looking into it Fuzz. Is it possible to add some sort of random/range of delay between defence/attack/changing objectives? I'm surprised there isn't one already, I just looked through the code and there doesn't seem to be - though I am no coding expert so take that with a huge grain of salt lol.

**Comment by fuzzdeveloper** [comment]
Yeah I tried that (actually did a rewrite of that code completely at one stage) but turns out not to be related to objective selection at all, its pathing (which I found out after removing all randomness and just making them go to nearest enemy/neutral objective and they STILL got stuck up at blacksmith). Anyway I found some additional AB waypoints on another bot (with a very similar codebase and identical waypoints for the rest of AB) and that seems to help them get down.

**Comment by Dreathean** [comment]
Closing as many of these issues have been resolved as of https://github.com/liyunfan1223/mod-playerbots/pull/298; a few do remain to my knowledge such as tactics for AV, but issues should be opened up for any remaining specific issues. Thanks to everyone who helped resolve these issues!

**Comment by jpmckown** [comment]
Sorry I haven’t been responsive here @Dreathean, I’ve been traveling. I spent some time on the AV issue and have isolated it to a certain segment of pathing where the bots (both sides do it) will start back tracking for some reason (as far as I can tell they shouldn’t be). Haven’t had time to determine why. 

Thanks for pushing all this stuff @Dreathean

**Comment by Dreathean** [comment]
Of course! If you're interested, join us over on the discord and we can go over some of your findings with other devs like Fuzz and hopefully we can get it figured out! https://discord.gg/rVqTfqjT
