### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#701]
Gets a clang error with latest update 

clang: fatal error: clang frontend command failed with exit code 134 (use -v to see invocation)

Im compile with no mods

**Comment by noisiver** [comment]
You need to include the actual error message(s).

**Comment by EricksOliveira** [comment]
I'm having these errors after updating the Core to the latest rev.

`Erro LNK2001	símbolo externo não resolvido "public: virtual void __cdecl WotlkDungeonCoSStrategy::InitTriggers(class std::vector<class TriggerNode *,class std::allocator<class TriggerNode *> > &)" (?InitTriggers@WotlkDungeonCoSStrategy@@UEAAXAEAV?$vector@PEAVTriggerNode@@V?$allocator@PEAVTriggerNode@@@std@@@std@@@Z)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual void __cdecl WotlkDungeonCoSStrategy::InitMultipliers(class std::vector<class Multiplier *,class std::allocator<class Multiplier *> > &)" (?InitMultipliers@WotlkDungeonCoSStrategy@@UEAAXAEAV?$vector@PEAVMultiplier@@V?$allocator@PEAVMultiplier@@@std@@@std@@@Z)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl ExplodeGhoulTrigger::IsActive(void)" (?IsActive@ExplodeGhoulTrigger@@UEAA_NXZ)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl ExplodeGhoulSpreadAction::Execute(class Event)" (?Execute@ExplodeGhoulSpreadAction@@UEAA_NVEvent@@@Z)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl EpochStackAction::isUseful(void)" (?isUseful@EpochStackAction@@UEAA_NXZ)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl EpochStackAction::Execute(class Event)" (?Execute@EpochStackAction@@UEAA_NVEvent@@@Z)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl EpochRangedTrigger::IsActive(void)" (?IsActive@EpochRangedTrigger@@UEAA_NXZ)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK2001	símbolo externo não resolvido "public: virtual bool __cdecl DalronnNontankTrigger::IsActive(void)" (?IsActive@DalronnNontankTrigger@@UEAA_NXZ)	worldserver	C:\Server\Build-Playerbot\src\server\apps\modules.lib(AiObjectContext.obj)	1		

Erro	LNK1120	8 externo não resolvidos	worldserver	C:\Server\Build-Playerbot\bin\RelWithDebInfo\worldserver.exe	1`

**Comment by davvvve1** [comment]
I just redownload it again and now its working . Mabye the update was fu. Close this
