### ISSUE TITLE
Characters are not marked as offline

### ISSUE THREAD

**Issue by d-christ** [liyunfan1223/mod-playerbots#710]
**Describe the bug**
When a player logs out the character is still marked as online (In the "characters" table, the value "online" is not updated to "0". it stays at "1". This is only resetted if the server is restarted

**Commit hash**
abd9b4ebb862354dbfce18fbe857bf61932aca8d

**To Reproduce**
1. Log in
2. Log out
3 Look at "characters"-Table for the character just logged in. "Online" should be "0", but is "1"

**Expected behavior**
"characters"."Online" should be "0" when character is logged off

**Additional context**
AC> AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 1369.
Connection peak: 1.
Server uptime: 12 hour(s) 47 minute(s) 45 second(s)
Update time diff: 10ms. Last 500 diffs summary:
|- Mean: 13ms
|- Median: 11ms
|- Percentiles (95, 99, max): 26ms, 30ms, 32ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80040
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-125-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /home/azerothcore/azerothcore-wotlk/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/azerothcore/azerothcore-wotlk/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/azerothcore/azerothcore-wotlk/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-aoe-loot
|- mod-breaking-news-override
|- mod-eluna
|- mod-guildhouse
|- mod-playerbots
|- mod-transmog

**Comment by noisiver** [comment]
This isn't specific to playerbots. The core has this issue to begin with.

**Comment by Dreathean** [comment]
I saw he posted this issue originally on the core, and they closed it immediately when they saw he had playerbots module, saying it must be a playerbots only issue. https://github.com/azerothcore/azerothcore-wotlk/issues/20545

Though admittedly the person that reviewed it did say they couldn't replicate the issue on base core.

**Comment by noisiver** [comment]
Well, I know there is no code in the core that marks a character as offline (online = 0) when they log out. It only ever does this on startup. I know this for sure. There is even a PR draft open to address this in the azerothcore repo.

**Comment by d-christ** [comment]
I didnt test it on a clean Installation, but i think i will do that and then try to reisen the Ticket.

If there is a PR i maybe just merge that into my local code...

Thanks for the hint. And @Dreathean: thanks for your comment. Highly appreciated!

**Comment by noisiver** [comment]
I actually ran tests on stock AC. I can't replicate it anymore. It was an issue before but I can't get it to happen anymore no matter what I do. I don't know if this is core-side playerbots or the module but it isn't azerothcore itself.

**Comment by d-christ** [comment]
We tried it on an installation with playerbots and ah-bot only.

**Comment by d-christ** [comment]
This is the pull-Request: https://github.com/azerothcore/azerothcore-wotlk/pull/20367

Could we use this on the playerbot-branch?

**Comment by zbhcn** [comment]
> I actually ran tests on stock AC. I can't replicate it anymore. It was an issue before but I can't get it to happen anymore no matter what I do. I don't know if this is core-side playerbots or the module but it isn't azerothcore itself.

Yes, it isn't azerothcore itself core-problem. it's playerbots only

**Comment by hermensbas** [comment]
As @zbhcn stated

**Comment by d-christ** [comment]
@hermensbas : ehrm... @zbhcn stated that this is a playerbots problem. Why did you close the ticket?

Little update from my personal installation: i tried the "fix" from the fork manually. It didnt work. Everyone is still marked online from the first login.

**Comment by noisiver** [comment]
I don't know if it's an issue on the core side or the module but it is indeed an issue with playerbots and not stock azerothcore.

**Comment by zbhcn** [comment]
i tried the "fix" from the fork manually. It didnt work too, So this fix fork doesn't solve this problem at all

**Comment by hermensbas** [comment]
ow haha mistake

**Comment by locchi93** [comment]
It's the first time I've seen the codebase, so I'm not sure what I'm saying... I think the module's implementation of `OnDatabaseSelectIndexLogout` is wrong, it takes `CHAR_UPD_CHAR_ONLINE` as statement which however sets the character online and not offline... This part differs from the original azerothcore repo in which in fact it is not possible for more than one character from the same account to be online (in fact, `CHAR_UPD_ACCOUNT_ONLINE` is used there which sets all the characters in the account to offline when any character logs out).

**Comment by moncat2005** [comment]
Maybe a temporary solution is to increase the criteria for online judgment
It seems like this
`SELECT * FROM characters WHERE characters.online = 1 and characters.account in (SELECT acore_auth.account.id FROM acore_auth.account WHERE acore_auth.account.online = 1);`

**Comment by noisiver** [comment]
I actually found the issue and am working towards a solution.

**Comment by noisiver** [comment]
Though, I'm seeing things that shouldn't happen so I might need some time with this.

**Comment by locchi93** [comment]
I think a change is needed in the azerothcore fork to add a statement like this:
`PrepareStatement(CHAR_UPD_CHAR_OFFLINE, "UPDATE characters SET online = 0 WHERE guid = ?", CONNECTION_ASYNC);`

And modify the module so that the `OnDatabaseSelectIndexLogout` implementation takes this statement instead of the current `CHAR_UPD_CHAR_ONLINE`.

Could it work? I don't have a development setup to test this at the moment.

**Comment by noisiver** [comment]
No, that's not the best solution. I know how to fix it, I just want the best possible solution.

**Comment by noisiver** [comment]
Well, it's not a bad solution - not bad at all. I've given it a grand total of 2 minutes of thinking and it might be the best we can utilize. I'll play around for a bit to see if another one is better, otherwise I'll try that.

**Comment by noisiver** [comment]
I'll try that one because whatever solution I think of requires more changes to the core. Do you want to create the PR if it works as intended or is it enough if I do and credit you?

**Comment by d-christ** [comment]
"This part differs from the original azerothcore repo in which in fact it is not possible for more than one character from the same account to be online"

-> Could it be, that this works because of the "Playerbot"-functionality? I can call my twinks as bots so multiple characters of the same account can be online. 

I'm not familiar with the code or how this works. it just came to my mind!

**Comment by locchi93** [comment]
@noisiver If it works, go ahead without any problems! If it doesn't work I'll try to set up a development setup so I can study the project a bit and contribute if I can ;)

**Comment by noisiver** [comment]
It works. I'll make sure to credit you with the PR because 99.99% of it was you. It really is the simplest solution and it isn't hacky so it is the best one.

**Comment by d-christ** [comment]
@locchi93 : amazing analyzing skills. Thanks a lot! :)

**Comment by d-christ** [comment]
But isnt this the same solution this PR from the core-Project provides?:

https://github.com/azerothcore/azerothcore-wotlk/pull/20367/files

I tried that, and it didnt work.

**Comment by noisiver** [comment]
The module overrides the statement used, and that was the final piece of the puzzle. I can't log in random bots for some strange reason, it just says "60 new bots" forever and ever but I tried it with 24 altbots + me and it always set online to 0 when I logged out.

**Comment by locchi93** [comment]
Tried master today on my server, it seems to work fine! I think that the issue can be closed, have you tried @d-christ ?

**Comment by d-christ** [comment]
Yes, works for me, too. Thanks!
