### ISSUE TITLE
Instant Worldserver Crash when Bots entering FOS

### ISSUE THREAD

**Issue by R0thgas** [liyunfan1223/mod-playerbots#718]
Well, as in the title. The worldserver instant crashs with an "segmentation error" when bots entering FOS.

**To Reproduce**
add some Bots and enter FOS or enter fos and summon bots

The Worldserver should not crash when Entering FOS, and the new added strategies should work, too (as i couldnt tested them atm)

Azerothcore is hosted on an ubuntu 24.04 Ubuntu LXC via Proxmox. 
if specific hardwareinfo needed please give me a info

**Comment by R0thgas** [comment]
@moncat2005 
Already testet I shared the startquest with the Bots, they accept it. 
In an earlier Version (when there was no strategies for FOS) the Bots could enter FOS.

**Comment by serverwar** [comment]
Put try in the function, if there is an error it will ignore it and not crash the server.

**Comment by noisiver** [comment]
This should be fixed now so I'm closing this issue.
