### ISSUE TITLE
使用.server restart xxxx重启命令后，worldserver.exe直接崩溃。

### ISSUE THREAD

**Issue by QianXiPs** [liyunfan1223/mod-playerbots#72]
刚输入“.server restart 14400”时，控制台显示所有的PlayerBots都立刻登出了游戏，而立马又有一些PlayerBots开始登录游戏。只登陆了20个左右，就没有响应了，服务器也假死崩溃了。
使用mod-auto-shutdown重启时也是这样，开始提醒的时候worldserver就崩溃了。
服务器提示重启时，所有机器人都登出的逻辑是在哪里？可以去掉吗？

**Comment by MRafStudio** [comment]
我同意，我也注意到了类似的问题

**Comment by liyunfan1223** [comment]
Fixed in core https://github.com/liyunfan1223/azerothcore-wotlk/commit/80a8896dfeeb9fa2943822f77bbb5ea4ea53a2c7
