### ISSUE TITLE
Can bots be more inactive ?  

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#722]
What i ment is that randombots only spawn when gets an invite ? Like with dungeons and bgs/arena and thru search when pressing social?

**Comment by hermensbas** [comment]
Maybe this helps answering your question? https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration

**Comment by davvvve1** [comment]
> Maybe this helps answering your question? https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration

Thanks , mate !

**Comment by davvvve1** [comment]
> Maybe this helps answering your question? https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration

My server has laged so i stop playing wow . Now it runs beautiful .  Next time check the wiki .  THANKS alot for the answer!

**Comment by hermensbas** [comment]
your welcome
