### ISSUE TITLE
Acore Delete a variable DATA_ANUB_GATE = 104

### ISSUE THREAD

**Issue by leewheel** [liyunfan1223/mod-playerbots#725]
**Describe the bug**
![image](https://github.com/user-attachments/assets/9a4a5eb5-31a6-4078-b79e-af46c61c38a4)

**Commit hash**
The hash of the current commit.

**To Reproduce**
Acore just delete a variable DATA_ANUB_GATE = 104, This caused the Naxx part of the program to fail, and also caused the Raid's NAXX strategy to fail.

**Expected behavior**
Adjust the trigger conditions and fix BUG

**Screenshots**
![image](https://github.com/user-attachments/assets/73610e3a-506b-4a71-bc17-dffc8290d634)
![image](https://github.com/user-attachments/assets/ff6c4b17-58ca-4b64-978d-5f0fbf4f9036)

**Desktop (please complete the following information):**
Womndows 10

**Additional context**
None

**Comment by noisiver** [comment]
This has never been an issue for me in the past and still isn't. The code shown is out-of-date and it still uses `DATA_ANUB_GATE` just like the original source of AzerothCore.

Maybe it's your Womndows!
