### ISSUE TITLE
Utgarde keep 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#726]
*When i log in the bots started to flying .  Any config i have done wrong = ?

**Comment by davvvve1** [comment]
> *When i log in the bots started to flying . Any config i have done wrong = ?

And i noticed on the server info the ms spiked from 25 to 43 and went to 65 ms until i rebooted

**Comment by davvvve1** [comment]
> > *When i log in the bots started to flying . Any config i have done wrong = ?
> 
> And i noticed on the server info the ms spiked from 25 to 43 and went to 65 ms until i rebooted

Close this . Change Threadpool to 2 and problen solved  -

**Comment by maikale** [comment]
I'm having a lag problem too 250 bots after 10 15 minutes it becomes scary where I'm messing up
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
Number Of Processors: 24
Physical Memory: 65457 MB
*** Operation System ***
Windows 10 Professional

**Comment by serverwar** [comment]
![image](https://github.com/user-attachments/assets/1064534b-667f-4c61-bd6a-0ee256f867ee)
Man, I never had a lag problem using 200 bots at the maximum

**Comment by davvvve1** [comment]
> I'm having a lag problem too 250 bots after 10 15 minutes it becomes scary where I'm messing up *** Hardware *** Processor: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz Number Of Processors: 24 Physical Memory: 65457 MB *** Operation System *** Windows 10 Professional

https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration  . I did that and no lag

**Comment by davvvve1** [comment]
> > I'm having a lag problem too 250 bots after 10 15 minutes it becomes scary where I'm messing up *** Hardware *** Processor: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz Number Of Processors: 24 Physical Memory: 65457 MB *** Operation System *** Windows 10 Professional
> 
> https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration . I did that and no lag

https://github.com/liyunfan1223/mod-playerbots/issues/722

**Comment by davvvve1** [comment]
unload strategy for utgarde and still that behaviour .

**Comment by davvvve1** [comment]
Updated my worldserver.conf  .  Now it works .    Close this

**Comment by maikale** [comment]
> Updated my worldserver.conf . Now it works . Close this

Share how

**Comment by davvvve1** [comment]
> I'm having a lag problem too 250 bots after 10 15 minutes it becomes scary where I'm messing up *** Hardware *** Processor: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz Number Of Processors: 24 Physical Memory: 65457 MB *** Operation System *** Windows 10 Professional

If you open up your playerbots.conf  or playerbot.conf.dist  and change this lines to mine you  can try . 
AiPlayerbot.MinRandomBots = 3000
AiPlayerbot.MaxRandomBots = 3000

AiPlayerbot.RandomBotJoinLfg = 1

AiPlayerbot.RandomBotAutoJoinBG = 0

AiPlayerbot.BotActiveAlone = 10
AiPlayerbot.botActiveAloneSmartScale = 0
AiPlayerbot.botActiveAloneSmartScaleWhenMinLevel = 1
AiPlayerbot.botActiveAloneSmartScaleWhenMaxLevel = 80
AiPlayerbot.ProbTeleToBankers = 1
#AiPlayerbot.RandomBotMaps = 0
