### ISSUE TITLE
SQL/DATA Folder

### ISSUE THREAD

**Issue by Raz0r1337** [liyunfan1223/mod-playerbots#736]
**Describe the bug**
I perform a new fresh clone of the source and after compiling there will be errors on the start of the core that the SQL files not found. The core searches it on the old path not data/SQL.

**Commit hash**
4cd23792db

**To Reproduce**
Simple clone the source and mod-playerbot.
Then compile it and start the core.

**Expected behavior**
It seems that already be the old path left in the code.

**Desktop (please complete the following information):**
 Tested on Windows 11 and linux Ubuntu server 24.04.1

**Comment by hermensbas** [comment]
Did you update our core and our mod to the latest version?

**Comment by Raz0r1337** [comment]
Of course I use the newest version.
A friend of mine has the same issue.
And I have tested this on two machines fresh.

It seems that parts of the old code still present and link to the old location of the SQL files.

**Comment by noisiver** [comment]
```
>> Applying update "world_charsections_dbc.sql" '1419FC7'...
>> Applying update "world_emotetextsound_dbc.sql" 'DA8D68F'...
>> Applying update "world_playerbots_rpg_races.sql" '04DC4B0'...
>> Applied 330 queries. Containing 972 new and 0 archived updates.
 
Opening DatabasePool 'acore_playerbots_3'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool 'acore_playerbots_3' opened successfully. 2 total connections running.
 
Updating Playerbots database...
DBUpdater: Given update include directory "C:/Users/Revision/Desktop/azerothcore/world3/source/modules/mod-playerbots/sql/playerbots/updates" does not exist, skipped!
DBUpdater: Given update include directory "C:/Users/Revision/Desktop/azerothcore/world3/source/modules/mod-playerbots/sql/playerbots/custom" does not exist, skipped!
DBUpdater: Given update include directory "C:/Users/Revision/Desktop/azerothcore/world3/source/modules/mod-playerbots/sql/playerbots/archive" does not exist, skipped!
>> The file '2024_08_07_00.sql' was applied to the database, but is missing in your update directory now!
Deleting orphaned entry '2024_08_07_00.sql'...
>> Playerbots database is up-to-date! Containing 1 new and 0 archived updates.
```
As you can see the SQL files for the world database applied fine but the playerbots database didn't at all. As I have the data/sql folder inside the module I know for sure that I also have the latest update. I don't use the auto updater but decided to test it and can confirm this for the playerbots database but not characters or world.

**Comment by Raz0r1337** [comment]
I only mean the Playerbot DB.
World, char and auth updates and populating works fine.

But why the new data/SQL path don't work?

My workaround is to move the SQL folder in the mod-playerbot folder and it works.

But these path was changed and I find this should work.

**Comment by noisiver** [comment]
I don't know why it isn't working. I'm diagnosing it, but I'm having troubles finding where it's set. I'm searching through both the module and the core and can't find anything (yet at least).

**Comment by Raz0r1337** [comment]
I am searching for it to. If I find anything I will send it here. 😉

**Comment by noisiver** [comment]
I found it

**Comment by noisiver** [comment]
Bash should've made an update file for it but didn't so that's the only fix. It won't affect your bots or anything so don't worry about that.

**Comment by noisiver** [comment]
It won't fix itself but drop the table and import the file again from the base folder. I just confirmed that fixed it.

**Comment by Raz0r1337** [comment]
This shouldn't make problems with a new clean DB and a new compiled core on another machine. But it makes the same errors.

I will try what you said and answer if I am ready. 😉

**Comment by Raz0r1337** [comment]
It works.
Thank you very much for helping by this. 👍
