### ISSUE TITLE
Playerbots cause server to crash during Warsong gulch battleground

### ISSUE THREAD

**Issue by Meteorika** [liyunfan1223/mod-playerbots#737]
Happens randomly; bots join the queue, start buffing, match starts, sometimes match ends without crashing. My solo server never crashed with playerbots in the world or dungeons, it started to happen when I enabled [`AiPlayerbot.RandomBotAutoJoinBG = 1`], server crashes with, or without a living player on wsg bg. 

Changing `MapUpdate.Threads` from 1 to 8, `ThreadPool` to 8, and `MaxCoreStuckTime` to 30 helped a bit, server's crashes became a bit less frequent from my observation. Expected behavior: server doesn't crash during battleground populated with playerbots.

> Revision: AzerothCore rev. c3be0fa2a8b4+ 2024-08-05 01:22:16 +0800 (Playerbot branch) (Win64, Release, Static)
> Date 24:11:2024. Time 9:45 
> //=====================================================
> *** Hardware ***
> Processor: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
> Number Of Processors: 16
> Physical Memory: 33449588 KB (Available: 21490924 KB)
> Commit Charge Limit: 35546740 KB
> 
> *** Operation System ***
> Windows 10 Home Edition (Version 10.0, Build 19045)
> 
> //=====================================================
> Exception code: C0000005 ACCESS_VIOLATION
> Fault address:  00007FF61F211E8A 01:0000000000940E8A E:\Torrent\Archief\AzerothCore-WotLK\AzerothCore-x64-WotLK-09.08.24\worldserver.exe

**Comment by noisiver** [comment]
Compiling in Release generates useless crash logs. Compile in RelWithDebInfo to get anything readable.

**Comment by zbhcn** [comment]
[https://github.com/liyunfan1223/mod-playerbots/issues/715#issue-2660522699](url)MapUpdate.Threads >1 will crash

**Comment by noisiver** [comment]
On Windows it will. I've been running my server for over a week with MapUpdate.Threads set to 1 and there are no issues.

As I've said before though, changing ThreadPool does basically nothing in relation to the bots.

**Comment by Meteorika** [comment]
It crashes faster and more frequent when `MapUpdate.Threads = 1` 
currently learning how to compline with RelWithDebInfo

**Comment by noisiver** [comment]
I know that battlegrounds can crash if you are in it as a GM, at least it has happened to me many, many times. Aside from that I never have crashes though.

**Comment by Meteorika** [comment]
Issue resolved by reinstalling everything from the scratch, using liyufan12223's branch of azerothcore
