### ISSUE TITLE
Soulstone support

### ISSUE THREAD

**Issue by kadeshar** [liyunfan1223/mod-playerbots#738]
WoW Wotlk have combat ressurection system which is not used by bots and raids envoirment requires that.
For example:
Now warlock can cast "Create Soulstone" (spell id: 47884) which creates item "Demonic Soulstone" (item id: 36895).
Using this item on other bot is bugged and dont work correctly. 
Only way i select target bot and use command "u Demonic Soulstone" but sometimes bot using that on himself and rarely on targeted bot.
Even when targeted bot get aura "Soulstone Resurrection" (spell id: 47883) and died he dont use soulstone. Command "do accept ressurect" dont work.

![obraz](https://github.com/user-attachments/assets/3a43c2a5-a2c0-43e9-9a38-26b95404709e)

Resolution:

Best:
Add in generic warlock strategy support for marking soulstone target and using automatic "Demonic Soulstone" when cooldown off (15 minutes)
Add in dead strategy support for using soulstone when possible

Alternatives:
Allow using "Demonic Soulstone" on other bot via command and command "do use soulstone" to accept ressurection using this way.

**Comment by kadeshar** [comment]
I added PR with simple soulstone implementation which allow casting warlock soulstone on master.

**Comment by hermensbas** [comment]
merged
