### ISSUE TITLE
Huge laggs starting to occur after 1-2 hours 

### ISSUE THREAD

**Issue by nl-saw** [liyunfan1223/mod-playerbots#743]
**Describe the bug**
Server running with 3000 bots, when started and all bots have initialized, the DIFF is about 30-45 ms without laggs. This generally stays the same over time but after 1-2 hours (depending on the amount of bots and the inactivity settings) there start to be huge laggs, increasing in both intensity and frequency (up to 6 seconds and beyond!). When you start noticing the issue it becomes exponentially worse, quickly. At that point the game becomes basically unplayable. When lowering the amount of bots, and/or decrease their activeness/increase idling times the problem is just delayed. After a server restart all is fine once again for 1-2 hours and the cycle repeats. Can someone help me with what I can do to help pinpoint the problem? I am not a hardcore developer, but I can manage my way around with some directions.

**Commit hash**
AzerothCore rev. 1294d79764e3 2024-11-25 23:22:31 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**To Reproduce**
1. Start a server with 3k bots.

Only following mods are enabled: 
- mod-autobalance
- mod-dynamic-xp
- mod-rdf-expansion
- mod-solo-lfg

2. Wait (or play) for 1-2 hours
3. Observe insane DIFF times up to 6+ seconds.

**Expected behavior**
There should be no laggs of 1+ seconds happening over time.

**Screenshots**
n/a

*** Hardware ***
Processor: AMD Ryzen 7 7800X3D 8-Core Processor
Number Of Processors: 16
Physical Memory: 64 GB

*** Operation System ***
Ubuntu 24.04.1 LTS

**Additional context**
I haven't played around with Playerbots for around a year, so I have 0 clue where this problem might have started for me meanwhile, but this behavior was not happening back then. My server's config files attached.
For MySQL I basically just increased the innodb_buffer_pool_size to 32 GB, and I do not see any performance issue with it.

[playerbots.conf.txt](https://github.com/user-attachments/files/17921641/playerbots.conf.txt)
[worldserver.conf.txt](https://github.com/user-attachments/files/17921648/worldserver.conf.txt)

**Comment by davvvve1** [comment]
#playerbotsconfig#
AiPlayerbot.MinRandomBots = 3000
AiPlayerbot.MaxRandomBots = 3000

AiPlayerbot.RandomBotJoinLfg = 1

AiPlayerbot.RandomBotAutoJoinBG = 0

AiPlayerbot.BotActiveAlone = 10
AiPlayerbot.botActiveAloneSmartScale = 0
AiPlayerbot.botActiveAloneSmartScaleWhenMinLevel = 80
AiPlayerbot.botActiveAloneSmartScaleWhenMaxLevel = 80
AiPlayerbot.ProbTeleToBankers = 1
Maps where bots can be teleported to

#AiPlayerbot.RandomBotMaps = 0 (---- Yes with the #
 
Change mapupdate to 4 in the worldconfig

Not to solve it but works for me.   I have some crashes but i belive its cause that it is alot of bots in one city .  But can play like 10 hours .

**Comment by davvvve1** [comment]
https://github.com/liyunfan1223/mod-playerbots/wiki/Playerbot-Configuration

**Comment by maikale** [comment]
I had this problem too, I changed MapUpdate.Threads = 6 just that and I no longer have problems.
4 days running with 3500 bots and I have no problem

**Comment by maikale** [comment]
> innodb_buffer_pool_size to 32 GB

I didn't do that either and had even more problems than a solution.

**Comment by hermensbas** [comment]
Indeed study the wiki and configurarion, and obviously monitor your hardware resources. I am running my days for days with 5k bots with no problem. Also keep in mind running the amount of real players in different areas will effect the performance. Still need to make it configerable whether all bots in area are 100% active or not.
