### ISSUE TITLE
Lag spikes while loot is available

### ISSUE THREAD

**Issue by natugrumu** [liyunfan1223/mod-playerbots#744]
**Describe the bug**

Edit*  While AiPlayerbot.TwoRoundsGearInit = 1 

Lag spikes while loot is available to playerbots (not rndbots). Especially bad in Desolace (at least the worst I've encountered so far).

**Commit hash**
c0b185935bd55fe6fdf8d0d62bc2c3256d6596a8

**To Reproduce**
1. Grab a party of playerbots, all with 2 leveled professions. 
2. Head to Desolace.
3. Kill a whole bunch of mobs near each other.
4. You want to get a lot of loot to drop fast to really see the spikes. It's barely noticeable if you kill one mob and loot it then go to the next.
5. For science do another mass killing after sending the playerbots offline for a completely lag free experience.

**Screenshots**
This is not a bad spike but I've seen them upward of 3000ms while truly committing a ton of murder.
![image_2024_11_27T06_42_44_188Z](https://github.com/user-attachments/assets/c81aef6d-dd3e-4588-87b4-ff328f9b1d3f)

**Desktop (please complete the following information):**
Win10
Only
Playerbots and Ahbot mods installed

**Additional context**
It seems like it might be area specific since I have been playing with them for about a month and a half now and just recently started encountering this in Desolace, Tanaris, Maraudon and Zul'farrak dungeons.

One user can cause the same lag spikes for another user if they are in the same zone. I'm unsure if it affect other regions I forgot to test that.

Thank you so much to everyone who works on this project. This is soo good and I love it so much!

**Comment by gododog85** [comment]
i had same issue. I changed playbot.conf option

**Comment by natugrumu** [comment]
Going to try that immediately when I get home.  Thank you for the tip.

**Comment by natugrumu** [comment]
Changing to AiPlayerbot.AutoEquipUpgradeLoot = 0 made the lag disappear completely. Thanks again for the heads up.

Such a strange setting to cause lag in only certain zones.

**Comment by noisiver** [comment]
I never noticed any issues with this. I was grinding in Tanaris yesterday, just killing a ton of stuff and completing some quests and no lag occurred - not even when they all equipped gear automatically that they got from quests.

**Comment by natugrumu** [comment]
Would you mind trying Zul'Farrak for me? Specifically the room where you touch the sand piles and a ton of mobs spawn. 

The lag I'm getting only occurs and gets worse depending on how many lootables are on the ground and only in certain zones, skinnable creatures adds to it as well.

I'm trying to figure out whats going on because the auto equip feature is amazing and I want to keep using it.

Thank you mucho gracias.

**Comment by noisiver** [comment]
When I were grinding in Tanaris I never looted anything unless I was specifically looking for quest items, which wasn't often. I was just running around killing everything I could find. I'll try to check ZF soon.

**Comment by natugrumu** [comment]
Excellent thank you. Do you know of any server command or other method I could use to test or debug where the latency is happening at? Just a general idea and I'll look it up and figure it out.

**Comment by natugrumu** [comment]
More info.
Reverting to the default setting AiPlayerbot.TwoRoundsGearInit = 0 has solved the problem also.
Now I am able to use AutoEquipUpgradeLoot!

**Comment by hermensbas** [comment]
> Why is it closed? Multiple ppl state they ran into the problem. Seems there's an issue here, perhaps mitigated by workarounds by a config combination but not by an actual given solution.

did you try and reproduce?

**Comment by hermensbas** [comment]
ive used default config, multple config setups. Cant reproduce, no lag, no spikes. Maybe its specific config setup, add-on or other module. Surely we can keep it open, re open but with what intend?
