### ISSUE TITLE
formation near

### ISSUE THREAD

**Issue by gododog85** [liyunfan1223/mod-playerbots#749]
Command formation near , the bots are overlapped in a single point. They used to stand in a circle near to the player, which is a bit odd.

When I summon the bots, they will gather in a circle nearby but they overlapped into a single point when I move. 

commit : 3e449fff731fd79bfc1fc5e5f8abd1f23ea81ac8

**Comment by serverwar** [comment]
And tell you more about this crash formation, with many real players

**Comment by locchi93** [comment]
I confirm the problem, and I also think other formations behave strangely, such as the "formation circle". [this recent commit](https://github.com/liyunfan1223/mod-playerbots/commit/af0a6b73e16c959450ae206888e010d8deb02608) could be responsible, it modifies the `GetFollowAngle` function used by multiple formations.

**Comment by locchi93** [comment]
@EricksOliveira Hi, I saw that [this commit](https://github.com/liyunfan1223/mod-playerbots/commit/af0a6b73e16c959450ae206888e010d8deb02608) was made by you, in trying to find the problem I removed the check to `member == bot` inside `GetFollowAngle` (line 440, 452 and 465) and this seams to fix the "formation near". I'm not very familiar with the code and therefore I can't understand whether removing this part risks breaking something you fixed or not.
