### ISSUE TITLE
编译通不过

### ISSUE THREAD

**Issue by lanhai** [liyunfan1223/mod-playerbots#75]
15>已完成生成项目“modules.vcxproj”的操作 - 失败。
18>------ 已启动生成: 项目: worldserver, 配置: RelWithDebInfo x64 ------
18>Building Custom Rule J:/Azerothcore/azerothcore-wotlk-bot/src/server/apps/CMakeLists.txt
18>cmake_pch.cxx
18>Main.cpp
18>ACSoap.cpp
18>CliRunnable.cpp
18>RASession.cpp
18>WheatyExceptionReport.cpp
18>ServiceWin32.cpp
18>LINK : fatal error LNK1181: 无法打开输入文件“..\..\..\modules\RelWithDebInfo\modules.lib”
18>已完成生成项目“worldserver.vcxproj”的操作 - 失败。
19>------ 已启动生成: 项目: ALL_BUILD, 配置: RelWithDebInfo x64 ------
19>Building Custom Rule J:/Azerothcore/azerothcore-wotlk-bot/CMakeLists.txt
========== 生成: 14 成功，5 失败，0 最新，0 已跳过 ==========
========== 生成 于 2:23 完成，耗时 09:57.590 分钟 ==========

**Comment by oiuv** [comment]
你是怎么编译的，不是把module放到项目中直接编译AC服务端吗？

https://www.zhihu.com/answer/3337215148

**Comment by liyunfan1223** [comment]
Check CI https://github.com/liyunfan1223/mod-playerbots/actions.
