### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#754]
**Describe the bug**
Crash 

**Commit hash**
latest this day 1/12

**To Reproduce**
1. Go to auctionhous and spam dungs

**Expected behavior**
When i stand in Orgrimmar in auction house and spam Dungeons , When the dungeon is over server crash after Dungen when you are tp back it should work

**Screenshots**

**Desktop (please complete the following information):**
Debian 12

**Additional context**

**Comment by noisiver** [comment]
Need a crash log to determine the cause. Without it, it's impossible to find and even less possible to fix the issue.

**Comment by davvvve1** [comment]
Gonna fix that after work. Thank u

**Comment by Dreathean** [comment]
Closing due to no crash logs as requested after 2 weeks, please re-open if you are still experiencing this issue with crash logs on latest commit

**Comment by Povotech** [comment]
the server does not stay online for more than 20 minutes without crashing, I just let the world run to see and the server crashes, I have no crash log the file is empty, it is generated well at the time of the crash but 0 data

**Comment by PaoloBenigni** [comment]
Have you tried gbd?
