### ISSUE TITLE
worldserver.exe program crash feedback.

### ISSUE THREAD

**Issue by bing88868** [liyunfan1223/mod-playerbots#76]
**Describe the bug**
After using the "talk" command for the robot and any shop NPC, worldserver.exe will immediately crash. This is compiled from the latest updated version of the source code.

**Screenshots**
For example, in 闪金镇, the proud Lion King Inn, Innkeeper Farley <Innkeeper> uses "talk" to expand worldserver.exe.
![拓机提交01](https://github.com/liyunfan1223/mod-playerbots/assets/10162018/3496a9e1-7b4e-447b-9372-71c12a957f89)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2022 21H2]

**Comment by qyh214** [comment]
无法复现哎，是最新的核心和最新的mod吗

**Comment by bing88868** [comment]
没有，只装了这里的 playerbot，就是与商人类NPC 使用 talk，就会拓机。

**Comment by bing88868** [comment]
这个应该是老问题了，用别人11月初编译的版本也是一样，一用 talk 完成任务命令，立即拓机。

**Comment by liyunfan1223** [comment]
Thank you for your report, confirmed the issue.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/187989ddd1d3a765ef734021f4044199d6c07016
