### ISSUE TITLE
本地化改进：技能，物品，任务，生物改为本地化支持

### ISSUE THREAD

**Issue by qyh214** [liyunfan1223/mod-playerbots#77]
**Is your feature request related to a problem? Please describe.**
#29 #62 

**Describe the solution you'd like**
这些问题应该是看了下需要dbc采用enus来解决，例如不会释放技能等问题；另外，显示的物品、任务、npc会默认读取enus的缺省数据，应该根据客户端语言读取相对应的数据

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by oiuv** [comment]
dbc采用enUS是什么意思？是要用enUS的客户端来生成dbc吗？

**Comment by AlvinZhu** [comment]
https://github.com/liyunfan1223/azerothcore-wotlk/pull/1
这个PR可以解决使用enUS DBC 带来的本地化问题。

另外在使用playerbot过程中，机器人名字，机器人聊天、物品、任务名称，这些需要去搜索并本地化相应的代码和数据库。

**Comment by oiuv** [comment]
> [liyunfan1223/azerothcore-wotlk#1](https://github.com/liyunfan1223/azerothcore-wotlk/pull/1) 这个PR可以解决使用enUS DBC 带来的本地化问题。
> 
> 另外在使用playerbot过程中，机器人名字，机器人聊天、物品、任务名称，这些需要去搜索并本地化相应的代码和数据库。

你这个详细说一下，是不是DBC可以正常的用zhCN，但如果用了zhCN的，机器人是怎么调enUS的DBC呢？

**Comment by AlvinZhu** [comment]
> > [liyunfan1223/azerothcore-wotlk#1](https://github.com/liyunfan1223/azerothcore-wotlk/pull/1) 这个PR可以解决使用enUS DBC 带来的本地化问题。
> > 另外在使用playerbot过程中，机器人名字，机器人聊天、物品、任务名称，这些需要去搜索并本地化相应的代码和数据库。
> 
> 你这个详细说一下，是不是DBC可以正常的用zhCN，但如果用了zhCN的，机器人是怎么调enUS的DBC呢？

Server端同时放enUS和zhCN的两套DBC。机器人调enUS,客户端调用zhCN。

**Comment by AlvinZhu** [comment]
> > [liyunfan1223/azerothcore-wotlk#1](https://github.com/liyunfan1223/azerothcore-wotlk/pull/1) 这个PR可以解决使用enUS DBC 带来的本地化问题。
> > 另外在使用playerbot过程中，机器人名字，机器人聊天、物品、任务名称，这些需要去搜索并本地化相应的代码和数据库。
> 
> @AlvinZhu 大佬，我编译了你的最新源码，请问你的那个alvin里自定义sql需要手动导入还是启动时会自动导入呢？playerbot的名字好像是没有汉化吧？另外，启动服务端时有一个关于ID:70581的NPCBOT名字不在表里的红字提醒是什么原因？ 还有，我试了下组了PBOT后进不了战场，是不是当有两种机器人时只能NPCBOT才能打战场呢？我单独编译liyunfan大佬的PBOT组了同号下的机器人可以进战场，但没试过组野外机器人是否也能进

自定义的sql主要是一些汉化和修复。自定义的sql要手动导入。不然会有红字。
但是你这个NPCBOT的红字我没遇到过。可能是你原来的数据库和我的不兼容。我清空数据库重新生成是没问题的。
战场我没试过。也不排除npcbot和playbot有冲突的可能性。

**Comment by oiuv** [comment]
> > > [liyunfan1223/azerothcore-wotlk#1](https://github.com/liyunfan1223/azerothcore-wotlk/pull/1) 这个PR可以解决使用enUS DBC 带来的本地化问题。
> > > 另外在使用playerbot过程中，机器人名字，机器人聊天、物品、任务名称，这些需要去搜索并本地化相应的代码和数据库。
> > 
> > 
> > 你这个详细说一下，是不是DBC可以正常的用zhCN，但如果用了zhCN的，机器人是怎么调enUS的DBC呢？
> 
> Server端同时放enUS和zhCN的两套DBC。机器人调enUS,客户端调用zhCN。

不明白，data不是自动调用`Cameras/dbc/maps/mmaps/vmaps`吗?怎么放二个dbc？

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/azerothcore-wotlk/pull/1
