### ISSUE TITLE
player alts as bots getting gear upgrades

### ISSUE THREAD

**Issue by xSparky911x** [liyunfan1223/mod-playerbots#770]
Forgive my ability to properly use bug reports but here goes. Not sure you would consider this a bug or not but I think its a bit of an issue.

**Describe the bug**
Using the players alts as bots, the init command doesn't work as expected and should be. The issue is though that the autogear whisper does. Is this intended? I think its a bit of an issue because once that character is autogeared they get to keep the gear. I think the autogear command should be disable for bots in the playerbot roster (I think that's what I mean) just like the init=auto is.

**Commit hash**
437f816b15e99be828ac69288e7586506302a726

**To Reproduce**
1. Bring a player alt online as a bot
2. whisper "autogear" to that alt bot
3. log out of current character and then on as that player alt
4. See all your new gear you didn't earn

**Expected behavior**
Not to be able to use autogear on player alts as bots.

**Comment by Dreathean** [comment]
Well, you can disable autogear in the config.

**Comment by xSparky911x** [comment]
Fixed in https://github.com/liyunfan1223/mod-playerbots/commit/cbadb5765facf48bdb7a7930f2709bae843264f4
