### ISSUE TITLE
Some BUGs about PLAYERBOT after enabling automatic equipment.

### ISSUE THREAD

**Issue by moncat2005** [liyunfan1223/mod-playerbots#773]
**Describe the bug**
The warrior of playerbot, with a fury talent, has activated automatic equip.
When the playerbot get up new loot long handled weapon or two handed weapon, there are also multiple weapons in the bag.
At this point, the playerbot an automatic equip long handled weapon or two handed weapon action occurs, but then attempts are made to equip the deputy with weapons, resulting in a cycle of constantly switching equip weapons.

**Commit hash**
`mod-playerbots` `c436781`

**To Reproduce**
1. enabling automatic equip
2. The warrior of playerbot, with a fury talent
3. playerbot has multiple weapons in the bag
4. playerbot get up new loot weapons and automatic equip long handled weapon/two handed weapon action
5. resulting in a cycle of constantly switching equip weapons.

**Expected behavior**
Optimize the weapon and equip selection logic of playerbot based on talent mode.
Exclude the issue of dual handed weapon equip cycling without dual wielding skills.

**Screenshots**
![image](https://github.com/user-attachments/assets/ebb40814-e800-4cfe-ba17-ed6e5dacbe05)

**Comment by avirar** [comment]
#777

This should help. But the issue remains that when a bot has no item (or a very low scoring item), they will flag nearly everything as an upgrade, and then equip items progressively as the visitor function iterates through their inventory slots.

**Comment by moncat2005** [comment]
Thank you, I will try this new logic.

**Comment by Dreathean** [comment]
Going to close this as that PR has been merged, if you still have this issue @moncat2005 please let us know
