### ISSUE TITLE
拍卖行插件模块无法共同编译报错

### ISSUE THREAD

**Issue by JoshuaWuP** [liyunfan1223/mod-playerbots#776]
Ah_HOT自动拍卖行模块编译器无法共同编译

**Comment by noisiver** [comment]
I use mod-ah-bot with playerbots and it compiles fine. Since you neglected to include any information about whatever error you're getting it's easy to assume the claim is invalid.

**Comment by TheSCREWEDSoftware** [comment]
Just made the same issue in AC, didn't fill the form as it should nor is in english. 

[Here](https://github.com/azerothcore/azerothcore-wotlk/issues?q=is%3Aissue+author%3AJoshuaWuP+is%3Aclosed) so i will pressume he will spam his issue all over where he can about his AH issue.

**Comment by JoshuaWuP** [comment]
![微信图片_20241218195307](https://github.com/user-attachments/assets/c90f9193-fd7b-4ba9-b437-13cf97f33579)
The compile problem is in the picture,thanks

**Comment by Dreathean** [comment]
I too use ah-bot with playerbots with no issue, though I have not grabbed any updates from ah-bot in a while if something recent broke compatibility. At any rate, your compile problem is with ah-bot, not playerbots and this github does not do anything with ah-bot.

**Comment by noisiver** [comment]
> ![微信图片_20241218195307](https://private-user-images.githubusercontent.com/160583336/396895837-c90f9193-fd7b-4ba9-b437-13cf97f33579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MzUyOTIsIm5iZiI6MTczNDUzNDk5MiwicGF0aCI6Ii8xNjA1ODMzMzYvMzk2ODk1ODM3LWM5MGY5MTkzLWZkN2ItNGJhOS1iNDM3LTEzY2Y5N2YzMzU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxNTE2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzBkZTk0M2Y4MDFlOWU3NjExMTA5YmIxNzE5NGZiOGYwM2Y5ODU1ZThhYjk0NmNkMmQyZjc4YWJkYTZkYjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jLp1RbtWjR_LVcUJMVP6oHYH6Lm577CqV07-WhyX0Ng) The compile problem is in the picture,thanks

You need to update the ah-bot module, but this is completely unrelated to playerbots and isn't a compability issue between the two. It's because the core was changed, essentially a typo was corrected, and the module needs to reflect that. So.. update it.

**Comment by JoshuaWuP** [comment]
how to update ah-hot?can you share me the module,I download it!

**Comment by leewheel** [comment]
There is nothing wrong with this module. I have been using it without any problems.
