### ISSUE TITLE
After the latest update, the startup report configuration file is missing parameter information.

### ISSUE THREAD

**Issue by moncat2005** [liyunfan1223/mod-playerbots#787]
**Describe the bug**
Config: Missing property AiPlayerbot.BotActiveAloneWhenInRadius in config file /home/moncat/azeroth-server/etc/worldserver.conf, add "AiPlayerbot.BotActiveAloneWhenInRadius = 150" to this file or define 'AC_AI_PLAYERBOT_BOT_ACTIVE_ALONE_WHEN_IN_RADIUS' as an environment variable.

**Commit hash**
`mod-playerbots`  `cbadb57`

**Comment by xSparky911x** [comment]
I was running into this problem with other functions added removed from the module and found that you need to update the config.dist files as well. There will be an updated conf.dist file in the new version that also needs to be copied over to your env.dist.etc/modules folder and if you have a modified .conf file you need to make the changes to it as well

**Comment by moncat2005** [comment]
I confirm that the new configuration parameters have been added to mod-playerbots.conf.
Please note that the prompt now indicates that this parameter is missing from worldserver. conf.
Moreover, this parameter (AiPlayerbot. BotActiveAloneWhenInRadius=150) is not included in the newly compiled and installed worldserver. conf.dist.
I tried manually adding it to worldserver. conf, and the startup alarm disappeared.
But there must be something wrong here.

**Comment by xSparky911x** [comment]
Right what Im saying is you also need the new playerbots.conf.dist file copied over to your env/dist/env/modules folder. Notice the .dist extension

**Comment by moncat2005** [comment]
1、 I didn't find AiPlayerbot. BotActiveAloneWhenInRadius=150 in the new worldserver.conf.dist file.
2、I confirm that the newly added parameters in playerbots.conf.dist that I have compiled and installed into etc/modules have been copied to the etc/modules/playerbots.conf file.

**Comment by xSparky911x** [comment]
on line 1519 of playerbots.conf.dist there is a similar line
```AiPlayerbot.BotActiveAloneForceWhenInRadius = 150```

**Comment by xSparky911x** [comment]
Ahh found the issue

Typo in the config
has ```AiPlayerbot.BotActiveAloneForceWhenInRadius = 150``` in the config file but in the PlayerbotAI.cpp file it has ```sPlayerbotAIConfig->BotActiveAloneWhenInRadius```
