### ISSUE TITLE
bot 反复刷回主城

### ISSUE THREAD

**Issue by garfieldz90** [liyunfan1223/mod-playerbots#8]
1，联盟的暗夜精灵，德莱尼的bot，如果组队带着他们去旅行没问题，但是如果取消组队，或者只是机器人的组队的情况，暗夜精灵和德莱尼的bot都会刷回他们的主城或者他们的城镇。矮人和人类没有这个情况。
2，部落的情况还没去看，后续再去看看

**Comment by liyunfan1223** [comment]
Thank you for your feedback! 

Regarding this problem, have you enabled the AutoDoQuests option in the configuration to enable the rpg strategy, and can you reproduce this problem stably? Also, it might be expected behavior for Hearthstone to come back to town after a random bot leaves the party.

**Comment by garfieldz90** [comment]
i didnt change any config except max bot number, i'll try trace one Draenei rndbot after leave the party, thanks your hard work!
