### ISSUE TITLE
Crash due to the new world buff strategy

### ISSUE THREAD

**Issue by noisiver** [liyunfan1223/mod-playerbots#808]
As soon as I use `nc +worldbuff` the server crashes. I'm including the crash log so hopefully someone who knows what's going on can have a look at it.

[gdb.txt](https://github.com/user-attachments/files/18220599/gdb.txt)

**Comment by kadeshar** [comment]
Made PR for reverting changes in trigger.
https://github.com/liyunfan1223/mod-playerbots/pull/809

**Comment by noisiver** [comment]
Closing this for now then. I haven't tested the new changes yet but it's safe to assume this issue is resolved at least.

**Comment by kadeshar** [comment]
I dont have linux arm environment but both version working for me in windows environment.
I restored orginal ike3 playerbots implementation.
