### ISSUE TITLE
Account passwords are not case sensitive.

### ISSUE THREAD

**Issue by Stuntmonkey4u** [liyunfan1223/mod-playerbots#812]
**Describe the bug**
Account passwords are not case sensitive. 

**Commit hash**
7347f6493898a9109cdd9b886ac67bc7c57debe9

**To Reproduce**
1. Create an account or use existing account
2. Type in account password in any case you want ie. PassWord, pAsswOrd, password, PASSWORD, etc..

**Expected behavior**
Whether bug or feature, The account password should be more secure by only accepting case sensitive passwords, or allowing switch to enable that functionality.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 24.04

**Additional context**

**Comment by noisiver** [comment]
This is completely unrelated to playerbots and even AzerothCore. The 3.3.5 client is not case-sensitive and this is not something anyone can fix unless you ask Blizzard to change the 3.3.5 client and send you an updated version.

Why Blizzard decided to make the client case-insensitive I have no idea but that's what it is.
