### ISSUE TITLE
No name found for race and gender

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#821]
**Describe the bug**
Creating random bot characters for account: [9998/10000]
No name found for race and gender: 12
Fail to create character for account 9998
No name found for race and gender: 13
Fail to create character for account 9998
No name found for race and gender: 6
Fail to create character for account 9998
No name found for race and gender: 14
Fail to create character for account 9998
Creating random bot characters for account: [9999/10000]
No name found for race and gender: 7
Fail to create character for account 9999
No name found for race and gender: 17
Fail to create character for account 9999
No name found for race and gender: 9
Fail to create character for account 9999
No name found for race and gender: 17
Fail to create character for account 9999
No name found for race and gender: 7
Fail to create character for account 9999
Creating random bot characters for account: [10000/10000]

**Commit hash**
[The hash of the current commit.](https://github.com/liyunfan1223/mod-playerbots/commits/master/)

**To Reproduce**
cmake
make
set config account 10000
./worldserver

**Expected behavior**

Is the creation successful or not? Isn't it possible to directly randomly() generate an English user name? Why is the error reported?

**Comment by kadeshar** [comment]
Each possible names for race+gender combination are stored in table acore_characters.playerbots_names. If in process of character creation there will be not free name for this combination then error shows in console and system try create next randomized character and then is possibility that for next combination will be free name (thats why in next try character is created). Currently there is list of 100000 names which is more than enought for any server. If you want more create extended list with name + number which is combination (race + gender) 
![obraz](https://github.com/user-attachments/assets/7ad3d1ae-6fb3-4cc0-89c7-8fb0d1b53d95)
Theoretically, we can add some random suffix when name poll is depleted but easiest is use chatGTP to generate more names :P
