### ISSUE TITLE
Oculus bots won't fly despite mount

### ISSUE THREAD

**Issue by abananihi** [liyunfan1223/mod-playerbots#823]
**Describe the bug**
In herioric The Oculus dungeon, bots will mount properly when the player mounts but refuse to fly/move when the player moves. Dungeon is not completable due to this. It was working on an older commit (last time I finished the dungeon was ~1 month ago there was no such issue)

**Commit hash**
1c22a9a9ffabeafaccac3157055c513fef0f6386

**To Reproduce**
1. Add bots and then go to the Oculus
2. Finish first boss, get any essence and use it
3. See bots will use essence and mount, but won't follow player no matter what

**Expected behavior**
Bots should fly and follow player, and should use abilities properly.

**Additional Context**
I searched Discord there was at least one other player having the same issue.

**Comment by kadeshar** [comment]
Posted PR with fix https://github.com/liyunfan1223/mod-playerbots/pull/827
