### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by locchi93** [liyunfan1223/mod-playerbots#826]
**Describe the bug**
High CPU usage in docker installation (I only use the docker setup) after recent commits.
The problem was found in both the following commits that I tested. I don't know exactly where he entered.

Normal CPU usage was around 20% with no player/bot online, now it is reported at around 80%. I noticed a change from the power consumption data of my server running the docker instance, now is about 20W higher than usual.

**Commit hash**
- [1ed6645](https://github.com/liyunfan1223/mod-playerbots/commit/1ed6645119c9736e70a326bd3d8afc8061f9848f)
- [d9f9d98](https://github.com/liyunfan1223/mod-playerbots/commit/d9f9d980cff7b08864bf7c0bf4386d5aa2341971)

**To Reproduce**
1. Startup server with `docker compose up -d`
2. open `htop` to see CPU usage. 

**Expected behavior**
Lower CPU usage like before.

**Screenshots**
![Screenshot from 2024-12-28 15-17-53](https://github.com/user-attachments/assets/cf4f4589-9e46-4efe-8254-1bdb7824d5fa)

**Desktop (please complete the following information):**
 - OS: Ubuntu server 22.04.x

**Additional context**

I have no random-bot in my configuration (`AiPlayerbot.RandomBotAutologin = 0`, `AiPlayerbot.RandomBotAccountCount = 0`), I use this mod only for playing with my alts. I will provide my `playerbots.conf` if needed.

The only modification I have inside `worldserver.conf` are:
- `MinWorldUpdateTime = 10`
- `MapUpdateInterval = 100`

**Comment by blinkysc** [comment]
Might be from NetworkThread.h. It has been fixed in master AC but not merged yet in Playerbots AC. It’s a few edits to try out. https://github.com/azerothcore/azerothcore-wotlk/commit/24726545fbb189c3fb23b5a2ceded8a04bd3f7ab

**Comment by PaoloBenigni** [comment]
What hardware are you running? How many bots?

**Comment by dedahr** [comment]
Y could be that, this fixed my idling also (Windows environment). Recently after patches it boost to almost 5GHz, not it sits on 2-3GHz as before and no more fan havoc.

**Comment by noisiver** [comment]
If this is originally an issue with stock AC it's unrelated to playerbots and this issue should be closed.

**Comment by Dreathean** [comment]
Yes this is a stock AC issue that has already been fixed in master and will be resolved here once Liyunfan merges to his fork, or if anyone doesn't want to wait for that they can merge updates from stock or apply the direct fix linked above. Agreed we can close this.
