### ISSUE TITLE
rtsc go bots wont stay

### ISSUE THREAD

**Issue by crispinknox** [liyunfan1223/mod-playerbots#828]
**Describe the bug**
when you tell bots rtsc go 1 etc they run to spot and then run back

**Expected behavior**
the bots should run to position and then wait until recalled.

**Comment by kadeshar** [comment]
Currently "rtsc go" working on stance guard ("co +guard"). 
https://www.youtube.com/watch?v=RDMxc7aJD58&list=PLOjP9sYKFs7xnZWAF_zAEJ6-57gMLNV-e&index=1&t=67s
