### ISSUE TITLE
找不到设置机器人在线时间的配置，现在机器人挂机太厉害了

### ISSUE THREAD

**Issue by oiuv** [liyunfan1223/mod-playerbots#83]
我正常在我的服务器加上了AI，因为我的服务端也是学习研究用，注册网页上用的也是开源的项目，上面有玩家排行榜，但现在的问题是机器人是24小时在线的，游戏时间很快就超过了真实玩家，排名直接把真实玩家挤没了。
![image](https://github.com/liyunfan1223/mod-playerbots/assets/13300261/0ab6b188-d3f7-4ea4-a2a4-f46525cab885)
对比下面金币排行，中文角色的是真实玩家数据
![image](https://github.com/liyunfan1223/mod-playerbots/assets/13300261/124bdfb9-4d2f-4f1b-a9dd-732734c5c489)

有没有可以配置机器人在线时间的，和真人一样，同一个角色不要24小时在线的，可以换不同的机器人轮流上线嘛。

**Comment by CoffeeFantasy** [comment]
我觉得机器人现在好像就是轮流的

**Comment by CoffeeFantasy** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/146047757/d7f8a87e-24eb-414e-8f58-15bdc2555dce)
你试试这个配置呢，我没试过

**Comment by CoffeeFantasy** [comment]
我觉得现在机器人就是轮流的，会有部分下线换其他上线，只是很少一部分

**Comment by CoffeeFantasy** [comment]
![image](https://github.com/liyunfan1223/mod-playerbots/assets/146047757/a373a94d-7d1a-4bf1-ad89-5544bc09a26b)
试试这几个配置呢，我这边是机器人升级很慢，我怀疑跟配置有关系

**Comment by oiuv** [comment]
```ini
# Specify percent of active bots
# The default is 10. With 10% of all bots going active or inactive each minute.
AiPlayerbot.BotActiveAlone = 100
```
@CoffeeFantasy 这个？100是不是所有机器人都活跃？

**Comment by liyunfan1223** [comment]
Try setting `AiPlayerbot.EnableRotation = 1` and resetting rndbot. You can reduce the online time of each bot by increasing `AiPlayerbot.RotationPoolSize`.

**Comment by oiuv** [comment]
@liyunfan1223 那下面这个配置默认是100，要改动吗？主要是什么作用。

```ini
# Specify percent of active bots
# The default is 10. With 10% of all bots going active or inactive each minute.
AiPlayerbot.BotActiveAlone = 100
```

**Comment by oiuv** [comment]
还有修改配置后如何在不重启服务器的情况下让配置生效，测试`reload config`无效

**Comment by oiuv** [comment]
> Try setting `AiPlayerbot.EnableRotation = 1` and resetting rndbot. You can reduce the online time of each bot by increasing `AiPlayerbot.RotationPoolSize`.

**resetting rndbot** 应该怎么操作？

**Comment by liyunfan1223** [comment]
> > Try setting `AiPlayerbot.EnableRotation = 1` and resetting rndbot. You can reduce the online time of each bot by increasing `AiPlayerbot.RotationPoolSize`.
> 
> **resetting rndbot** 应该怎么操作？

`.playerbot rndbot reset` in the server console

**Comment by oiuv** [comment]
> > > Try setting `AiPlayerbot.EnableRotation = 1` and resetting rndbot. You can reduce the online time of each bot by increasing `AiPlayerbot.RotationPoolSize`.
> > 
> > 
> > **resetting rndbot** 应该怎么操作？
> 
> `.playerbot rndbot reset` in the server console

还有这种指令啊，都不知道，另外我看了还有 gtask 和 pmon 是啥意思

Possible subcommands:
|- playerbots gtask
|- playerbots pmon
|- playerbots rndbot

**Comment by alexyang-sea** [comment]
> ![image](https://private-user-images.githubusercontent.com/146047757/292793924-a373a94d-7d1a-4bf1-ad89-5544bc09a26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzI5MjcsIm5iZiI6MTcwMzU3MjYyNywicGF0aCI6Ii8xNDYwNDc3NTcvMjkyNzkzOTI0LWEzNzNhOTRkLTdkMWEtNGJmMS1hZDg5LTU1NDRiYzA5YTI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNjM3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDZhNWZkZGY3M2QwMTg2ZmEzYjA1MGVjNTM0ZmU2Zjc1NmJlM2I1ZWJmYTMwZTczMGJmODM0ZDRjZDIwNzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SriZTk0pd3u7ZGYixk375Zvxk-jIxXPB7sIOKmYHGUg) 试试这几个配置呢，我这边是机器人升级很慢，我怀疑跟配置有关系

我用的是上线同号机器人组队，我也感觉机器人升级速度远远赶不上我自己的速度，即使我已经把机器人的经验倍率改为了10也一样，不知道还有什么设置可以提高跟自己组队的机器人的升级速度

**Comment by oiuv** [comment]
> > > Try setting `AiPlayerbot.EnableRotation = 1` and resetting rndbot. You can reduce the online time of each bot by increasing `AiPlayerbot.RotationPoolSize`.
> > 
> > 
> > **resetting rndbot** 应该怎么操作？
> 
> `.playerbot rndbot reset` in the server console

使用这个方案，已解决需求，可以关闭本议题了。
