### ISSUE TITLE
大佬你好，请问这个mod不能直接放入我自己的源码Modules文件夹里，然后CMake吗

### ISSUE THREAD

**Issue by lene42287** [liyunfan1223/mod-playerbots#84]
大佬你好，这个mod是不是不能直接放入我自己的源码Modules文件夹里，然后CMake吧，只能用您这个https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot     这里的源码来编译吗

**Comment by qyh214** [comment]
是的，有些源码的修改，可以直接用这里分支的，基本是做到和az的同步更新的
