### ISSUE TITLE
机器人天赋点可以自动选择吗

### ISSUE THREAD

**Issue by alexyang-sea** [liyunfan1223/mod-playerbots#85]
我现在用的同号上线机器人，但发现他们没有自动选择天赋点，我也无法给他们分配。不知道后期能否实现只要我给机器人切换到哪个天赋，那么对应的最佳天赋点就能自动分配给机器人？

**Comment by liyunfan1223** [comment]
Similar to https://github.com/liyunfan1223/mod-playerbots/issues/60.
