### ISSUE TITLE
Can't get playerbot to loot bodies or interact with game objects

### ISSUE THREAD

**Issue by Nevinkai** [liyunfan1223/mod-playerbots#86]
I have been trying to get the playerbot to loot bodies using the commands given on "https://ike3.github.io/mangosbot-docs/" but the bot would not loot the body. I have used "d loot", which causes the playerbot to say "Loot: Useless". I have tried to use "d add all loot", where the bot will make a sound effect saying their going to loot, but will proceed not to do anything. If I attempt the same command again the bot will say "add all loot: failed". I have tried changing looting strategy, but that did not change anything. I have also tried to get the bot to loot game objects like chests using "u [gameobject]", but the bot will not do or say anything. The server is running on an Ubuntu 22.04 machine.

**Comment by noisiver** [comment]
Did you try `/p add all loot`? According to the addon, that should be it. You say `d add all loot` but I'm not sure what that means. Personally I just have them loot in their strategy and they loot fine.
