### ISSUE TITLE
`AiPlayerbot.AddClassCommand=0`后GM也不能用了（而说明中0是GM only）

### ISSUE THREAD

**Issue by oiuv** [liyunfan1223/mod-playerbots#87]
`AiPlayerbot.AddClassCommand=0`后GM也不能用了，我是用目前的最新版本编译的。

当我把以下配置`AiPlayerbot.AddClassCommand`修改为0后，根据说明应该是仅GM可用，可实际上GM也不能用了。
```ini
# Enable/Disable create bot by addclass command (0 = GM only, 1 = enable)
# default: 1 (enable)
AiPlayerbot.AddClassCommand = 0
```

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/pull/89
