### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by kekeshgreen** [liyunfan1223/mod-playerbots#90]
**Describe the bug**
When multiple player bots log out at the same time the server crashes

**Commit hash**
The hash of the current commit.

**To Reproduce**
Wait for multiple player bots to log out at the same time

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian

**Additional context**

**Comment by liyunfan1223** [comment]
Thanks for your report. This may be an old problem, try updating to the latest version. If it still occurs, please provide the gdb log for easy analysis.
