### ISSUE TITLE
机器人好像不会roll装备，不知道是我不会用，还是没有这个功能

### ISSUE THREAD

**Issue by rootdgy** [liyunfan1223/mod-playerbots#97]
如题，机器人只会放弃

**Comment by oiuv** [comment]
是你不会用，你可以tell机器人help看帮助，另外建议选择队长分配模式，对需要ROLL的装备你来分配。

**Comment by liyunfan1223** [comment]
Not fully implemented yet.

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/0b105e70d71386dc18acd898788f1b8c0ff0c9bc
