### ISSUE TITLE
当玩家在骑乘状态召唤机器人上线时会出现机器人无法正确召唤坐骑的BUG

### ISSUE THREAD

**Issue by oiuv** [liyunfan1223/mod-playerbots#98]
机器人召唤什么坐骑（跑的还是飞的）和玩家有关，但我出现过好几次机器人队友不能召唤骑马的问题，只见他们不停的召唤但就是不成功，后来发现自己下马后切换一种坐骑后他们才能正常，这个问题主要是在第一次召唤队友时出现。

我目前测试复现的情况主要是针对自己生成的随机机器人队友，可以使用以下方式简单复现BUG：

在组队状态你在骑乘状态选择下线，这样他们全部下线，如果还在20秒倒计时时可以取消不线，然后你再把他们全召唤上线，这时他们会自动上马，但实际上不成功，只会不停的做召唤动作，你只有换一种坐骑后他们才能正常。

![image](https://github.com/liyunfan1223/mod-playerbots/assets/13300261/594170c7-c6ac-4129-8b48-0a27136d5047)
![image](https://github.com/liyunfan1223/mod-playerbots/assets/13300261/7cd354eb-4578-4733-b3b7-b6dc382d7f01)

**Comment by liyunfan1223** [comment]
Comfired.
