### ISSUE TITLE
Bots greatly inactive after Fix movement on slope

### ISSUE THREAD

**Issue by nl-saw** [liyunfan1223/mod-playerbots#99]
**Describe the bug**
Running 2100 bots server and after the recent commit most of the bots just stand still and amass in places like the dalaran bank. The rest seems to mostly wander randomly for short distances. Next to that I noticed a small server performance decrease as well (+ 5-10 ms). Reverting back to previous commit restores normal behavior.

**Commit hash**
https://github.com/liyunfan1223/mod-playerbots/commit/b3c9f8d796b057bd370f823846001a76ac340d3b

**To Reproduce**
Have a good population bot-wise. It's a day and night difference (for me at least).

**Expected behavior**
Traveling bots as before that make great(er) distances and seem to actually do/be busy with something and not aimlessly wander in short, random directions.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by rogerc66** [comment]
I think your observation is true, looks like bots thinking more than doing now. They might standing still and thinking "Why I am here"

**Comment by liyunfan1223** [comment]
Yes, this commit introduces such a problem. I solved in the latest commit https://github.com/liyunfan1223/mod-playerbots/commit/8bf944c024fe3017a35fcef3f483d6060f541386. 

Server performance issues may not be completely resolved currently. Without seriously affecting performance, I want to solve some movement-related issues first.
